import type { Module } from "../types";

export const arraysHashing: Module = {
  id: "arrays-hashing",
  num: 2,
  name: "Arrays & Hashing",
  section: "1a",
  track: "both",
  order: 2,
  prereqIds: ["foundations"],
  resources: [
    { title: "USACO Guide — Intro to Sets & Maps (Bronze)", url: "https://usaco.guide/bronze/intro-sets" },
    { title: "CP-Algorithms — Hash Tables", url: "https://cp-algorithms.com/data_structures/hash_table.html" },
    { title: "CPH Book Ch. 4 — Data Structures", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Contains Duplicate",
      url: "https://leetcode.com/problems/contains-duplicate/",
      source: "LC 217",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Pattern 1 — set existence; simplest application",
    },
    {
      num: 2,
      title: "Valid Anagram",
      url: "https://leetcode.com/problems/valid-anagram/",
      source: "LC 242",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Pattern 2 — `Counter(s) == Counter(t)`",
    },
    {
      num: 3,
      title: "Two Sum",
      url: "https://leetcode.com/problems/two-sum/",
      source: "LC 1",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Pattern 3 — complement lookup; solves your Step 1 problem (CSES 1640)",
    },
    {
      num: 4,
      title: "Group Anagrams",
      url: "https://leetcode.com/problems/group-anagrams/",
      source: "LC 49",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Pattern 4 — `tuple(sorted(s))` as the canonical key; grouping by derived property",
    },
    {
      num: 5,
      title: "Valid Sudoku",
      url: "https://leetcode.com/problems/valid-sudoku/",
      source: "LC 36",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Pattern 1 multi-tracked — encode each constraint as `(track, value)` in one set (or maintain 27 separate sets). The encoding step is what scales the pattern across 27 parallel constraints",
    },
    {
      num: 6,
      title: "Top K Frequent Elements",
      url: "https://leetcode.com/problems/top-k-frequent-elements/",
      source: "LC 347",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Pattern 2 + frequency buckets — invert Counter into a `count → values` array and walk from the top; O(n) without sorting",
    },
    {
      num: 7,
      title: "Don't Be Last!",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=687",
      source: "USACO Bronze",
      difficulty: "medium",
      list: "UG ⭐",
      role: "combination",
      teaches: "Pattern 2 + sort by composite key — dict aggregation followed by tuple-sort to extract a ranked answer; first time Pattern 2 feeds into downstream processing",
    },
    {
      num: 8,
      title: "Cities and States",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=667",
      source: "USACO Silver",
      difficulty: "medium",
      list: "UG",
      role: "combination",
      teaches: "Pattern 3 + Pattern 4 together — complement is a derived tuple key `(state, city[:2])` rather than a number; teaches that \"complement\" generalises beyond arithmetic and foreshadows module 4's prefix-sum complement",
    },
    {
      num: 9,
      title: "Longest Consecutive Sequence",
      url: "https://leetcode.com/problems/longest-consecutive-sequence/",
      source: "LC 128",
      difficulty: "medium",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: O(n) requires that each element is visited a constant number of times — what discipline from earlier in the module enforces that? Pattern 5 — set-guided iteration. Only walk chains from their minimum so each element starts at most one walk.",
    },
  ],
};
