import type { Module } from "../types";

export const sorting: Module = {
  id: "sorting",
  num: 3,
  name: "Sorting",
  section: "1",
  track: "both",
  order: 3,
  prereqIds: ["arrays-hashing"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Intro to Sorting (Bronze)", url: "https://usaco.guide/bronze/intro-sorting" },
    { title: "USACO Guide — Sorting with Custom Comparators (Silver)", url: "https://usaco.guide/silver/sorting-custom" },
    { title: "CPH Book", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Sort an Array",
      url: "https://leetcode.com/problems/sort-an-array/",
      source: "LC 912",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Mergesort skeleton from Step 4 cold — write it without `sorted()`, verify against the built-in",
    },
    {
      num: 2,
      title: "Merge Sorted Array",
      url: "https://leetcode.com/problems/merge-sorted-array/",
      source: "LC 88",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "In-place merge — fill `nums1` from the back so writes never trample unread reads; same merge logic, different storage discipline",
    },
    {
      num: 3,
      title: "Sort Colors",
      url: "https://leetcode.com/problems/sort-colors/",
      source: "LC 75",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "New sub-pattern: counting sort for k = 3, or Dutch flag in one in-place O(1)-space pass",
    },
    {
      num: 4,
      title: "Relative Sort Array",
      url: "https://leetcode.com/problems/relative-sort-array/",
      source: "LC 1122",
      difficulty: "easy",
      list: "new",
      role: "extension",
      teaches: "`key=` from an external rank dict, with a fallback rank for unranked elements — the \"sort by an imposed ordering\" idiom",
    },
    {
      num: 5,
      title: "Largest Number",
      url: "https://leetcode.com/problems/largest-number/",
      source: "LC 179",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "`cmp_to_key` — pair-wise comparison when `key=` can't express the ordering, because `a + b` vs `b + a` is a property of the pair",
    },
    {
      num: 6,
      title: "Sorting Methods",
      url: "https://cses.fi/problemset/task/1162",
      source: "CSES",
      difficulty: "medium",
      list: "UG ⭐",
      role: "combination",
      teaches: "Solve Method 1 only (min adjacent swaps = inversion count) — mergesort + count-during-merge, `total = within-L + within-R + crossing`. Methods 2–4 test unrelated ideas (cycle decomposition, fixed points); skip them for now.",
    },
    {
      num: 7,
      title: "Count of Smaller Numbers After Self",
      url: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
      source: "LC 315",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Per-index inversion counting — carry the original index through the recursion; charge each R-pull to its remaining-L slots",
    },
  ],
};
