import type { Module } from "../types";

export const prefixSums: Module = {
  id: "prefix-sums",
  num: 4,
  name: "Prefix Sums",
  section: "1",
  track: "both",
  order: 4,
  prereqIds: ["arrays-hashing"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Prefix Sums (Silver)", url: "https://usaco.guide/silver/prefix-sums" },
    { title: "USACO Guide — More Prefix Sums (Silver)", url: "https://usaco.guide/silver/more-prefix-sums" },
    { title: "CPH Book Ch. 9 — Range Queries", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Static Range Sum Queries",
      url: "https://cses.fi/problemset/task/1646",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Pure 1D prefix sum — implement the cold attempt from Step 1 properly",
    },
    {
      num: 2,
      title: "Breed Counting",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=572",
      source: "USACO Silver",
      difficulty: "easy",
      list: "UG ⭐",
      role: "extension",
      teaches: "One prefix array *per breed* — prefix sums generalise to \"counts of anything\", not just sums",
    },
    {
      num: 3,
      title: "Product of Array Except Self",
      url: "https://leetcode.com/problems/product-of-array-except-self/",
      source: "LC 238",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Two-scan span — introduces the forward + backward sweep that returns in modules 8 and 9",
    },
    {
      num: 4,
      title: "Subarray Sum Equals K",
      url: "https://leetcode.com/problems/subarray-sum-equals-k/",
      source: "LC 560",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Complement lookup over prefix sums (count variant) — frequency dict + the load-bearing `freq[0] = 1` init; the most-asked prefix-sum interview question",
    },
    {
      num: 5,
      title: "Contiguous Array",
      url: "https://leetcode.com/problems/contiguous-array/",
      source: "LC 525",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "New sub-pattern: encode `0 → -1`, then \"longest subarray with equal 0s/1s\" becomes \"longest subarray summing to 0\" — earliest-index dict for a length answer, `first[0] = -1` as the base case",
    },
    {
      num: 6,
      title: "Subarray Sums Divisible by K",
      url: "https://leetcode.com/problems/subarray-sums-divisible-by-k/",
      source: "LC 974",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Modular complement — `prefix % k` as the dict key; two prefix sums have equal mods iff the subarray between them is divisible by k. The `% k` swap from LC 560's `- k` is the only change but the reasoning is entirely different",
    },
    {
      num: 7,
      title: "Range Sum Query 2D - Immutable",
      url: "https://leetcode.com/problems/range-sum-query-2d-immutable/",
      source: "LC 304",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "2D prefix sum baseline — O(MN) preprocessing, O(1) per rectangle query via 4-term inclusion-exclusion. The clean introduction before Forest Queries pushes it on larger CSES constraints",
    },
    {
      num: 8,
      title: "Forest Queries",
      url: "https://cses.fi/problemset/task/1652",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "2D prefix sums — first time the 4-term inclusion-exclusion is needed; CSES gives larger test cases than LC 304",
    },
    {
      num: 9,
      title: "Corporate Flight Bookings",
      url: "https://leetcode.com/problems/corporate-flight-bookings/",
      source: "LC 1109",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Difference array — many range updates, single point-query pass at the end; the inverse direction of prefix sums",
    },
    {
      num: 10,
      title: "Running Miles",
      url: "https://codeforces.com/contest/1826/problem/D",
      source: "CF 1826D",
      difficulty: "medium",
      list: "UG ⭐",
      role: "checkpoint",
      teaches: "Before reading: the answer is `max over j of (something[i≤j] + a[j] + something[k≥j])`. What earlier pattern handles the bracketed terms? Two-scan span from problem 3. Algebraic regrouping unmasks the prefix/suffix structure; apply prefix-max from the left and suffix-max from the right, combine at each pivot j.",
    },
  ],
};
