import type { Module } from "../types";

export const twoPointers: Module = {
  id: "two-pointers",
  num: 5,
  name: "Two Pointers",
  section: "1",
  track: "both",
  order: 5,
  prereqIds: ["arrays-hashing", "sorting"],
  resources: [
    { title: "USACO Guide — Two Pointers (Silver)", url: "https://usaco.guide/silver/two-pointers" },
  ],
  problems: [
    {
      num: 1,
      title: "Sum of Two Values",
      url: "https://cses.fi/problemset/task/1640",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "baseline",
      teaches: "Converging two-sum on sorted array — you solved this in module 2 with a dict (complement lookup); now sort + two pointers, then map back to original indices via `(value, index)` tuples",
    },
    {
      num: 2,
      title: "Squares of a Sorted Array",
      url: "https://leetcode.com/problems/squares-of-a-sorted-array/",
      source: "LC 977",
      difficulty: "easy",
      list: "new",
      role: "baseline",
      teaches: "New sub-pattern: magnitude-comparison converging. Sorted input has negatives, so the largest square sits at one end — compare `abs(a[left])` vs `abs(a[right])`, write the winner to `out[write]`, decrement `write`. Element-emitting loop uses `while left <= right`, not `<`",
    },
    {
      num: 3,
      title: "Valid Palindrome",
      url: "https://leetcode.com/problems/valid-palindrome/",
      source: "LC 125",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Converging on a string from both ends — character-skipping edge case (filter non-alphanumeric inline)",
    },
    {
      num: 4,
      title: "Sum of Three Values",
      url: "https://cses.fi/problemset/task/1641",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "extension",
      teaches: "Reduce by fixing one — fix outer index `i`, run converging two-pointer on the suffix. No dedup needed (distinct values) — isolates the skeleton from problem 5's wrinkle",
    },
    {
      num: 5,
      title: "3Sum",
      url: "https://leetcode.com/problems/3sum/",
      source: "LC 15",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same skeleton as problem 4 plus deduplication — skip duplicate outer `a[i]`; advance `left`/`right` past their duplicates after recording a hit",
    },
    {
      num: 6,
      title: "Container With Most Water",
      url: "https://leetcode.com/problems/container-with-most-water/",
      source: "LC 11",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Different objective (max area, not match a target). Now solve the Step 1 cold attempt with the monotonic invariant from Step 2",
    },
    {
      num: 7,
      title: "Trapping Rain Water",
      url: "https://leetcode.com/problems/trapping-rain-water/",
      source: "LC 42",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Converging while maintaining `left_max` and `right_max` in one pass; combines the monotonic invariant with the [two-scan span](00-patterns.md#two-scan-span) from module 4",
    },
  ],
};
