import type { Module } from "../types";

export const twoPointers: Module = {
  id: "two-pointers",
  num: 5,
  name: "Two Pointers",
  section: "1b",
  tier: "core",
  order: 6,
  prereqIds: ["arrays-hashing", "sorting"],
  resources: [
    { title: "USACO Guide — Two Pointers (Silver)", url: "https://usaco.guide/silver/two-pointers" },
    { title: "CPH Book Ch. 8 — Range Queries (covers two-pointer)", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Sum of Two Values",
      url: "https://cses.fi/problemset/task/1640",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "baseline",
      teaches: "Converging two-sum on sorted array — you solved this in module 2 with a dict (complement lookup); now sort + two pointers, then map back to original indices via `(value, index)` tuples",
    },
    {
      num: 2,
      title: "Squares of a Sorted Array",
      url: "https://leetcode.com/problems/squares-of-a-sorted-array/",
      source: "LC 977",
      difficulty: "easy",
      list: "new",
      role: "baseline",
      teaches: "New sub-pattern: magnitude-comparison converging. Sorted input has negatives, so the largest square sits at one end — compare `abs(a[left])` vs `abs(a[right])`, write the winner to `out[write]`, decrement `write`. Element-emitting loop uses `while left <= right`, not `<`",
    },
    {
      num: 3,
      title: "Valid Palindrome",
      url: "https://leetcode.com/problems/valid-palindrome/",
      source: "LC 125",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Converging on a string from both ends — character-skipping edge case (filter non-alphanumeric inline)",
    },
    {
      num: 4,
      title: "Sort Colors",
      url: "https://leetcode.com/problems/sort-colors/",
      source: "LC 75",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "New sub-pattern: **three-way partition** (Dutch National Flag). Same-direction two pointers — `low`/`high` bound the unsorted middle, `mid` scans. On `0`: swap with `low`, advance both; on `1`: advance `mid`; on `2`: swap with `high`, do *not* advance `mid` (the incoming value is unseen). The asymmetric mid-advance is the load-bearing invariant — most canonical partition question at Meta/Google",
    },
    {
      num: 5,
      title: "Sum of Three Values",
      url: "https://cses.fi/problemset/task/1641",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "extension",
      teaches: "Reduce by fixing one — fix outer index `i`, run converging two-pointer on the suffix. No dedup needed (distinct values) — isolates the skeleton from problem 6's wrinkle",
    },
    {
      num: 6,
      title: "3Sum",
      url: "https://leetcode.com/problems/3sum/",
      source: "LC 15",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same skeleton as problem 5 plus deduplication — skip duplicate outer `a[i]`; advance `left`/`right` past their duplicates after recording a hit",
    },
    {
      num: 7,
      title: "Container With Most Water",
      url: "https://leetcode.com/problems/container-with-most-water/",
      source: "LC 11",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Different objective (max area, not match a target). Now solve the Step 1 cold attempt with the monotonic invariant from Step 2",
    },
    {
      num: 8,
      title: "3Sum Closest",
      url: "https://leetcode.com/problems/3sum-closest/",
      source: "LC 16",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Reduce-by-fixing-one + converging with a distance-to-target objective — track the minimum |sum − target| seen, update inside the inner pointer loop. Bridges 3Sum's exact-match converging to LC 42's minimax tracking",
    },
    {
      num: 9,
      title: "Trapping Rain Water",
      url: "https://leetcode.com/problems/trapping-rain-water/",
      source: "LC 42",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: each cell's water depends on the max heights on both sides — what earlier pattern computed those side-maxes? The [two-scan span](00-patterns.md#two-scan-span) from module 4. Fuse the two scans into one converging pass, maintaining `left_max` and `right_max` and advancing the smaller side.",
    },
  ],
};
