import type { Module } from "../types";

export const slidingWindow: Module = {
  id: "sliding-window",
  num: 6,
  name: "Sliding Window",
  section: "1",
  track: "both",
  order: 6,
  prereqIds: ["two-pointers"],
  resources: [
    { title: "USACO Guide — Two Pointers (Silver)", url: "https://usaco.guide/silver/two-pointers" },
  ],
  problems: [
    {
      num: 1,
      title: "Subarray Sums I",
      url: "https://cses.fi/problemset/task/1660",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Variable window on positive integers, exact match — this was your Step 1 problem",
    },
    {
      num: 2,
      title: "Minimum Size Subarray Sum",
      url: "https://leetcode.com/problems/minimum-size-subarray-sum/",
      source: "LC 209",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "The **minimum-window** shape from Step 2 — extend until valid, then shrink while *still* valid; update `best` inside the `while`. Same skeleton the checkpoint extends",
    },
    {
      num: 3,
      title: "Longest Substring Without Repeating Characters",
      url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
      source: "LC 3",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "The **longest-window** shape — extend, then shrink while *invalid*; window state is a set (or count-of-1s dict)",
    },
    {
      num: 4,
      title: "Longest Repeating Character Replacement",
      url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
      source: "LC 424",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same longest-window shape with a frequency dict, plus the stale-`max_freq` trick from Step 2 — load-bearing because a fresh max recompute on every step would be O(26 · n)",
    },
    {
      num: 5,
      title: "Permutation in String",
      url: "https://leetcode.com/problems/permutation-in-string/",
      source: "LC 567",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Fixed window — window size is exactly `len(s1)`, no shrink decision; compare freq dicts in O(26) per slide, or track a \"matches\" counter for O(1)",
    },
    {
      num: 6,
      title: "Diamond Collector",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=643",
      source: "USACO Silver",
      difficulty: "medium",
      list: "UG ⭐",
      role: "extension",
      teaches: "Sort + variable window with `max − min ≤ K` constraint — the problem statement does not say \"sliding window\"; you must recognise it after the sort",
    },
    {
      num: 7,
      title: "Subarrays with K Different Integers",
      url: "https://leetcode.com/problems/subarrays-with-k-different-integers/",
      source: "LC 992",
      difficulty: "hard",
      list: "new",
      role: "combination",
      teaches: "at-most-K reduction — \"exactly K distinct\" isn't monotonic in window size; convert to `atMost(K) − atMost(K−1)`, run two variable-window passes and subtract; the first time the window pattern doubles on itself",
    },
    {
      num: 8,
      title: "Minimum Window Substring",
      url: "https://leetcode.com/problems/minimum-window-substring/",
      source: "LC 76",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Minimum-window (problem 2's shape) + multi-character tracking — the \"missing counter\" trick replaces the freq-dict comparison",
    },
  ],
};
