import type { Module } from "../types";

export const stack: Module = {
  id: "stack",
  num: 7,
  name: "Stack",
  section: "1b",
  track: "both",
  order: 8,
  prereqIds: ["arrays-hashing"],
  resources: [
    { title: "USACO Guide — Stacks (Gold)", url: "https://usaco.guide/gold/stacks" },
    { title: "CP-Algorithms — Stack with minimum", url: "https://cp-algorithms.com/data_structures/stack_queue_modification.html" },
    { title: "CPH Book Ch. 4 — Data Structures", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Valid Parentheses",
      url: "https://leetcode.com/problems/valid-parentheses/",
      source: "LC 20",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Push on open, match-and-pop on close; this was your Step 1 problem",
    },
    {
      num: 2,
      title: "Min Stack",
      url: "https://leetcode.com/problems/min-stack/",
      source: "LC 155",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Augmented data structure — each entry carries `(value, current_min)`; first appearance of the pattern, reused at the checkpoint",
    },
    {
      num: 3,
      title: "Evaluate Reverse Polish Notation",
      url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
      source: "LC 150",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Expression evaluation — operands on stack, operator pops two; LIFO is the natural fit for postfix",
    },
    {
      num: 4,
      title: "Simplify Path",
      url: "https://leetcode.com/problems/simplify-path/",
      source: "LC 71",
      difficulty: "medium",
      list: "⭐",
      role: "extension",
      teaches: "Stack-as-current-state, cleanest form — push real segments, pop on `..`, skip on `.`; the stack at the end *is* the canonical path",
    },
    {
      num: 5,
      title: "Asteroid Collision",
      url: "https://leetcode.com/problems/asteroid-collision/",
      source: "LC 735",
      difficulty: "medium",
      list: "⭐",
      role: "extension",
      teaches: "Same shape as problem 4 but with a *while* loop comparing the new arrival to the top — three-case collision logic (top dies, new dies, both die), reused at the checkpoint",
    },
    {
      num: 6,
      title: "Decode String",
      url: "https://leetcode.com/problems/decode-string/",
      source: "LC 394",
      difficulty: "medium",
      list: "⭐",
      role: "extension",
      teaches: "Nested context — push the current `(string, count)` state on `[`, pop and unwind on `]`; entries are heterogeneous",
    },
    {
      num: 7,
      title: "Remove All Adjacent Duplicates In String II",
      url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/",
      source: "LC 1209",
      difficulty: "medium",
      list: "⭐",
      role: "checkpoint",
      teaches: "Before reading: which earlier problem in the module attached extra bookkeeping to each stack entry, and which one popped on a top-vs-incoming comparison? Problem 2's augmented entries plus problem 5's collision check. Stack of `(char, run_length)` with threshold-driven pop when `run_length == k`.",
    },
  ],
};
