import type { Module } from "../types";

export const monotonicStack: Module = {
  id: "monotonic-stack",
  num: 8,
  name: "Monotonic Stack",
  section: "1",
  track: "both",
  order: 8,
  prereqIds: ["stack", "two-pointers"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Stacks (Gold)", url: "https://usaco.guide/gold/stacks" },
    { title: "USACO Guide — Monotonic Stack (Platinum)", url: "https://usaco.guide/plat/monotonic-stack" },
  ],
  problems: [
    {
      num: 1,
      title: "Nearest Smaller Values",
      url: "https://cses.fi/problemset/task/1645",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "PSE going left-to-right — implement your Step 1 problem with the increasing stack",
    },
    {
      num: 2,
      title: "Daily Temperatures",
      url: "https://leetcode.com/problems/daily-temperatures/",
      source: "LC 739",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "NGE going right — answer assigned at pop time; the mirror direction of problem 1",
    },
    {
      num: 3,
      title: "Mike and Feet",
      url: "https://codeforces.com/contest/547/problem/B",
      source: "CF 547B",
      difficulty: "medium",
      list: "UG ⭐",
      role: "extension",
      teaches: "Span = PSE + NSE — for each height, find the widest subarray where it is the minimum; first use of the two-scan span pattern",
    },
    {
      num: 4,
      title: "Online Stock Span",
      url: "https://leetcode.com/problems/online-stock-span/",
      source: "LC 901",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "New sub-pattern: `(price, span)` pairs with accumulate-on-pop — the stack carries state, popping does work (Step 2 \"carrying state\")",
    },
    {
      num: 5,
      title: "Car Fleet",
      url: "https://leetcode.com/problems/car-fleet/",
      source: "LC 853",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same carrying-state idiom in a lateral framing — sort by position, decreasing stack of arrival times, a slower fleet absorbs faster cars trapped behind it",
    },
    {
      num: 6,
      title: "Largest Rectangle in Histogram",
      url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
      source: "LC 84",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Canonical PSE + NSE with the sentinel-flush trick; computes `height[i] × span[i]` at pop time",
    },
    {
      num: 7,
      title: "Sum of Subarray Minimums",
      url: "https://leetcode.com/problems/sum-of-subarray-minimums/",
      source: "LC 907",
      difficulty: "medium",
      list: "⭐",
      role: "checkpoint",
      teaches: "Contribution counting with asymmetric tie-breaking (`≥` on PSE side, `>` on NSE side)",
    },
  ],
};
