import type { Module } from "../types";

export const monotonicDeque: Module = {
  id: "monotonic-deque",
  num: 9,
  name: "Monotonic Deque",
  section: "1",
  track: "both",
  order: 9,
  prereqIds: ["sliding-window", "monotonic-stack", "prefix-sums"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Sliding Window (Gold)", url: "https://usaco.guide/gold/sliding-window" },
  ],
  problems: [
    {
      num: 1,
      title: "Sliding Window Maximum",
      url: "https://leetcode.com/problems/sliding-window-maximum/",
      source: "LC 239",
      difficulty: "hard",
      list: "NC150",
      role: "baseline",
      teaches: "Fixed-window decreasing deque — your Step 1 problem; the canonical interview application",
    },
    {
      num: 2,
      title: "Max Subarray Sum II",
      url: "https://cses.fi/problemset/task/1644",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "Fixed-window deque over prefix sums — max subarray sum with length in `[a, b]`; reduces to \"max of P[i] over a sliding window of size b−a+1\"",
    },
    {
      num: 3,
      title: "Longest Continuous Subarray With Absolute Diff ≤ Limit",
      url: "https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-leq-limit/",
      source: "LC 1438",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Two deques simultaneously — max-deque and min-deque tracked together; the two-scan span pattern interleaved in one sweep",
    },
    {
      num: 4,
      title: "Jump Game VI",
      url: "https://leetcode.com/problems/jump-game-vi/",
      source: "LC 1696",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "New sub-pattern: **deque over a DP recurrence**. `dp[i] = nums[i] + max(dp[i-k..i-1])`; the deque slides over an array computed as you go — strict read-before-write",
    },
    {
      num: 5,
      title: "Maximum Number of Robots Within Budget",
      url: "https://leetcode.com/problems/maximum-number-of-robots-within-budget/",
      source: "LC 2398",
      difficulty: "hard",
      list: "new",
      role: "combination",
      teaches: "Deque-max combined with a running cost sum inside a variable window from module 6; cost formula `max_charge + window_size × sum_costs` drives the shrink decision",
    },
    {
      num: 6,
      title: "Shortest Subarray with Sum at Least K",
      url: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/",
      source: "LC 862",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Deque over prefix sums when the array contains negatives — module 6's sliding window precondition breaks; module 4's prefix sums are the repair",
    },
  ],
};
