import type { Module } from "../types";

export const monotonicDeque: Module = {
  id: "monotonic-deque",
  num: 12,
  name: "Monotonic Deque",
  section: "1b",
  tier: "core",
  order: 12,
  prereqIds: ["sliding-window", "monotonic-stack", "prefix-sums"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Stacks (Gold)", url: "https://usaco.guide/gold/stacks" },
    { title: "USACO Guide — Sliding Window (Gold)", url: "https://usaco.guide/gold/sliding-window" },
  ],
  problems: [
    {
      num: 1,
      title: "Max Subarray Sum II",
      url: "https://cses.fi/problemset/task/1644",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "baseline",
      teaches: "Fixed-window decreasing deque over prefix sums — your Step 1 problem; max subarray sum with length in `[a, b]` reduces to \"max of P[i] over a sliding window of size b−a+1\"",
    },
    {
      num: 2,
      title: "Longest Continuous Subarray With Absolute Diff ≤ Limit",
      url: "https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-leq-limit/",
      source: "LC 1438",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Two deques simultaneously — max-deque and min-deque tracked together; the two-scan span pattern interleaved in one sweep",
    },
    {
      num: 3,
      title: "Jump Game VI",
      url: "https://leetcode.com/problems/jump-game-vi/",
      source: "LC 1696",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "New sub-pattern: **deque over a DP recurrence**. `dp[i] = nums[i] + max(dp[i-k..i-1])`; the deque slides over an array computed as you go — strict read-before-write",
    },
    {
      num: 4,
      title: "Constrained Subsequence Sum",
      url: "https://leetcode.com/problems/constrained-subsequence-sum/",
      source: "LC 1425",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "Deque over DP recurrence — `dp[i] = nums[i] + max(dp[i-k..i-1], 0)`. Maintain a monotonic decreasing deque of `dp` values within the window; the front gives the maximum in O(1). This is the canonical 'sliding-window optimisation of a 1D DP' pattern",
    },
    {
      num: 5,
      title: "Shortest Subarray with Sum at Least K",
      url: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/",
      source: "LC 862",
      difficulty: "hard",
      list: "new",
      role: "combination",
      teaches: "Deque over prefix sums when the array contains negatives — module 6's sliding window precondition breaks; module 4's prefix sums are the repair",
    },
    {
      num: 6,
      title: "Sliding Window Maximum",
      url: "https://leetcode.com/problems/sliding-window-maximum/",
      source: "LC 239",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: strip away prefix sums, DP recurrences, and negative arrays — what is the deque discipline in its most stripped-down form? Fixed-window decreasing deque on the raw array. The canonical interview application: pop-back while smaller, pop-front when index expires, front is the answer.",
    },
  ],
};
