import type { Module } from "../types";

export const linkedList: Module = {
  id: "linked-list",
  num: 5,
  name: "Linked List",
  section: "1a",
  tier: "core",
  order: 5,
  prereqIds: ["arrays-hashing"],
  resources: [
    { title: "Wikipedia — Floyd's cycle detection, \"Tortoise and hare\" section", url: "https://en.wikipedia.org/wiki/Cycle_detection#Floyd's_tortoise_and_hare" },
    { title: "USACO Guide — Linked Lists", url: "https://usaco.guide/general/linked-lists" },
    { title: "Python docs — collections.deque", url: "https://docs.python.org/3/library/collections.html#collections.deque" },
  ],
  problems: [
    {
      num: 1,
      title: "Reverse Linked List",
      url: "https://leetcode.com/problems/reverse-linked-list/",
      source: "LC 206",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Pointer manipulation — `prev / curr / nxt` discipline; reused in problems 7 and 11",
    },
    {
      num: 2,
      title: "Merge Two Sorted Lists",
      url: "https://leetcode.com/problems/merge-two-sorted-lists/",
      source: "LC 21",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Dummy head + merge — the subroutine reused in problem 6 and at the checkpoint",
    },
    {
      num: 3,
      title: "Add Two Numbers",
      url: "https://leetcode.com/problems/add-two-numbers/",
      source: "LC 2",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Dummy head from problem 2 + a `carry` variable that survives across nodes — first appearance of two-pointer traversal with arithmetic state; remember the final carry node when one list is longer or both end with a carry",
    },
    {
      num: 4,
      title: "Linked List Cycle",
      url: "https://leetcode.com/problems/linked-list-cycle/",
      source: "LC 141",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Fast/slow pointer — detect cycle in O(1) space; phase 1 of Floyd's",
    },
    {
      num: 5,
      title: "Linked List Cycle II",
      url: "https://leetcode.com/problems/linked-list-cycle-ii/",
      source: "LC 142",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Floyd's *full* algorithm — phase 2 reset trick that Step 2 derives; return the cycle-start node, not just a boolean",
    },
    {
      num: 6,
      title: "Remove Nth Node From End of List",
      url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
      source: "LC 19",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Two pointers with a *fixed gap* — same fast/slow chassis as problem 4 with the gap controlling distance-from-end; your Step 1 problem",
    },
    {
      num: 7,
      title: "Reorder List",
      url: "https://leetcode.com/problems/reorder-list/",
      source: "LC 143",
      difficulty: "medium",
      list: "NC150",
      role: "combination",
      teaches: "Find middle (fast/slow, no gap) + reverse second half (problem 1) + merge alternating (problem 2) — three patterns in one pass",
    },
    {
      num: 8,
      title: "Copy List With Random Pointer",
      url: "https://leetcode.com/problems/copy-list-with-random-pointer/",
      source: "LC 138",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Hash map `{old → new}` for cross-referenced duplication — single-pass insufficient because `.random` can point forward",
    },
    {
      num: 9,
      title: "Find The Duplicate Number",
      url: "https://leetcode.com/problems/find-the-duplicate-number/",
      source: "LC 287",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Floyd's reused on an *implicit* functional graph (`i → a[i]`) — the \"list\" exists only conceptually; cycle start = duplicate value",
    },
    {
      num: 10,
      title: "LRU Cache",
      url: "https://leetcode.com/problems/lru-cache/",
      source: "LC 146",
      difficulty: "medium",
      list: "NC150",
      role: "combination",
      teaches: "Doubly linked list + dict — the [augmented data structure](00-patterns.md#augmented-data-structure) pattern reused from module 7's Min Stack; implement the DLL explicitly (not `OrderedDict`) for interview",
    },
    {
      num: 11,
      title: "Reverse Nodes in k-Group",
      url: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
      source: "LC 25",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Segmented reversal — count k ahead to confirm a full group exists, reverse that segment using problem 1's `prev/curr/nxt` discipline, then splice the reversed head/tail back into the surrounding list. Tail-pointer bookkeeping across segments is the bug surface; a Google/Meta favourite that pushes pointer manipulation to its limit",
    },
    {
      num: 12,
      title: "Merge K Sorted Lists",
      url: "https://leetcode.com/problems/merge-k-sorted-lists/",
      source: "LC 23",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: problem 2 merged two sorted lists in O(n+m). What auxiliary structure generalises that to k lists in O(N log k)? A min-heap keyed on current-front values. Stash `(val, index, node)` tuples (index breaks ties since `ListNode` isn't comparable); the merge subroutine from problem 2 is the inner step.",
    },
  ],
};
