import type { Module } from "../types";

export const binarySearch: Module = {
  id: "binary-search",
  num: 11,
  name: "Binary Search",
  section: "1",
  track: "both",
  order: 11,
  prereqIds: ["arrays-hashing", "sorting", "two-pointers"],
  resources: [
    { title: "USACO Guide — Binary Search on Sorted Array (Silver)", url: "https://usaco.guide/silver/binary-search-sorted-array" },
    { title: "USACO Guide — Binary Search (Silver)", url: "https://usaco.guide/silver/binary-search" },
  ],
  problems: [
    {
      num: 1,
      title: "Binary Search",
      url: "https://leetcode.com/problems/binary-search/",
      source: "LC 704",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Implement Template A from scratch — prove termination via the loop invariant",
    },
    {
      num: 2,
      title: "Counting Haybales",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=666",
      source: "USACO Silver",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "Range count via `bisect_right(end) - bisect_left(start)` — the canonical bisect application beyond raw lookup",
    },
    {
      num: 3,
      title: "Search a 2D Matrix",
      url: "https://leetcode.com/problems/search-a-2d-matrix/",
      source: "LC 74",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Flatten 2D index `k` to `(k // n, k % n)` — same Template A on the virtual flat array",
    },
    {
      num: 4,
      title: "Find Minimum in Rotated Sorted Array",
      url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
      source: "LC 153",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Your Step 1 problem — Template B with the `a[mid] <= a[hi]` comparison",
    },
    {
      num: 5,
      title: "Search in Rotated Sorted Array",
      url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
      source: "LC 33",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same rotated structure as problem 4, now searching for a target — one extra range check per branch",
    },
    {
      num: 6,
      title: "Time Based Key-Value Store",
      url: "https://leetcode.com/problems/time-based-key-value-store/",
      source: "LC 981",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "`bisect_right` embedded in a data structure design — binary search on a list of timestamps",
    },
    {
      num: 7,
      title: "Single Element in a Sorted Array",
      url: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
      source: "LC 540",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "New sub-pattern: a non-trivial monotonic predicate — index parity tells you which half holds the unique element. Force `mid` even with `mid -= mid & 1`, then test `a[mid] == a[mid+1]`",
    },
    {
      num: 8,
      title: "Find Peak Element",
      url: "https://leetcode.com/problems/find-peak-element/",
      source: "LC 162",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Neighbor-comparison predicate — compare `a[mid]` vs `a[mid+1]` to determine which side ascends toward a peak; no target value, the monotonic structure is local slope",
    },
    {
      num: 9,
      title: "Median of Two Sorted Arrays",
      url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
      source: "LC 4",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Binary search on the partition point of the smaller array; the partition of the larger array is then determined",
    },
  ],
};
