import type { Module } from "../types";

export const bsAnswer: Module = {
  id: "bs-answer",
  num: 12,
  name: "Binary Search on Answer",
  label: "Binary Search\non Answer",
  section: "1c",
  tier: "core",
  order: 13,
  prereqIds: ["binary-search"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Binary Search (Silver)", url: "https://usaco.guide/silver/binary-search" },
  ],
  problems: [
    {
      num: 1,
      title: "Array Division",
      url: "https://cses.fi/problemset/task/1085",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "baseline",
      teaches: "Greedy-contiguous-partition feasibility — your Step 1 problem; `parts ≤ k` if you fill each subarray up to X",
    },
    {
      num: 2,
      title: "Koko Eating Bananas",
      url: "https://leetcode.com/problems/koko-eating-bananas/",
      source: "LC 875",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Independent-per-element feasibility — `sum(ceil(p / k)) ≤ h`; same outer template, different feasibility shape",
    },
    {
      num: 3,
      title: "Minimum Number of Days to Make m Bouquets",
      url: "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/",
      source: "LC 1482",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "New feasibility shape: scan for **k adjacent bloomed flowers** and count m bouquets — not a sum, a structural streak",
    },
    {
      num: 4,
      title: "The Meeting Place Cannot Be Changed",
      url: "https://codeforces.com/contest/782/problem/B",
      source: "CF 782B",
      difficulty: "medium",
      list: "UG ⭐",
      role: "extension",
      teaches: "Interval-intersection feasibility — at time T each friend's reachable interval is `[pos_i − speed_i·T, pos_i + speed_i·T]`; T is feasible iff the intersection is non-empty",
    },
    {
      num: 5,
      title: "Magnetic Force Between Two Balls",
      url: "https://leetcode.com/problems/magnetic-force-between-two-balls/",
      source: "LC 1552",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Maximise-minimum** direction — sort positions, greedily place balls at the first viable spot, check count ≥ m; the canonical flipped-template problem",
    },
    {
      num: 6,
      title: "Maximum Median",
      url: "https://codeforces.com/contest/1201/problem/C",
      source: "CF 1201C",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "Sort + cost-over-upper-half feasibility — the USACO Guide's featured example; cost to raise the median to x is `Σ_{i ≥ n/2} max(0, x − a[i])`",
    },
    {
      num: 7,
      title: "Capacity To Ship Packages Within D Days",
      url: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
      source: "LC 1011",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Canonical partition-feasibility on the answer — BS on capacity `c`; the feasibility predicate is a single greedy pass that counts how many days are needed to ship all packages with capacity `c`. The most-asked BS-on-answer pattern in FAANG, equivalent to Array Division (problem 1) but on the LC framing. Minimize-the-maximum direction.",
    },
    {
      num: 8,
      title: "Kth Smallest Element in a Sorted Matrix",
      url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
      source: "LC 378",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "New feasibility shape: BS on the answer value x, feasibility = count cells ≤ x ≥ k (row-wise linear scan). Flips the question — instead of 'is X achievable?' ask 'how many items satisfy ≤ x?' and find the smallest x where that count reaches k",
    },
    {
      num: 9,
      title: "Find K-th Smallest Pair Distance",
      url: "https://leetcode.com/problems/find-k-th-smallest-pair-distance/",
      source: "LC 719",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "Count-feasibility with sliding window — BS on the answer distance d; feasibility = 'count pairs with distance ≤ d ≥ k'. Sort the array, then count pairs using a two-pointer sweep in O(n). Harder than LC 378: feasibility itself requires a non-trivial algorithm",
    },
    {
      num: 10,
      title: "Angry Cows (Gold)",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=597",
      source: "USACO Gold",
      difficulty: "hard",
      list: "UG ⭐",
      role: "checkpoint",
      teaches: "Before reading: the BS-on-answer skeleton is fixed — what does the feasibility predicate cost when problem 9 forced you to use a sweep inside it? O(n log n). Chain-reaction simulation over sorted haybales plus a converging two-pointer (module 5) over launch positions; total runtime O(n log² n).",
    },
  ],
};
