import type { Module } from "../types";

export const backtracking: Module = {
  id: "backtracking",
  num: 13,
  name: "Recursion & Backtracking",
  label: "Recursion &\nBacktracking",
  section: "1",
  track: "both",
  order: 13,
  prereqIds: ["foundations"],
  resources: [
    { title: "USACO Guide — Complete Search with Recursion (Bronze)", url: "https://usaco.guide/bronze/complete-rec" },
  ],
  problems: [
    {
      num: 1,
      title: "Apple Division",
      url: "https://cses.fi/problemset/task/1623",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Subset recursion with a running aggregate — your Step 1 problem",
    },
    {
      num: 2,
      title: "Subsets",
      url: "https://leetcode.com/problems/subsets/",
      source: "LC 78",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same subset recursion, generate-all framing — interview canon",
    },
    {
      num: 3,
      title: "Permutations",
      url: "https://leetcode.com/problems/permutations/",
      source: "LC 46",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "New sub-pattern: swap-based permutations",
    },
    {
      num: 4,
      title: "Creating Strings I",
      url: "https://cses.fi/problemset/task/1622",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "Permutations with duplicates — introduces the `i > start` skip rule",
    },
    {
      num: 5,
      title: "Combination Sum",
      url: "https://leetcode.com/problems/combination-sum/",
      source: "LC 39",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Accumulate-with-reuse plus sorted+break pruning",
    },
    {
      num: 6,
      title: "Generate Parentheses",
      url: "https://leetcode.com/problems/generate-parentheses/",
      source: "LC 22",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Count-constrained recursion — `open < n` to add `(`, `close < open` to add `)`",
    },
    {
      num: 7,
      title: "Combination Sum II",
      url: "https://leetcode.com/problems/combination-sum-ii/",
      source: "LC 40",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Skip rule from problem 4 + no-reuse (pass `i+1`)",
    },
    {
      num: 8,
      title: "Word Search",
      url: "https://leetcode.com/problems/word-search/",
      source: "LC 79",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Grid backtracking — mark with `#`, recurse 4 directions, restore on return",
    },
    {
      num: 9,
      title: "Livestock Lineup",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=965",
      source: "USACO Bronze",
      difficulty: "medium",
      list: "UG ⭐",
      role: "extension",
      teaches: "Permutation backtracking in a problem statement that doesn't name the pattern — must identify it",
    },
    {
      num: 10,
      title: "Partition to K Equal Sum Subsets",
      url: "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/",
      source: "LC 698",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Bucket-filling backtracking — place each item into one of k buckets that must each sum to `total/k`. Prune by sorting descending (place hardest items first), skipping symmetric empty-bucket states, and bailing when a bucket overflows. Distinct mechanic from constraint-placement (N-Queens) and target-accumulation (Combination Sum)",
    },
    {
      num: 11,
      title: "N-Queens",
      url: "https://leetcode.com/problems/n-queens/",
      source: "LC 51",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Place queens row by row; prune on `cols`, `r − c`, `r + c` simultaneously",
    },
  ],
};
