import type { Module } from "../types";

export const backtracking: Module = {
  id: "backtracking",
  num: 4,
  name: "Recursion & Backtracking",
  label: "Recursion &\nBacktracking",
  section: "1d",
  tier: "core",
  order: 4,
  prereqIds: ["foundations"],
  resources: [
    { title: "USACO Guide — Complete Search with Recursion (Bronze)", url: "https://usaco.guide/bronze/complete-rec" },
    { title: "CP-Algorithms — Generating subsets / combinations", url: "https://cp-algorithms.com/combinatorics/generating_combinations.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Subsets",
      url: "https://leetcode.com/problems/subsets/",
      source: "LC 78",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Canonical subset enumeration via the include/skip branching template. Your Step 1 problem.",
    },
    {
      num: 2,
      title: "Permutations",
      url: "https://leetcode.com/problems/permutations/",
      source: "LC 46",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "New sub-pattern: swap-based permutations",
    },
    {
      num: 3,
      title: "Letter Combinations of a Phone Number",
      url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
      source: "LC 17",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Index-based recursion — at depth `i`, iterate over the letters mapped to digits[i] and recurse on i+1. Build a partial string, backtrack by removing the last character. The canonical recursive-enumeration shape distinct from combinations/permutations",
    },
    {
      num: 4,
      title: "Permutations II",
      url: "https://leetcode.com/problems/permutations-ii/",
      source: "LC 47",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Permutations with duplicates — sort first, then skip `nums[i] == nums[i-1] && !used[i-1]` at each level. The dedup happens on the *unused* mirror, not the in-progress permutation. Same skip-rule mechanic as Combination Sum II but applied to permutations.",
    },
    {
      num: 5,
      title: "Combination Sum",
      url: "https://leetcode.com/problems/combination-sum/",
      source: "LC 39",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Accumulate-with-reuse plus sorted+break pruning",
    },
    {
      num: 6,
      title: "Generate Parentheses",
      url: "https://leetcode.com/problems/generate-parentheses/",
      source: "LC 22",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Count-constrained recursion — `open < n` to add `(`, `close < open` to add `)`",
    },
    {
      num: 7,
      title: "Combination Sum II",
      url: "https://leetcode.com/problems/combination-sum-ii/",
      source: "LC 40",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Skip rule from problem 4 + no-reuse (pass `i+1`)",
    },
    {
      num: 8,
      title: "Palindrome Partitioning",
      url: "https://leetcode.com/problems/palindrome-partitioning/",
      source: "LC 131",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Backtracking with state validation — at each step, try every prefix that's a palindrome and recurse on the suffix. Combines partition enumeration with a per-cut check; the validity test gates the recursion",
    },
    {
      num: 9,
      title: "Word Search",
      url: "https://leetcode.com/problems/word-search/",
      source: "LC 79",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Grid backtracking — mark with `#`, recurse 4 directions, restore on return",
    },
    {
      num: 10,
      title: "Expression Add Operators",
      url: "https://leetcode.com/problems/expression-add-operators/",
      source: "LC 282",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Expression-tree backtracking with carry-tracking — at each digit-split, try `+`, `-`, `*`. Multiplication requires undoing the previous operator's contribution, so each recursive frame carries `prev_operand` separately from `current_total`. Tests careful state passing under operator precedence.",
    },
    {
      num: 11,
      title: "Partition to K Equal Sum Subsets",
      url: "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/",
      source: "LC 698",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Bucket-filling backtracking — place each item into one of k buckets that must each sum to `total/k`. Prune by sorting descending (place hardest items first), skipping symmetric empty-bucket states, and bailing when a bucket overflows. Distinct mechanic from constraint-placement (N-Queens) and target-accumulation (Combination Sum)",
    },
    {
      num: 12,
      title: "N-Queens",
      url: "https://leetcode.com/problems/n-queens/",
      source: "LC 51",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: which earlier problem pruned by tracking a set of \"already-used\" indices, and how do you extend that idea when three orthogonal attacks (column, two diagonals) must all be free? Place queens row by row; maintain three sets indexed by `col`, `r − c`, and `r + c`, prune on all three simultaneously before recursing.",
    },
  ],
};
