import type { Module } from "../types";

export const trees: Module = {
  id: "trees",
  num: 14,
  name: "Trees",
  section: "1",
  track: "both",
  order: 14,
  prereqIds: ["backtracking", "stack"],
  resources: [
    { title: "USACO Guide — Introduction to Trees (Silver)", url: "https://usaco.guide/silver/intro-tree" },
  ],
  problems: [
    {
      num: 1,
      title: "Subordinates",
      url: "https://cses.fi/problemset/task/1674",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "General tree DFS — adjacency list, parent guard, return subtree size",
    },
    {
      num: 2,
      title: "Maximum Depth of Binary Tree",
      url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
      source: "LC 104",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Height aggregation — the foundation for all post-order problems",
    },
    {
      num: 3,
      title: "Diameter of Binary Tree",
      url: "https://leetcode.com/problems/diameter-of-binary-tree/",
      source: "LC 543",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Your Step 1 problem — return height upward, update global diameter as side effect",
    },
    {
      num: 4,
      title: "Binary Tree Level Order Traversal",
      url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
      source: "LC 102",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "BFS with the level-size snapshot trick",
    },
    {
      num: 5,
      title: "Count Good Nodes in Binary Tree",
      url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
      source: "LC 1448",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "State down — pass `max_so_far` to each recursive call",
    },
    {
      num: 6,
      title: "Validate Binary Search Tree",
      url: "https://leetcode.com/problems/validate-binary-search-tree/",
      source: "LC 98",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "BST range validation — pass `(lo, hi)` down, tighten at each step",
    },
    {
      num: 7,
      title: "Lowest Common Ancestor of BST",
      url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
      source: "LC 235",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "BST navigation — first node with `min(p, q) ≤ node ≤ max(p, q)`",
    },
    {
      num: 8,
      title: "Kth Smallest Element in a BST",
      url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
      source: "LC 230",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "In-order = sorted; stop at the k-th yield; iterative in-order short-circuits, recursive does not",
    },
    {
      num: 9,
      title: "Tree Diameter",
      url: "https://cses.fi/problemset/task/1131",
      source: "CSES",
      difficulty: "medium",
      list: "UG ⭐",
      role: "extension",
      teaches: "Unrooted general tree — two-pass BFS algorithm; first farthest is one endpoint, second farthest from it is the other",
    },
    {
      num: 10,
      title: "Binary Tree Maximum Path Sum",
      url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
      source: "LC 124",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Same post-order pattern as LC 543, but the distinction between *returned value* and *globally recorded value* is the entire problem",
    },
  ],
};
