import type { Module } from "../types";

// Stealth prereqs (not enforced by the DAG):
// - Functional recursion with return-value composition. Backtracking
//   teaches mutate-and-undo recursion; trees need return-and-combine
//   (aggregate up the call stack, parent merges child results).
//   Novices write `void` helpers with side-effects and stall on
//   "return the diameter." If shaky on this, revisit recursion
//   before problem 3.

export const trees: Module = {
  id: "trees",
  num: 13,
  name: "Trees",
  section: "1d",
  tier: "core",
  order: 13,
  prereqIds: ["stack", "binary-search"],
  resources: [
    { title: "USACO Guide — Introduction to Trees (Silver)", url: "https://usaco.guide/silver/intro-tree" },
    { title: "CPH Book Ch. 14 — Tree Algorithms", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Maximum Depth of Binary Tree",
      url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
      source: "LC 104",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Your Step 1 problem — post-order height aggregation: `depth(node) = 1 + max(depth(left), depth(right))`. The return-and-combine skeleton every later tree problem reuses.",
    },
    {
      num: 2,
      title: "Invert Binary Tree",
      url: "https://leetcode.com/problems/invert-binary-tree/",
      source: "LC 226",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Structural mutation via recursion — swap left/right at every node, recurse into both subtrees. The canonical Google warmup; teaches that recursion can transform the tree in place, not just compute over it.",
    },
    {
      num: 3,
      title: "Diameter of Binary Tree",
      url: "https://leetcode.com/problems/diameter-of-binary-tree/",
      source: "LC 543",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "The return-up vs record-globally split — return height upward, update a global diameter as a side effect. The skeleton that LC 124 (the module checkpoint) reuses.",
    },
    {
      num: 4,
      title: "Balanced Binary Tree",
      url: "https://leetcode.com/problems/balanced-binary-tree/",
      source: "LC 110",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Post-order with early-termination signal — return `-1` to flag imbalance instead of recomputing height; avoids the O(n²) naive approach",
    },
    {
      num: 5,
      title: "Binary Tree Level Order Traversal",
      url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
      source: "LC 102",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "BFS with the level-size snapshot trick — the canonical level-by-level template (zigzag, right view, min depth, vertical order all reuse this scaffold)",
    },
    {
      num: 6,
      title: "Binary Tree Right Side View",
      url: "https://leetcode.com/problems/binary-tree-right-side-view/",
      source: "LC 199",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "BFS level-order variant — emit the last node at each depth level. Two flavors: (1) standard BFS with `level[-1]` per level, or (2) DFS preorder visiting right-first with a depth-indexed result. The 'rightmost-visible' framing extends LC 102 with a directional projection.",
    },
    {
      num: 7,
      title: "Count Good Nodes in Binary Tree",
      url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
      source: "LC 1448",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "State down — pass `max_so_far` to each recursive call. Complement to the return-up patterns above; root-to-node context flows top-down while the count aggregates bottom-up.",
    },
    {
      num: 8,
      title: "Validate Binary Search Tree",
      url: "https://leetcode.com/problems/validate-binary-search-tree/",
      source: "LC 98",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "BST range validation — pass `(lo, hi)` down, tighten at each step. Naive per-node `left.val < node.val < right.val` fails on grandchildren; the range invariant is the canonical fix.",
    },
    {
      num: 9,
      title: "Lowest Common Ancestor of BST",
      url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
      source: "LC 235",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "BST navigation — first node with `min(p, q) ≤ node ≤ max(p, q)`. Iterative O(h) walk; the BST property lets you decide direction without recursing into both subtrees.",
    },
    {
      num: 10,
      title: "Lowest Common Ancestor of a Binary Tree",
      url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
      source: "LC 236",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "BST property is gone — recurse on both subtrees; if `p` and `q` are found in different subtrees the current node IS the LCA, else recurse into whichever side returned non-null. The return-as-found-marker trick is what makes this elegant. Heavy Meta frequency.",
    },
    {
      num: 11,
      title: "Kth Smallest Element in a BST",
      url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
      source: "LC 230",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "In-order = sorted; stop at the k-th yield. Iterative in-order with an explicit stack short-circuits (push-left-chain, pop and visit, descend right); recursive does not. The iterative-stack pattern itself is the deliverable — BST iterators reuse it verbatim.",
    },
    {
      num: 12,
      title: "Construct Binary Tree from Preorder and Inorder Traversal",
      url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
      source: "LC 105",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Tree reconstruction — preorder root splits inorder into left/right children; hash-map the inorder positions for O(1) lookup at each recursive split",
    },
    {
      num: 13,
      title: "Serialize and Deserialize Binary Tree",
      url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
      source: "LC 297",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Preorder traversal with null sentinels — serialize by recording node values and 'null' markers in preorder; deserialize by consuming the same sequence with a pointer or queue. Teaches bidirectional tree ↔ string encoding.",
    },
    {
      num: 14,
      title: "Binary Tree Maximum Path Sum",
      url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
      source: "LC 124",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: LC 543 (Diameter) shares the recursion skeleton — what one structural distinction defines this problem? The split between the value *returned* upward (best one-armed extension, clamped at 0) and the value *recorded globally* (best bent path with both arms). Post-order; the global max captures bent paths that cannot propagate.",
    },
  ],
};
