import type { Module } from "../types";

// Stealth prereqs (not enforced by the DAG):
// - Functional recursion with return-value composition. Backtracking
//   teaches mutate-and-undo recursion; trees need return-and-combine
//   (aggregate up the call stack, parent merges child results).
//   Novices write `void` helpers with side-effects and stall on
//   "return the diameter." If shaky on this, revisit recursion
//   before problem 3.

export const trees: Module = {
  id: "trees",
  num: 14,
  name: "Trees",
  section: "1d",
  track: "both",
  order: 15,
  prereqIds: ["backtracking", "stack"],
  resources: [
    { title: "USACO Guide — Introduction to Trees (Silver)", url: "https://usaco.guide/silver/intro-tree" },
    { title: "CPH Book Ch. 14 — Tree Algorithms", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Subordinates",
      url: "https://cses.fi/problemset/task/1674",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "General tree DFS — adjacency list, parent guard, return subtree size",
    },
    {
      num: 2,
      title: "Maximum Depth of Binary Tree",
      url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
      source: "LC 104",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Height aggregation — the foundation for all post-order problems",
    },
    {
      num: 3,
      title: "Diameter of Binary Tree",
      url: "https://leetcode.com/problems/diameter-of-binary-tree/",
      source: "LC 543",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Your Step 1 problem — return height upward, update global diameter as side effect",
    },
    {
      num: 4,
      title: "Balanced Binary Tree",
      url: "https://leetcode.com/problems/balanced-binary-tree/",
      source: "LC 110",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Post-order with early-termination signal — return `-1` to flag imbalance instead of recomputing height; avoids the O(n²) naive approach",
    },
    {
      num: 5,
      title: "Binary Tree Level Order Traversal",
      url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
      source: "LC 102",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "BFS with the level-size snapshot trick",
    },
    {
      num: 6,
      title: "Count Good Nodes in Binary Tree",
      url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
      source: "LC 1448",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "State down — pass `max_so_far` to each recursive call",
    },
    {
      num: 7,
      title: "Validate Binary Search Tree",
      url: "https://leetcode.com/problems/validate-binary-search-tree/",
      source: "LC 98",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "BST range validation — pass `(lo, hi)` down, tighten at each step",
    },
    {
      num: 8,
      title: "Lowest Common Ancestor of BST",
      url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
      source: "LC 235",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "BST navigation — first node with `min(p, q) ≤ node ≤ max(p, q)`",
    },
    {
      num: 9,
      title: "Lowest Common Ancestor of a Binary Tree",
      url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
      source: "LC 236",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "BST property is gone — recurse on both subtrees; if `p` and `q` are found in different subtrees the current node IS the LCA, else recurse into whichever side returned non-null. The return-as-found-marker trick is what makes this elegant",
    },
    {
      num: 10,
      title: "Kth Smallest Element in a BST",
      url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
      source: "LC 230",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "In-order = sorted; stop at the k-th yield; iterative in-order short-circuits, recursive does not",
    },
    {
      num: 11,
      title: "Construct Binary Tree from Preorder and Inorder Traversal",
      url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
      source: "LC 105",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Tree reconstruction — preorder root splits inorder into left/right children; hash-map the inorder positions for O(1) lookup at each recursive split",
    },
    {
      num: 12,
      title: "Tree Diameter",
      url: "https://cses.fi/problemset/task/1131",
      source: "CSES",
      difficulty: "medium",
      list: "UG ⭐",
      role: "extension",
      teaches: "Unrooted general tree — two-pass BFS algorithm; first farthest is one endpoint, second farthest from it is the other",
    },
    {
      num: 13,
      title: "Serialize and Deserialize Binary Tree",
      url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
      source: "LC 297",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Preorder traversal with null sentinels — serialize by recording node values and 'null' markers in preorder; deserialize by consuming the same sequence with a pointer or queue. Teaches bidirectional tree ↔ string encoding",
    },
    {
      num: 14,
      title: "Binary Tree Maximum Path Sum",
      url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
      source: "LC 124",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: LC 543 (Diameter) shares the recursion skeleton — what one structural distinction defines this problem? The split between the value *returned* upward (best one-armed extension) and the value *recorded globally* (best bent path with both arms). Post-order; the global max captures bent paths that cannot propagate.",
    },
  ],
};
