import type { Module } from "../types";

export const tries: Module = {
  id: "tries",
  num: 15,
  name: "Tries",
  section: "1",
  track: "both",
  order: 15,
  prereqIds: ["trees"],
  resources: [
    { title: "USACO Guide — String Searching / Tries (Gold)", url: "https://usaco.guide/gold/string-search" },
    { title: "LeetCode editorial for LC 208 — Implement Trie", url: "https://leetcode.com/problems/implement-trie-prefix-tree/editorial/" },
    { title: "CP-Algorithms — String Algorithms", url: "https://cp-algorithms.com/string/string-hashing.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Implement Trie (Prefix Tree)",
      url: "https://leetcode.com/problems/implement-trie-prefix-tree/",
      source: "LC 208",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "The three core operations — your Step 1 problem",
    },
    {
      num: 2,
      title: "Design Add and Search Words Data Structure",
      url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
      source: "LC 211",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Wildcard `'.'` matching via DFS on the trie",
    },
    {
      num: 3,
      title: "Search Suggestions System",
      url: "https://leetcode.com/problems/search-suggestions-system/",
      source: "LC 1268",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Autocomplete — at each prefix, collect up to 3 lexicographically smallest completions",
    },
    {
      num: 4,
      title: "Replace Words",
      url: "https://leetcode.com/problems/replace-words/",
      source: "LC 648",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Early-stop prefix walk — consume each sentence word character by character through the trie, terminate the moment a complete root is reached; the first-match greedy mechanic not present in problems 1-3",
    },
    {
      num: 5,
      title: "Maximum XOR of Two Numbers in an Array",
      url: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
      source: "LC 421",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Binary (XOR) trie — different alphabet (bits), different objective (maximise XOR by greedily picking opposite bits)",
    },
    {
      num: 6,
      title: "Word Search II",
      url: "https://leetcode.com/problems/word-search-ii/",
      source: "LC 212",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: naive is DFS per word against the grid. What structure folds all words into a single grid traversal? Trie of target words. One DFS from each cell, advancing the trie pointer in lockstep with grid moves; prune at missing children, snip leaves after collection, store the full word at each terminal.",
    },
  ],
};
