import type { Module } from "../types";

export const tries: Module = {
  id: "tries",
  num: 15,
  name: "Tries",
  section: "1d",
  tier: "core",
  order: 16,
  prereqIds: ["trees"],
  resources: [
    { title: "USACO Guide — String Searching / Tries (Gold)", url: "https://usaco.guide/gold/string-search" },
    { title: "LeetCode editorial for LC 208 — Implement Trie", url: "https://leetcode.com/problems/implement-trie-prefix-tree/editorial/" },
    { title: "CP-Algorithms — String Algorithms", url: "https://cp-algorithms.com/string/string-hashing.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Implement Trie (Prefix Tree)",
      url: "https://leetcode.com/problems/implement-trie-prefix-tree/",
      source: "LC 208",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Your Step 1 problem — the three core operations (`insert`, `search`, `startsWith`) over a 26-ary children map plus an `isEnd` flag. Establishes the node shape and walk-the-chars-down pattern every later problem reuses.",
    },
    {
      num: 2,
      title: "Design Add and Search Words Data Structure",
      url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
      source: "LC 211",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Wildcard `'.'` matching via DFS on the trie — on a literal char descend the one matching child; on `'.'` fan out into every child. First problem where the trie walk branches.",
    },
    {
      num: 3,
      title: "Search Suggestions System",
      url: "https://leetcode.com/problems/search-suggestions-system/",
      source: "LC 1268",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Autocomplete — at each prefix, collect up to 3 lexicographically smallest completions. Heavy Amazon frequency. Two-pointer/binary-search alternative exists but the trie + DFS-with-early-stop solution is the one interviewers expect once the module is named.",
    },
    {
      num: 4,
      title: "Replace Words",
      url: "https://leetcode.com/problems/replace-words/",
      source: "LC 648",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Early-stop prefix walk — consume each sentence word character by character through the trie, terminate the moment a complete root is reached; the first-match greedy mechanic not present in problems 1-3",
    },
    {
      num: 5,
      title: "Maximum XOR of Two Numbers in an Array",
      url: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
      source: "LC 421",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Binary (XOR) trie — different alphabet (bits), different objective (maximise XOR by greedily picking opposite bits) Note: NC150 categorizes this under Bit Manipulation.",
    },
    {
      num: 6,
      title: "Longest Word in Dictionary",
      url: "https://leetcode.com/problems/longest-word-in-dictionary/",
      source: "LC 720",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Build-up validation walk — insert all words into the trie marking `isEnd`; then for the longest valid word, traverse the trie picking only children with `isEnd == true` at every step (all prefixes must be valid words). DFS the trie collecting candidates; lexicographic tie-break via sorted iteration.",
    },
    {
      num: 7,
      title: "Word Search II",
      url: "https://leetcode.com/problems/word-search-ii/",
      source: "LC 212",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: naive is DFS per word against the grid. What structure folds all words into a single grid traversal? Trie of target words. One DFS from each cell, advancing the trie pointer in lockstep with grid moves; prune at missing children, snip leaves after collection, store the full word at each terminal.",
    },
  ],
};
