import type { Module } from "../types";

export const heap: Module = {
  id: "heap",
  num: 16,
  name: "Heap / Priority Queue",
  section: "1",
  track: "both",
  order: 16,
  prereqIds: ["trees", "linked-list"],
  resources: [
    { title: "USACO Guide — Priority Queues (Silver)", url: "https://usaco.guide/silver/priority-queues" },
  ],
  problems: [
    {
      num: 1,
      title: "Room Allocation",
      url: "https://cses.fi/problemset/task/1164",
      source: "CSES",
      difficulty: "medium",
      list: "UG ⭐",
      role: "baseline",
      teaches: "Sort by arrival + min-heap of departures — your Step 1 problem",
    },
    {
      num: 2,
      title: "Kth Largest Element In a Stream",
      url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
      source: "LC 703",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Min-heap of size k pattern — top is the k-th largest",
    },
    {
      num: 3,
      title: "Last Stone Weight",
      url: "https://leetcode.com/problems/last-stone-weight/",
      source: "LC 1046",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Max-heap simulation — negate on push and pop",
    },
    {
      num: 4,
      title: "K Closest Points to Origin",
      url: "https://leetcode.com/problems/k-closest-points-to-origin/",
      source: "LC 973",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Heap-of-size-k applied to distances — max-heap so we pop when the new point is closer",
    },
    {
      num: 5,
      title: "Merge K Sorted Lists",
      url: "https://leetcode.com/problems/merge-k-sorted-lists/",
      source: "LC 23",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Heap of `(val, index, node)` tuples — module 10's deferred problem",
    },
    {
      num: 6,
      title: "Task Scheduler",
      url: "https://leetcode.com/problems/task-scheduler/",
      source: "LC 621",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Greedy + max-heap with a cooldown queue — schedule the most frequent task that's off cooldown",
    },
    {
      num: 7,
      title: "IPO",
      url: "https://leetcode.com/problems/ipo/",
      source: "LC 502",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Two-heap with capital threshold — min-heap of unaffordable projects by capital, max-heap of affordable projects by profit; advance pointer to move newly-affordable projects between heaps each round",
    },
    {
      num: 8,
      title: "Find Median From Data Stream",
      url: "https://leetcode.com/problems/find-median-from-data-stream/",
      source: "LC 295",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Two-heap balancing — the three-step rebalance order from Step 2",
    },
  ],
};
