import type { Module } from "../types";

export const heap: Module = {
  id: "heap",
  num: 16,
  name: "Heap / Priority Queue",
  section: "1d",
  tier: "core",
  order: 17,
  prereqIds: ["trees", "linked-list"],
  resources: [
    { title: "USACO Guide — Priority Queues (Silver)", url: "https://usaco.guide/silver/priority-queues" },
    { title: "Python heapq documentation", url: "https://docs.python.org/3/library/heapq.html" },
    { title: "CPH Book Ch. 4 — Data Structures (covers heap)", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Kth Largest Element in an Array",
      url: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
      source: "LC 215",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Your Step 1 problem — min-heap of size k: push every element, pop when size > k, return top. O(n log k). The canonical heap interview problem and the template every later top-K problem builds on. Quickselect is the O(n) alternative worth knowing as a follow-up.",
    },
    {
      num: 2,
      title: "Kth Largest Element in a Stream",
      url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
      source: "LC 703",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Streaming variant of #1 — the size-k min-heap pattern is identical, but now it must persist across `add()` calls. Teaches when to pick heap-of-size-k over sort (online vs offline).",
    },
    {
      num: 3,
      title: "Top K Frequent Elements",
      url: "https://leetcode.com/problems/top-k-frequent-elements/",
      source: "LC 347",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Frequency map + size-k heap on `(count, value)`. Heavy Meta/Amazon frequency. Bucket-sort O(n) is the follow-up the interviewer pushes for once you've solved it with a heap — knowing both is the senior signal.",
    },
    {
      num: 4,
      title: "K Closest Points to Origin",
      url: "https://leetcode.com/problems/k-closest-points-to-origin/",
      source: "LC 973",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Heap-of-size-k applied to distances — max-heap so we pop the farthest when a closer point arrives. Same template as #1 with a custom key.",
    },
    {
      num: 5,
      title: "Room Allocation",
      url: "https://cses.fi/problemset/task/1164",
      source: "CSES",
      difficulty: "medium",
      list: "UG ⭐",
      role: "extension",
      teaches: "Sort by arrival + min-heap of departures — the sweep-with-a-heap pattern that recurs in interval problems (LC 253 Meeting Rooms II is the LeetCode twin). First non-top-K use of the heap.",
    },
    {
      num: 6,
      title: "Reorganize String",
      url: "https://leetcode.com/problems/reorganize-string/",
      source: "LC 767",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Greedy heap scheduling for non-adjacency — count character frequencies, push `(-count, char)` into a max-heap; at each step pop the two highest-count chars, append both, decrement and re-push if non-zero. Heap is the engine; the 'pop two and append' invariant guarantees adjacency rules. Foreshadows LC 621 Task Scheduler next.",
    },
    {
      num: 7,
      title: "Task Scheduler",
      url: "https://leetcode.com/problems/task-scheduler/",
      source: "LC 621",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Greedy + max-heap with a cooldown queue — pop the most frequent ready task each tick, push it onto a cooldown queue stamped with its release time, drain back to the heap when ready. The cooldown-queue companion structure generalises to rate-limited scheduling.",
    },
    {
      num: 8,
      title: "Merge K Sorted Lists",
      url: "https://leetcode.com/problems/merge-k-sorted-lists/",
      source: "LC 23",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Heap of `(val, index, node)` tuples — module 10's deferred problem. The `index` tiebreaker matters when nodes are non-comparable. Same template applies to LC 378 (sorted matrix) and merging k streams.",
    },
    {
      num: 9,
      title: "IPO",
      url: "https://leetcode.com/problems/ipo/",
      source: "LC 502",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Two-heap with capital threshold — min-heap of unaffordable projects by capital, max-heap of affordable projects by profit; advance pointer to move newly-affordable projects between heaps each round. First two-heap problem; sets up the checkpoint.",
    },
    {
      num: 10,
      title: "Find Median From Data Stream",
      url: "https://leetcode.com/problems/find-median-from-data-stream/",
      source: "LC 295",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: which earlier problem partitioned items across two heaps with different ordering, and what is the invariant that makes the median O(1) to read? Two-heap balancing: max-heap over the lower half, min-heap over the upper half. The three-step rebalance (push to one side, transfer top to the other, rebalance sizes) keeps `|lo| − |hi| ∈ {0, 1}` so the median is always the top(s).",
    },
  ],
};
