import type { Module } from "../types";

export const greedy: Module = {
  id: "greedy",
  num: 26,
  name: "Greedy",
  section: "2a",
  tier: "core",
  order: 26,
  prereqIds: ["arrays-hashing", "sorting"],
  resources: [
    { title: "USACO Guide — Intro to Greedy (Bronze)", url: "https://usaco.guide/bronze/intro-greedy" },
    { title: "USACO Guide — Greedy Sorting (Silver)", url: "https://usaco.guide/silver/greedy-sorting" },
    { title: "CPH Chapter 6 — Greedy Algorithms", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Tasks and Deadlines",
      url: "https://cses.fi/problemset/task/1630",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "baseline",
      teaches: "Sort + iterate with exchange-argument optimality — your Step 1 problem",
    },
    {
      num: 2,
      title: "Maximum Subarray",
      url: "https://leetcode.com/problems/maximum-subarray/",
      source: "LC 53",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Kadane's — running aggregate with local reset rule",
    },
    {
      num: 3,
      title: "Jump Game",
      url: "https://leetcode.com/problems/jump-game/",
      source: "LC 55",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Max-reach single-pass invariant",
    },
    {
      num: 4,
      title: "Jump Game II",
      url: "https://leetcode.com/problems/jump-game-ii/",
      source: "LC 45",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Extends LC 55 with BFS-style level counting — track current jump's reach AND next jump's reach",
    },
    {
      num: 5,
      title: "Partition Labels",
      url: "https://leetcode.com/problems/partition-labels/",
      source: "LC 763",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "One-pass with `last_occurrence` lookup; close a partition when the running max-last-index equals the current index",
    },
    {
      num: 6,
      title: "Gas Station",
      url: "https://leetcode.com/problems/gas-station/",
      source: "LC 134",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Cumulative deficit insight — global feasibility check + restart-on-negative",
    },
    {
      num: 7,
      title: "Hand of Straights",
      url: "https://leetcode.com/problems/hand-of-straights/",
      source: "LC 846",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Sort + frequency map — greedily consume the smallest remaining card to start each group",
    },
    {
      num: 8,
      title: "Candy",
      url: "https://leetcode.com/problems/candy/",
      source: "LC 135",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "Multi-pass greedy — left-pass enforces the right-neighbor constraint, right-pass enforces the left-neighbor constraint, take the max. The only problem in the module that uses two scans; callbacks to module 4's two-scan span pattern applied in a greedy context",
    },
    {
      num: 9,
      title: "Valid Parenthesis String",
      url: "https://leetcode.com/problems/valid-parenthesis-string/",
      source: "LC 678",
      difficulty: "medium",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: a single open-paren counter can't decide whether `*` should be `(`, `)`, or empty. What lightweight extension tracks all possibilities at once? Two-bound tracking. Maintain `low` (min possible open count) and `high` (max possible open count); reject if `high < 0`, succeed if `low == 0` at the end.",
    },
  ],
};
