import type { Module } from "../types";

export const intervals: Module = {
  id: "intervals",
  num: 18,
  name: "Intervals & Sweep Line",
  label: "Intervals &\nSweep Line",
  section: "2b",
  track: "both",
  order: 18,
  prereqIds: ["greedy", "heap"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Greedy Sorting (Silver)", url: "https://usaco.guide/silver/greedy-sorting" },
    { title: "CP-Algorithms — Sweep Line (segment intersection)", url: "https://cp-algorithms.com/geometry/intersecting_segments.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Meeting Rooms",
      url: "https://leetcode.com/problems/meeting-rooms/",
      source: "LC 252",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Sort by start time, then linear scan checking adjacent pairs — the simplest 'do intervals overlap?' primitive. Establishes the sort-then-scan pattern before the more elaborate merge and sweep variants",
    },
    {
      num: 2,
      title: "Movie Festival",
      url: "https://cses.fi/problemset/task/1629",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "EFT greedy with exchange-argument proof — your Step 1 problem",
    },
    {
      num: 3,
      title: "Merge Intervals",
      url: "https://leetcode.com/problems/merge-intervals/",
      source: "LC 56",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Sort by start + extend running interval — different sort key, different sub-pattern",
    },
    {
      num: 4,
      title: "Insert Interval",
      url: "https://leetcode.com/problems/insert-interval/",
      source: "LC 57",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same merge logic as LC 56 but with a pre-sorted list and one insertion — three-phase scan",
    },
    {
      num: 5,
      title: "Non-overlapping Intervals",
      url: "https://leetcode.com/problems/non-overlapping-intervals/",
      source: "LC 435",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same EFT machinery as problem 1, framed as \"minimum removals = n − max non-overlapping\"",
    },
    {
      num: 6,
      title: "Meeting Rooms II",
      url: "https://leetcode.com/problems/meeting-rooms-ii/",
      source: "LC 253",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Sweep line with start/end events — third sub-pattern",
    },
    {
      num: 7,
      title: "Minimum Interval to Include Each Query",
      url: "https://leetcode.com/problems/minimum-interval-to-include-each-query/",
      source: "LC 1851",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Sort queries offline + heap of size k keyed by interval size; remove expired intervals",
    },
  ],
};
