import type { Module } from "../types";

export const intervals: Module = {
  id: "intervals",
  num: 25,
  name: "Intervals & Sweep Line",
  label: "Intervals &\nSweep Line",
  section: "2a",
  tier: "core",
  order: 25,
  prereqIds: ["greedy", "heap"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Greedy Sorting (Silver)", url: "https://usaco.guide/silver/greedy-sorting" },
    { title: "CP-Algorithms — Sweep Line (segment intersection)", url: "https://cp-algorithms.com/geometry/intersecting_segments.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Meeting Rooms",
      url: "https://leetcode.com/problems/meeting-rooms/",
      source: "LC 252",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Sort by start time, then linear scan checking adjacent pairs — the simplest 'do intervals overlap?' primitive. Establishes the sort-then-scan pattern before the more elaborate merge and sweep variants — your Step 1 problem",
    },
    {
      num: 2,
      title: "Merge Intervals",
      url: "https://leetcode.com/problems/merge-intervals/",
      source: "LC 56",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Sort by start + extend running interval — the canonical merge sub-pattern. Most-asked interval problem at Meta/Google",
    },
    {
      num: 3,
      title: "Insert Interval",
      url: "https://leetcode.com/problems/insert-interval/",
      source: "LC 57",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same merge logic as LC 56 but with a pre-sorted list and one insertion — three-phase scan (before, overlapping, after)",
    },
    {
      num: 4,
      title: "Meeting Rooms II",
      url: "https://leetcode.com/problems/meeting-rooms-ii/",
      source: "LC 253",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Sweep line with start/end events OR min-heap of end times — the second canonical sub-pattern. Counts concurrent intervals = max heap size during the sweep",
    },
    {
      num: 5,
      title: "Movie Festival",
      url: "https://cses.fi/problemset/task/1629",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "Earliest-finish-time (EFT) greedy with exchange-argument proof — sort by end time, then take any interval that starts at or after the last taken interval's end",
    },
    {
      num: 6,
      title: "Non-overlapping Intervals",
      url: "https://leetcode.com/problems/non-overlapping-intervals/",
      source: "LC 435",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same EFT machinery as Movie Festival, framed as \"minimum removals = n − max non-overlapping\"",
    },
    {
      num: 7,
      title: "My Calendar I",
      url: "https://leetcode.com/problems/my-calendar-i/",
      source: "LC 729",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Sorted-interval design problem — maintain a sorted structure (BST via `SortedList` or array + `bisect_right`) of booked `(start, end)` intervals. On `book(s, e)`, locate the right-neighbor with `bisect_right` and check overlap with both the right-neighbor and its predecessor. O(log n) per insert.",
    },
    {
      num: 8,
      title: "Minimum Interval to Include Each Query",
      url: "https://leetcode.com/problems/minimum-interval-to-include-each-query/",
      source: "LC 1851",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: queries arrive unordered; each needs only the intervals covering it. What decouples query order from processing, and what (module 16) finds the smallest live interval? Sort queries offline; sweep a min-heap keyed by interval size; lazily pop intervals whose end has passed the current query point.",
    },
  ],
};
