import type { Module } from "../types";

export const graphTraversal: Module = {
  id: "graph-traversal",
  num: 19,
  name: "Graph Traversal",
  section: "2c",
  tier: "core",
  order: 24,
  prereqIds: ["trees", "binary-search"],
  resources: [
    { title: "USACO Guide — Graph Traversal (Silver)", url: "https://usaco.guide/silver/graph-traversal" },
    { title: "USACO Guide — Flood Fill (Silver)", url: "https://usaco.guide/silver/flood-fill" },
    { title: "CPH Chapter 12 — Graph Traversal", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Number of Islands",
      url: "https://leetcode.com/problems/number-of-islands/",
      source: "LC 200",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Grid DFS for connected components — your Step 1 problem",
    },
    {
      num: 2,
      title: "Rotting Oranges",
      url: "https://leetcode.com/problems/rotting-oranges/",
      source: "LC 994",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Multi-source BFS — distance from a set, computed in one pass",
    },
    {
      num: 3,
      title: "Number of Provinces",
      url: "https://leetcode.com/problems/number-of-provinces/",
      source: "LC 547",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Connected components on an adjacency matrix — DFS/BFS from each unvisited city, marking all reachable cities, incrementing the province count. Same component-counting mechanic as LC 200 but on an explicit graph rather than a grid. FAANG-direct version of CSES Building Roads.",
    },
    {
      num: 4,
      title: "Clone Graph",
      url: "https://leetcode.com/problems/clone-graph/",
      source: "LC 133",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "DFS with `{old → new}` visited dict — same node returned consistently across recursive calls",
    },
    {
      num: 5,
      title: "01 Matrix",
      url: "https://leetcode.com/problems/01-matrix/",
      source: "LC 542",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Multi-source BFS — initialise the queue with ALL zero cells at distance 0, then expand outward. Each cell's distance is computed in a single sweep rather than running BFS from each cell. The 'reverse the question' trick: instead of 'distance from x to nearest 0', compute 'distance from each 0 to x'",
    },
    {
      num: 6,
      title: "Is Graph Bipartite?",
      url: "https://leetcode.com/problems/is-graph-bipartite/",
      source: "LC 785",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Bipartite check via BFS/DFS 2-coloring — assign color 0 to the start node, alternate colors across edges; conflict (same color on adjacent nodes) means the graph is not bipartite. Must iterate over connected components in case the graph is disconnected. Canonical FAANG bipartite question.",
    },
    {
      num: 7,
      title: "Pacific Atlantic Water Flow",
      url: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
      source: "LC 417",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Reverse the direction — BFS *out* from both oceans' boundaries, intersect the reachable sets",
    },
    {
      num: 8,
      title: "Surrounded Regions",
      url: "https://leetcode.com/problems/surrounded-regions/",
      source: "LC 130",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Anchor DFS from border-touching `'O'`s, mark survivors, flip the rest",
    },
    {
      num: 9,
      title: "Open the Lock",
      url: "https://leetcode.com/problems/open-the-lock/",
      source: "LC 752",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "State-space BFS — the node is a 4-tuple of digits, not a position; 8 neighbours per state (each wheel ±1); deadends become walls in the state space. Makes the state-encoding step explicit before Word Ladder hides it inside string transforms",
    },
    {
      num: 10,
      title: "Critical Connections in a Network",
      url: "https://leetcode.com/problems/critical-connections-in-a-network/",
      source: "LC 1192",
      difficulty: "hard",
      list: "NC150",
      role: "combination",
      teaches: "Tarjan's bridges — DFS maintaining `disc[u]` (discovery time) and `low[u]` (lowest disc reachable via back-edges from `u`'s subtree). Edge `(u, v)` is a bridge iff `low[v] > disc[u]`. The `low` update propagates from children except via the parent edge. Critical edges = bridges. FAANG-frequent at Meta and Google.",
    },
    {
      num: 11,
      title: "Word Ladder",
      url: "https://leetcode.com/problems/word-ladder/",
      source: "LC 127",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: no adjacency list is given — what made problem 9's state-space BFS work, and how do you transplant it to strings? Implicit graph: words are nodes, edges join words differing by one letter. BFS for shortest transformation; bucket neighbours by wildcard patterns (`h*t`, `ho*`, ...) to avoid the O(L · |dict|) per-pop pairwise check.",
    },
  ],
};
