import type { Module } from "../types";

export const graphTraversal: Module = {
  id: "graph-traversal",
  num: 19,
  name: "Graph Traversal",
  section: "2a",
  track: "both",
  order: 19,
  prereqIds: ["trees", "binary-search"],
  resources: [
    { title: "USACO Guide — Graph Traversal (Silver)", url: "https://usaco.guide/silver/graph-traversal" },
    { title: "USACO Guide — Flood Fill (Silver)", url: "https://usaco.guide/silver/flood-fill" },
  ],
  problems: [
    {
      num: 1,
      title: "Number of Islands",
      url: "https://leetcode.com/problems/number-of-islands/",
      source: "LC 200",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Grid DFS for connected components — your Step 1 problem",
    },
    {
      num: 2,
      title: "Rotting Oranges",
      url: "https://leetcode.com/problems/rotting-oranges/",
      source: "LC 994",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Multi-source BFS — distance from a set, computed in one pass",
    },
    {
      num: 3,
      title: "Building Roads",
      url: "https://cses.fi/problemset/task/1666",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Adjacency-list DFS — count components, then `k − 1` edges to connect them",
    },
    {
      num: 4,
      title: "Clone Graph",
      url: "https://leetcode.com/problems/clone-graph/",
      source: "LC 133",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "DFS with `{old → new}` visited dict — same node returned consistently across recursive calls",
    },
    {
      num: 5,
      title: "Building Teams",
      url: "https://cses.fi/problemset/task/1668",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Bipartite 2-colouring via BFS — same-coloured neighbour means odd cycle",
    },
    {
      num: 6,
      title: "Pacific Atlantic Water Flow",
      url: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
      source: "LC 417",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Reverse the direction — BFS *out* from both oceans' boundaries, intersect the reachable sets",
    },
    {
      num: 7,
      title: "Surrounded Regions",
      url: "https://leetcode.com/problems/surrounded-regions/",
      source: "LC 130",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Anchor DFS from border-touching `'O'`s, mark survivors, flip the rest",
    },
    {
      num: 8,
      title: "Word Ladder",
      url: "https://leetcode.com/problems/word-ladder/",
      source: "LC 127",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Implicit graph — words are nodes, BFS finds shortest transformation",
    },
  ],
};
