import type { Module } from "../types";

export const topoSort: Module = {
  id: "topo-sort",
  num: 28,
  name: "Topological Sort",
  section: "2c",
  tier: "core",
  order: 28,
  prereqIds: ["graph-traversal"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Topological Sort (Gold)", url: "https://usaco.guide/gold/toposort" },
    { title: "CP-Algorithms — Topological Sort", url: "https://cp-algorithms.com/graph/topological-sort.html" },
    { title: "CPH Book Ch. 16 — Directed Graphs", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Course Schedule",
      url: "https://leetcode.com/problems/course-schedule/",
      source: "LC 207",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Kahn's algorithm — your Step 1 problem; check `len(order) == n` for cycle",
    },
    {
      num: 2,
      title: "Course Schedule II",
      url: "https://leetcode.com/problems/course-schedule-ii/",
      source: "LC 210",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same algorithm, return the order itself instead of a boolean",
    },
    {
      num: 3,
      title: "Round Trip II",
      url: "https://cses.fi/problemset/task/1678",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "Directed cycle detection — print the cycle's nodes, not just a boolean; DFS with three colours",
    },
    {
      num: 4,
      title: "Timeline",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=1017",
      source: "USACO Gold",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "Longest distance in a DAG — Kahn's order + dp relaxation along edges (max aggregation); preview of module 25 DAG DP",
    },
    {
      num: 5,
      title: "Game Routes",
      url: "https://cses.fi/problemset/task/1681",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "extension",
      teaches: "Same DAG DP scaffold as problem 4, but **sum** aggregation — count paths from 1 to n; shows the aggregation operator is the only thing that changes",
    },
    {
      num: 6,
      title: "Find Eventual Safe States",
      url: "https://leetcode.com/problems/find-eventual-safe-states/",
      source: "LC 802",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "3-color DFS for cycle membership — a node is 'safe' iff it cannot reach any cycle. Color nodes white/gray/black during DFS; on cycle detection (gray neighbor), propagate 'unsafe' to all gray ancestors. Alternatively reverse the graph and run topo sort: starting from out-degree-0 nodes and peeling. Both formulations are FAANG-asked.",
    },
    {
      num: 7,
      title: "Build a Matrix With Conditions",
      url: "https://leetcode.com/problems/build-a-matrix-with-conditions/",
      source: "LC 2392",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "Multi-dim topo — run topological sort independently on rowConditions and colConditions, then place each value at `(rowPos[v], colPos[v])`. Each axis fails its own cycle check independently",
    },
    {
      num: 8,
      title: "Alien Dictionary",
      url: "https://leetcode.com/problems/alien-dictionary/",
      source: "LC 269",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: the input is a list of strings, not edges — where does the precedence graph come from? Compare each adjacent word pair letter-by-letter; the first differing position contributes one edge. Topo-sort the 26 letters with Kahn's; reject if a longer word precedes its own prefix (`ab` after `abc`) since that's an unencodable order.",
    },
  ],
};
