import type { Module } from "../types";

export const unionFind: Module = {
  id: "union-find",
  num: 21,
  name: "Union-Find / DSU",
  section: "2a",
  track: "both",
  order: 21,
  prereqIds: ["arrays-hashing"],
  isNew: true,
  resources: [
    { title: "USACO Guide — DSU (Silver)", url: "https://usaco.guide/silver/dsu" },
    { title: "CP-Algorithms — Disjoint Set Union", url: "https://cp-algorithms.com/data_structures/disjoint_set_union.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Road Construction",
      url: "https://cses.fi/problemset/task/1676",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Incremental component tracking with size — your Step 1 problem",
    },
    {
      num: 2,
      title: "Redundant Connection",
      url: "https://leetcode.com/problems/redundant-connection/",
      source: "LC 684",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Cycle detection via \"same root before union\"",
    },
    {
      num: 3,
      title: "Graph Valid Tree",
      url: "https://leetcode.com/problems/graph-valid-tree/",
      source: "LC 261",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Tree validation = connected + acyclic + exactly n−1 edges; combine cycle check with final component count",
    },
    {
      num: 4,
      title: "Accounts Merge",
      url: "https://leetcode.com/problems/accounts-merge/",
      source: "LC 721",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "String-keyed DSU — replace the integer parent array with a dict; each email is a node. Groups accounts by unioning emails that appear together, then reconstructs sorted groups per root. The canonical interview DSU problem where the key insight is that nodes are strings, not indices",
    },
    {
      num: 5,
      title: "Number of Operations to Make Network Connected",
      url: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/",
      source: "LC 1319",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Count surplus edges (those within already-connected components); check if surplus ≥ components − 1",
    },
    {
      num: 6,
      title: "Mootube",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=789",
      source: "USACO Gold",
      difficulty: "medium",
      list: "UG ⭐",
      role: "extension",
      teaches: "Offline DSU — sort queries and edges by weight, sweep with unions; preview of Kruskal's-style technique used in module 23",
    },
    {
      num: 7,
      title: "Wormhole Sort",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=992",
      source: "USACO Silver",
      difficulty: "medium",
      list: "UG ⭐",
      role: "checkpoint",
      teaches: "Binary search on the answer (module 12) + DSU connectivity check — combine two earlier modules",
    },
  ],
};
