import type { Module } from "../types";

export const unionFind: Module = {
  id: "union-find",
  num: 21,
  name: "Union-Find / DSU",
  section: "2a",
  track: "both",
  order: 21,
  prereqIds: ["arrays-hashing"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Disjoint Set Union (Gold)", url: "https://usaco.guide/gold/dsu" },
  ],
  problems: [
    {
      num: 1,
      title: "Road Construction",
      url: "https://cses.fi/problemset/task/1676",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Incremental component tracking with size — your Step 1 problem",
    },
    {
      num: 2,
      title: "Redundant Connection",
      url: "https://leetcode.com/problems/redundant-connection/",
      source: "LC 684",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Cycle detection via \"same root before union\"",
    },
    {
      num: 3,
      title: "Graph Valid Tree",
      url: "https://leetcode.com/problems/graph-valid-tree/",
      source: "LC 261",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Tree validation = connected + acyclic + exactly n−1 edges; combine cycle check with final component count",
    },
    {
      num: 4,
      title: "Number of Operations to Make Network Connected",
      url: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/",
      source: "LC 1319",
      difficulty: "medium",
      list: "⭐",
      role: "extension",
      teaches: "Count surplus edges (those within already-connected components); check if surplus ≥ components − 1",
    },
    {
      num: 5,
      title: "Mootube",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=789",
      source: "USACO Gold",
      difficulty: "easy",
      list: "UG ⭐",
      role: "extension",
      teaches: "Offline DSU — sort queries and edges by weight, sweep with unions; preview of Kruskal's-style technique used in module 23",
    },
    {
      num: 6,
      title: "Wormhole Sort",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=992",
      source: "USACO Silver",
      difficulty: "medium",
      list: "UG ⭐",
      role: "checkpoint",
      teaches: "Binary search on the answer (module 12) + DSU connectivity check — combine two earlier modules",
    },
  ],
};
