import type { Module } from "../types";

export const shortestPaths: Module = {
  id: "shortest-paths",
  num: 22,
  name: "Shortest Paths",
  section: "2a",
  track: "both",
  order: 22,
  prereqIds: ["graph-traversal", "heap"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Shortest Paths (Gold)", url: "https://usaco.guide/gold/shortest-paths" },
  ],
  problems: [
    {
      num: 1,
      title: "Network Delay Time",
      url: "https://leetcode.com/problems/network-delay-time/",
      source: "LC 743",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Dijkstra with heap — your Step 1 problem; final answer is `max(dist)`",
    },
    {
      num: 2,
      title: "Flight Discount",
      url: "https://cses.fi/problemset/task/1195",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "Dijkstra with **state augmentation** — track `(node, discount_used)`; relax with or without using the discount",
    },
    {
      num: 3,
      title: "High Score",
      url: "https://cses.fi/problemset/task/1673",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "Bellman-Ford — handles negative weights; mark nodes affected by negative cycles via a second-pass",
    },
    {
      num: 4,
      title: "Cheapest Flights Within K Stops",
      url: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
      source: "LC 787",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Bellman-Ford with **edge-count limit** — run K + 1 waves instead of V − 1; or state-augmented Dijkstra",
    },
    {
      num: 5,
      title: "Shortest Routes II",
      url: "https://cses.fi/problemset/task/1672",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "Floyd-Warshall — all-pairs distances; `O(V³)` precomputation, then O(1) per query",
    },
    {
      num: 6,
      title: "Swim in Rising Water",
      url: "https://leetcode.com/problems/swim-in-rising-water/",
      source: "LC 778",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Dijkstra with **minimax relaxation** — replace `dist[u] + w` with `max(dist[u], cell)`; the greedy invariant still holds for monotone path statistics",
    },
  ],
};
