import type { Module } from "../types";

export const mst: Module = {
  id: "mst",
  num: 23,
  name: "MST",
  section: "2c",
  tier: "faang-plus",
  order: 28,
  prereqIds: ["union-find", "shortest-paths"],
  isNew: true,
  resources: [
    { title: "USACO Guide — MST (Gold)", url: "https://usaco.guide/gold/mst" },
    { title: "CP-Algorithms — Kruskal's Algorithm", url: "https://cp-algorithms.com/graph/mst_kruskal.html" },
    { title: "CP-Algorithms — Prim's Algorithm", url: "https://cp-algorithms.com/graph/mst_prim.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Road Reparation",
      url: "https://cses.fi/problemset/task/1675",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Kruskal's from scratch — your Step 1 problem",
    },
    {
      num: 2,
      title: "Min Cost to Connect All Points",
      url: "https://leetcode.com/problems/min-cost-to-connect-all-points/",
      source: "LC 1584",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Prim's on a complete graph — all O(n²) edges implicit, so Prim's without pre-generating edges is cleaner",
    },
    {
      num: 3,
      title: "Superbull",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=531",
      source: "USACO Old Silver",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "MST where edge weights are computed from node values (XOR or sum) — must build the edge list from scratch",
    },
    {
      num: 4,
      title: "I Would Walk 500 Miles",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=946",
      source: "USACO Gold",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "Large n MST with structured edge costs — Kruskal's with careful edge generation",
    },
    {
      num: 5,
      title: "GCD and MST",
      url: "https://codeforces.com/problemset/problem/1513/D",
      source: "CF 1513D",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "Not all edges present — edges exist only when GCD condition holds; construct edges cleverly before Kruskal's",
    },
    {
      num: 6,
      title: "Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
      url: "https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/",
      source: "LC 1489",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Kruskal's + edge-classification — compute baseline MST weight, then for each edge: (a) force-exclude it and check if MST weight rises (critical), (b) force-include it and check if MST weight stays the same (pseudo-critical). Teaches the 'perturb the input' technique on MST",
    },
    {
      num: 7,
      title: "Portals",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=1138",
      source: "USACO Gold",
      difficulty: "medium",
      list: "UG",
      role: "checkpoint",
      teaches: "Before reading: no edge list is handed in — what is the unit of work, and how do you reduce the grid to a Kruskal-ready edge set? Treat each portal pair as a candidate edge between its two endpoints; enumerate the O(n²) pair-of-portals edges with costs from the grid, then run Kruskal + DSU. The leap is recognising the right edge model.",
    },
  ],
};
