import type { Module } from "../types";

export const advGraphs: Module = {
  id: "adv-graphs",
  num: 24,
  name: "Advanced Graphs",
  section: "2a",
  track: "cp",
  order: 24,
  prereqIds: ["topo-sort", "shortest-paths"],
  resources: [
    { title: "USACO Guide — SCC (Advanced)", url: "https://usaco.guide/adv/SCC" },
  ],
  problems: [
    {
      num: 1,
      title: "Planets & Kingdoms",
      url: "https://cses.fi/problemset/task/1683",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Kosaraju's SCC — your Step 1 problem",
    },
    {
      num: 2,
      title: "Coin Collector",
      url: "https://cses.fi/problemset/task/1686",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "SCC condensation + DAG DP — collect max coins; each SCC contributes its total coin sum",
    },
    {
      num: 3,
      title: "Grass Cownoisseur",
      url: "http://www.usaco.org/index.php?page=viewproblem2&cpid=516",
      source: "USACO Old Gold",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "SCC condensation + greedy on DAG — contest problem where the algorithm isn't named",
    },
    {
      num: 4,
      title: "Giant Pizza",
      url: "https://cses.fi/problemset/task/1684",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "2-SAT — implication graph, SCC, variable assignment from topological position",
    },
    {
      num: 5,
      title: "Reconstruct Itinerary",
      url: "https://leetcode.com/problems/reconstruct-itinerary/",
      source: "LC 332",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Eulerian path via Hierholzer's — the itinerary visits every flight once",
    },
    {
      num: 6,
      title: "Proving Equivalences",
      url: "https://open.kattis.com/problems/equivalences",
      source: "Kattis",
      difficulty: "hard",
      list: "UG",
      role: "checkpoint",
      teaches: "SCC application with counting — min edges to add to make all nodes mutually reachable; `max(sources, sinks)` in condensation where `sources = SCCs with in-degree 0`, `sinks = SCCs with out-degree 0`",
    },
  ],
};
