import type { Module } from "../types";

export const dpIntro: Module = {
  id: "dp-intro",
  num: 18,
  name: "DP Intro / 1D",
  section: "2b",
  tier: "core",
  order: 18,
  prereqIds: ["backtracking"],
  resources: [
    { title: "USACO Guide — Intro to DP (Gold)", url: "https://usaco.guide/gold/intro-dp" },
    { title: "AtCoder Educational DP Contest", url: "https://atcoder.jp/contests/dp" },
    { title: "CPH Book Ch. 7 — Dynamic Programming", url: "https://cses.fi/book/book.pdf" },
    { title: "CP-Algorithms — Dynamic Programming", url: "https://cp-algorithms.com/dynamic_programming/intro-to-dp.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Frog 1",
      url: "https://atcoder.jp/contests/dp/tasks/dp_a",
      source: "AC",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Your Step 1 problem — linear DP, two-predecessor transition",
    },
    {
      num: 2,
      title: "Best Time to Buy and Sell Stock",
      url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
      source: "LC 121",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "One-pass min-tracking — at each `prices[i]`, track `min_so_far` and the best profit so far (`prices[i] - min_so_far`). The DP framing reduces to two running scalars. Precursor to this module's state-machine DP at LC 309: here the state is implicit (held/not-held), there it's explicit.",
    },
    {
      num: 3,
      title: "House Robber",
      url: "https://leetcode.com/problems/house-robber/",
      source: "LC 198",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Take-or-skip with a single constraint; introduces the skip-or-take pattern",
    },
    {
      num: 4,
      title: "House Robber II",
      url: "https://leetcode.com/problems/house-robber-ii/",
      source: "LC 213",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Circular → two subproblems; solve the same linear DP twice",
    },
    {
      num: 5,
      title: "Decode Ways",
      url: "https://leetcode.com/problems/decode-ways/",
      source: "LC 91",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Parsing DP — transitions depend on the actual character values, not just position",
    },
    {
      num: 6,
      title: "Word Break",
      url: "https://leetcode.com/problems/word-break/",
      source: "LC 139",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Interval-scan DP — `dp[i]` looks back at all `dp[j]` for `j < i`",
    },
    {
      num: 7,
      title: "Maximum Product Subarray",
      url: "https://leetcode.com/problems/maximum-product-subarray/",
      source: "LC 152",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Tracking max and min in parallel — negatives flip sign, so the running minimum can become the next maximum",
    },
    {
      num: 8,
      title: "Best Time to Buy and Sell Stock with Cooldown",
      url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
      source: "LC 309",
      difficulty: "medium",
      list: "NC150",
      role: "combination",
      teaches: "State-machine DP — `dp[i][state]` with finite states (hold / sold / rest) and transitions between states, not just indices. Combines linear DP with an extra state dimension, bridging House Robber's collapsible take-or-skip and LC 152's parallel-scalar tracking before the hard synthesis",
    },
    {
      num: 9,
      title: "Palindrome Partitioning II",
      url: "https://leetcode.com/problems/palindrome-partitioning-ii/",
      source: "LC 132",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: a Word-Break-style backward scan over `j < i` is half of this. What auxiliary structure cheaply answers `isPalindrome(j, i)` inside the inner loop? A 2D `pal[i][j]` filled by length. `dp[i]` = min cuts for `s[0..i]`; the 1D partition objective sits on top of the 2D palindrome lookup — the bridge into module 26.",
    },
  ],
};
