import type { Module } from "../types";

export const dpIntro: Module = {
  id: "dp-intro",
  num: 25,
  name: "DP Intro / 1D",
  section: "2c",
  track: "both",
  order: 25,
  prereqIds: ["backtracking"],
  resources: [
    { title: "USACO Guide — Intro to DP (Gold)", url: "https://usaco.guide/gold/intro-dp" },
    { title: "AtCoder Educational DP Contest", url: "https://atcoder.jp/contests/dp" },
    { title: "CPH Book Ch. 7 — Dynamic Programming", url: "https://cses.fi/book/book.pdf" },
    { title: "CP-Algorithms — Dynamic Programming", url: "https://cp-algorithms.com/dynamic_programming/intro-to-dp.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Frog 1",
      url: "https://atcoder.jp/contests/dp/tasks/dp_a",
      source: "AC",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "Your Step 1 problem — linear DP, two-predecessor transition",
    },
    {
      num: 2,
      title: "Climbing Stairs",
      url: "https://leetcode.com/problems/climbing-stairs/",
      source: "LC 70",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Fibonacci DP — counting paths instead of minimising cost; same two-predecessor structure",
    },
    {
      num: 3,
      title: "House Robber",
      url: "https://leetcode.com/problems/house-robber/",
      source: "LC 198",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Take-or-skip with a single constraint; introduces the skip-or-take pattern",
    },
    {
      num: 4,
      title: "House Robber II",
      url: "https://leetcode.com/problems/house-robber-ii/",
      source: "LC 213",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Circular → two subproblems; solve the same linear DP twice",
    },
    {
      num: 5,
      title: "Decode Ways",
      url: "https://leetcode.com/problems/decode-ways/",
      source: "LC 91",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Parsing DP — transitions depend on the actual character values, not just position",
    },
    {
      num: 6,
      title: "Word Break",
      url: "https://leetcode.com/problems/word-break/",
      source: "LC 139",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Interval-scan DP — `dp[i]` looks back at all `dp[j]` for `j < i`",
    },
    {
      num: 7,
      title: "Maximum Product Subarray",
      url: "https://leetcode.com/problems/maximum-product-subarray/",
      source: "LC 152",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Tracking max and min in parallel — negatives flip sign, so the running minimum can become the next maximum",
    },
    {
      num: 8,
      title: "Best Time to Buy and Sell Stock with Cooldown",
      url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
      source: "LC 309",
      difficulty: "medium",
      list: "NC150",
      role: "checkpoint",
      teaches: "State-machine DP — `dp[i][state]` with finite states (hold / sold / rest) and transitions between states, not just indices. The richest pattern in the module: the state dimension is what separates this from House Robber's collapsible take-or-skip and from LC 152's parallel-scalar tracking",
    },
  ],
};
