import type { Module } from "../types";

export const dp2d: Module = {
  id: "dp-2d",
  num: 26,
  name: "2D / Grid DP",
  section: "2d",
  track: "both",
  order: 30,
  prereqIds: ["dp-intro"],
  resources: [
    { title: "USACO Guide — Paths / Grids DP (Gold)", url: "https://usaco.guide/gold/paths-grids" },
    { title: "CPH Chapter 7 — Dynamic Programming", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Unique Paths",
      url: "https://leetcode.com/problems/unique-paths/",
      source: "LC 62",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Your Step 1 problem — 2D grid DP counting paths from top-left to bottom-right with only right/down moves. Recurrence `dp[i][j] = dp[i-1][j] + dp[i][j-1]`, base row/col all 1s. The cleanest possible introduction to 2D state; every other problem in this module reuses this scaffold.",
    },
    {
      num: 2,
      title: "Minimum Path Sum",
      url: "https://leetcode.com/problems/minimum-path-sum/",
      source: "LC 64",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same grid-DP structure, different objective — optimize min cost instead of count paths. Recurrence: `dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1])`. Shifts the mental model from counting to optimizing over the same 2D state",
    },
    {
      num: 3,
      title: "Maximal Square",
      url: "https://leetcode.com/problems/maximal-square/",
      source: "LC 221",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Geometric grid DP — `dp[i][j]` = side length of largest all-1 square with bottom-right at `(i,j)`. Recurrence `dp[i][j] = min(up, left, diagonal) + 1` is non-obvious: the bottleneck is the smallest square in the three directions",
    },
    {
      num: 4,
      title: "Edit Distance",
      url: "https://leetcode.com/problems/edit-distance/",
      source: "LC 72",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Two-string 2D DP — new sub-pattern: `dp[i][j]` over prefixes of two strings. Three transitions: insert, delete, replace; fill row by row",
    },
    {
      num: 5,
      title: "Interleaving String",
      url: "https://leetcode.com/problems/interleaving-string/",
      source: "LC 97",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "2D boolean DP on two string positions — can `s3[:i+j]` be interleaved from `s1[:i]` and `s2[:j]`?",
    },
    {
      num: 6,
      title: "Regular Expression Matching",
      url: "https://leetcode.com/problems/regular-expression-matching/",
      source: "LC 10",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Meta-canonical two-string 2D DP with a non-trivial transition. `dp[i][j]` = does `s[:i]` match `p[:j]`? The `*` case branches on **zero occurrences** (`dp[i][j-2]`) **or one-more occurrence** (`dp[i-1][j]` if `s[i-1]` matches `p[j-2]`). The transition table — not the recurrence — is the entire problem.",
    },
    {
      num: 7,
      title: "Longest Increasing Path in a Matrix",
      url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
      source: "LC 329",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: every earlier problem fills the table in row/column order. Why can't you do that here? Dependencies follow the value gradient, not the index gradient, so there's no static fill order. DFS + memoisation with `(i, j)` as cache key; `@lru_cache` handles topological order implicitly per cell.",
    },
  ],
};
