import type { Module } from "../types";

export const dp2d: Module = {
  id: "dp-2d",
  num: 26,
  name: "2D / Grid DP",
  section: "2c",
  track: "both",
  order: 26,
  prereqIds: ["dp-intro"],
  resources: [
    { title: "USACO Guide — Paths / Grids DP (Gold)", url: "https://usaco.guide/gold/paths-grids" },
  ],
  problems: [
    {
      num: 1,
      title: "Grid Paths",
      url: "https://cses.fi/problemset/task/1638",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "baseline",
      teaches: "Your Step 1 problem — 2D grid DP with blocked cells",
    },
    {
      num: 2,
      title: "Unique Paths",
      url: "https://leetcode.com/problems/unique-paths/",
      source: "LC 62",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same grid path DP, no obstacles, interview format",
    },
    {
      num: 3,
      title: "Edit Distance",
      url: "https://cses.fi/problemset/task/1639",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "baseline",
      teaches: "String alignment as 2D DP — new sub-pattern: `dp[i][j]` over two string prefixes",
    },
    {
      num: 4,
      title: "Edit Distance",
      url: "https://leetcode.com/problems/edit-distance/",
      source: "LC 72",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same edit distance, interview format",
    },
    {
      num: 5,
      title: "Longest Palindromic Substring",
      url: "https://leetcode.com/problems/longest-palindromic-substring/",
      source: "LC 5",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Palindrome DP — `dp[i][j] = \"is s[i..j] a palindrome\"`; fill in order of increasing length",
    },
    {
      num: 6,
      title: "Interleaving String",
      url: "https://leetcode.com/problems/interleaving-string/",
      source: "LC 97",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "2D boolean DP on two string positions — can `s3[:i+j]` be interleaved from `s1[:i]` and `s2[:j]`?",
    },
    {
      num: 7,
      title: "Distinct Subsequences",
      url: "https://leetcode.com/problems/distinct-subsequences/",
      source: "LC 115",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Same two-string 2D state, counting instead of optimising; only deletion direction matters",
    },
    {
      num: 8,
      title: "Longest Increasing Path in a Matrix",
      url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
      source: "LC 329",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "DFS + memoisation with `(i, j)` as cache key — no fixed traversal order; `@lru_cache` handles topological order implicitly",
    },
  ],
};
