import type { Module } from "../types";

export const dp2d: Module = {
  id: "dp-2d",
  num: 26,
  name: "2D / Grid DP",
  section: "2c",
  track: "both",
  order: 26,
  prereqIds: ["dp-intro"],
  resources: [
    { title: "USACO Guide — Paths / Grids DP (Gold)", url: "https://usaco.guide/gold/paths-grids" },
    { title: "CPH Chapter 7 — Dynamic Programming", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Grid Paths",
      url: "https://cses.fi/problemset/task/1638",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "baseline",
      teaches: "Your Step 1 problem — 2D grid DP with blocked cells; `dp[i][j] = dp[i-1][j] + dp[i][j-1]` when cell is open, 0 when blocked",
    },
    {
      num: 2,
      title: "Minimum Path Sum",
      url: "https://leetcode.com/problems/minimum-path-sum/",
      source: "LC 64",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same grid-DP structure, different objective — optimize min cost instead of count paths. Recurrence: `dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1])`. Shifts the mental model from counting to optimizing over the same 2D state",
    },
    {
      num: 3,
      title: "Maximal Square",
      url: "https://leetcode.com/problems/maximal-square/",
      source: "LC 221",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Geometric grid DP — `dp[i][j]` = side length of largest all-1 square with bottom-right at `(i,j)`. Recurrence `dp[i][j] = min(up, left, diagonal) + 1` is non-obvious: the bottleneck is the smallest square in the three directions",
    },
    {
      num: 4,
      title: "Longest Palindromic Substring",
      url: "https://leetcode.com/problems/longest-palindromic-substring/",
      source: "LC 5",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Palindrome DP — `dp[i][j] = \"is s[i..j] a palindrome\"`; fill in order of increasing length",
    },
    {
      num: 5,
      title: "Edit Distance",
      url: "https://leetcode.com/problems/edit-distance/",
      source: "LC 72",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Two-string 2D DP — new sub-pattern: `dp[i][j]` over prefixes of two strings. Three transitions: insert, delete, replace; fill row by row",
    },
    {
      num: 6,
      title: "Interleaving String",
      url: "https://leetcode.com/problems/interleaving-string/",
      source: "LC 97",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "2D boolean DP on two string positions — can `s3[:i+j]` be interleaved from `s1[:i]` and `s2[:j]`?",
    },
    {
      num: 7,
      title: "Distinct Subsequences",
      url: "https://leetcode.com/problems/distinct-subsequences/",
      source: "LC 115",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "Same two-string 2D state, counting instead of optimising; only deletion direction matters",
    },
    {
      num: 8,
      title: "Longest Increasing Path in a Matrix",
      url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
      source: "LC 329",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "DFS + memoisation with `(i, j)` as cache key — no fixed traversal order; `@lru_cache` handles topological order implicitly",
    },
  ],
};
