import type { Module } from "../types";

export const knapsack: Module = {
  id: "knapsack",
  num: 27,
  name: "Knapsack Family",
  section: "2c",
  track: "both",
  order: 27,
  prereqIds: ["dp-intro"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Knapsack DP (Gold)", url: "https://usaco.guide/gold/knapsack" },
    { title: "CPH Book Ch. 7 — Dynamic Programming", url: "https://cses.fi/book/book.pdf" },
    { title: "AtCoder Educational DP Contest", url: "https://atcoder.jp/contests/dp" },
  ],
  problems: [
    {
      num: 1,
      title: "Book Shop",
      url: "https://cses.fi/problemset/task/1158",
      source: "CSES",
      difficulty: "easy",
      list: "UG ⭐",
      role: "baseline",
      teaches: "0/1 knapsack baseline — items with weight + value, pick a subset with total weight ≤ W maximising value. Rolling 1D `dp[w]` iterated **backward** over weight to prevent reusing an item",
    },
    {
      num: 2,
      title: "Partition Equal Subset Sum",
      url: "https://leetcode.com/problems/partition-equal-subset-sum/",
      source: "LC 416",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "0/1 knapsack reframed as boolean subset-sum — `dp[j]` = can we make sum j? Target is `total / 2`; odd total is impossible. The problem doesn't say \"knapsack\" — recognising it is the work",
    },
    {
      num: 3,
      title: "Target Sum",
      url: "https://leetcode.com/problems/target-sum/",
      source: "LC 494",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Sign-split transform — split items into a `+` group (sum P) and a `−` group (sum N) with `P + N = total` and `P − N = target`, so `P = (total + target) / 2`. Reduces to subset-sum counting; the algebraic reframing is the leap",
    },
    {
      num: 4,
      title: "Coin Change",
      url: "https://leetcode.com/problems/coin-change/",
      source: "LC 322",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Unbounded knapsack with min objective — `dp[w]` = min coins to make w. Iterate weight **forward** so a coin can be reused. The forward/backward iteration order is the *only* structural difference between 0/1 and unbounded",
    },
    {
      num: 5,
      title: "Coin Change II",
      url: "https://leetcode.com/problems/coin-change-ii/",
      source: "LC 518",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same unbounded knapsack scaffolding as #4, now counting ways instead of minimising. Outer loop over coins, inner over amounts — this loop order produces unordered combinations (see #6 for what flips when you reverse them)",
    },
    {
      num: 6,
      title: "Combination Sum IV",
      url: "https://leetcode.com/problems/combination-sum-iv/",
      source: "LC 377",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Order matters — outer loop over amounts, inner over nums. Same recurrence as Coin Change II, but the flipped loop order counts ordered tuples (permutations), not unordered combinations. The loop-order flip is the entire insight",
    },
    {
      num: 7,
      title: "Perfect Squares",
      url: "https://leetcode.com/problems/perfect-squares/",
      source: "LC 279",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Unbounded knapsack on a *computed* item set (squares 1, 4, 9, 16, …) with min objective — same forward-iteration template as Coin Change. The items aren't given by the problem; you generate them up to n",
    },
    {
      num: 8,
      title: "Ones and Zeroes",
      url: "https://leetcode.com/problems/ones-and-zeroes/",
      source: "LC 474",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Multi-dimensional 0/1 knapsack — two simultaneous capacity constraints (zeros m, ones n). `dp[i][j]` over both dimensions, iterate **backward** over both. Same logic as #1, twice the state",
    },
    {
      num: 9,
      title: "Knapsack 2",
      url: "https://atcoder.jp/contests/dp/tasks/dp_e",
      source: "AC",
      difficulty: "hard",
      list: "UG",
      role: "checkpoint",
      teaches: "State-swap meta-pattern — when W is huge (10⁹) but the value sum is small (≤ 10⁵), `dp[w]` blows memory. Swap roles: `dp[v]` = **min weight** to achieve value v. Same algorithm, dual state. The takeaway: the dimension you index by is a *choice*, not given by the problem",
    },
  ],
};
