import type { Module } from "../types";

export const lisLcs: Module = {
  id: "lis-lcs",
  num: 28,
  name: "LIS / LCS",
  section: "2b",
  track: "both",
  order: 22,
  prereqIds: ["dp-intro"],
  isNew: true,
  resources: [
    { title: "USACO Guide — LIS (Gold)", url: "https://usaco.guide/gold/lis" },
    { title: "CP-Algorithms — Longest Increasing Subsequence", url: "https://cp-algorithms.com/sequences/longest_increasing_subsequence.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Longest Increasing Subsequence",
      url: "https://leetcode.com/problems/longest-increasing-subsequence/",
      source: "LC 300",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Two approaches in one problem. O(n²): `dp[i] = max(dp[j]+1 for j<i if a[j]<a[i])`. O(n log n): maintain a `tails` array and use `bisect_left` to binary-search the insertion point — `tails` is always sorted, so LIS length = `len(tails)` at the end. The O(n log n) insight is the leap from the naive DP.",
    },
    {
      num: 2,
      title: "Longest Common Subsequence",
      url: "https://leetcode.com/problems/longest-common-subsequence/",
      source: "LC 1143",
      difficulty: "medium",
      list: "NC150",
      role: "baseline",
      teaches: "Specialization of the two-string 2D DP introduced in module 26 problem 4 (Edit Distance): same `dp[i][j]` over two prefixes, but a cheaper cost model — no insert/delete cost, only match (`dp[i-1][j-1]+1`) or skip-one (`max(dp[i-1][j], dp[i][j-1])`). Foundation for every LCS-reduction problem that follows.",
    },
    {
      num: 3,
      title: "Longest Palindromic Subsequence",
      url: "https://leetcode.com/problems/longest-palindromic-subsequence/",
      source: "LC 516",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "LCS reduction — `LPS(s) = LCS(s, s[::-1])`. A palindromic subsequence appears in `s` and in `s` reversed. Forces the habit of recognising a string problem as LCS in disguise before reaching for a bespoke DP. Direct reduction with no new code needed after problem 2.",
    },
    {
      num: 4,
      title: "Number of Longest Increasing Subsequences",
      url: "https://leetcode.com/problems/number-of-longest-increasing-subsequences/",
      source: "LC 673",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Parallel count array — alongside `length[i]`, maintain `count[i]` = number of LIS ending at index `i`. When extending from `j`: if `length[j]+1 > length[i]`, reset count; if equal, accumulate. The final answer sums `count[i]` over all `i` achieving the max length.",
    },
    {
      num: 5,
      title: "Longest String Chain",
      url: "https://leetcode.com/problems/longest-string-chain/",
      source: "LC 1048",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "DAG/dict-keyed LIS — sort words by length, then `dp[word] = max(dp[pred]+1)` over all predecessors (words formed by deleting one character). The predecessor check (`word[:i] + word[i+1:]`) is the problem-specific logic; the DP skeleton is pure LIS on a partial order.",
    },
    {
      num: 6,
      title: "Towers",
      url: "https://cses.fi/problemset/task/1145",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "combination",
      teaches: "Dilworth's theorem — min # piles needed to cover an array equals LIS length. Greedy proof: place each element on the leftmost pile whose top is strictly greater; otherwise start a new pile. The pile count at any step equals the number of elements in the current LIS tails array. This patience-sort intuition is the engine behind the checkpoint.",
    },
    {
      num: 7,
      title: "Russian Doll Envelopes",
      url: "https://leetcode.com/problems/russian-doll-envelopes/",
      source: "LC 354",
      difficulty: "hard",
      list: "NC150",
      role: "checkpoint",
      teaches: "Before reading: 1D LIS handles one increasing axis. With two strict-increase constraints, what sort lets you drop one axis? Width ASC, height DESC. DESC on ties stops equal-width envelopes from chaining, so an O(n log n) LIS on heights alone is exact. The sort is the leap; problem 6's patience-sort is the implementation.",
    },
  ],
};
