import type { Module } from "../types";

export const dpTrees: Module = {
  id: "dp-trees",
  num: 26,
  name: "DP on Trees",
  section: "2b",
  tier: "core",
  order: 26,
  prereqIds: ["dp-intro", "trees"],
  isNew: true,
  resources: [
    { title: "USACO Guide — DP on Trees (Gold)", url: "https://usaco.guide/gold/dp-trees" },
    { title: "USACO Guide — All Roots (Rerooting, Gold)", url: "https://usaco.guide/gold/all-roots" },
    { title: "CPH Chapter 14.3 — Tree Dynamic Programming", url: "https://cses.fi/book/book.pdf" },
    { title: "AtCoder Educational DP Contest — Problem P (Tree DP)", url: "https://atcoder.jp/contests/dp/tasks/dp_p" },
  ],
  problems: [
    {
      num: 1,
      title: "Tree Matching",
      url: "https://cses.fi/problemset/task/1130",
      source: "CSES",
      difficulty: "medium",
      list: "UG ⭐",
      role: "baseline",
      teaches: "The canonical tree DP baseline — each node returns a **tuple `(take, skip)`** where `take` = best when this node is matched with a child, `skip` = best when it is not. Parent composes: `skip = sum(max(c.take, c.skip))`, `take = max over child c of (1 + c.skip + sum over others of max(...))`. Uses the tree DFS scaffold from module 14 with subtree-result composition",
    },
    {
      num: 2,
      title: "House Robber III",
      url: "https://leetcode.com/problems/house-robber-iii/",
      source: "LC 337",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same `(rob, skip)` tuple-return pattern as Tree Matching, in interview flavor — child returns `(rob_node, skip_node)`; parent does `skip = max(l) + max(r)`, `rob = node.val + l.skip + r.skip`. Mirrors the 1D House Robber recurrence from module 25 but composed over a tree instead of a line",
    },
    {
      num: 3,
      title: "Longest Univalue Path",
      url: "https://leetcode.com/problems/longest-univalue-path/",
      source: "LC 687",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Return-vs-record split — child returns the longest one-sided same-value arm continuing through it; parent records `left_arm + right_arm` into a global answer but only returns `max(left_arm, right_arm) + 1` upward. Same scaffold as LC 543/124 (module 14) but the value-equality guard is the new mechanic — composition is conditional on `child.val == node.val`",
    },
    {
      num: 4,
      title: "Longest ZigZag Path in a Binary Tree",
      url: "https://leetcode.com/problems/longest-zigzag-path-in-a-binary-tree/",
      source: "LC 1372",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Multi-state per node** — each node returns `(go_left_len, go_right_len)`, where the parent uses the opposite child's state to extend. First problem where a single scalar return is insufficient; the state vector encodes which direction you arrived from",
    },
    {
      num: 5,
      title: "Binary Tree Cameras",
      url: "https://leetcode.com/problems/binary-tree-cameras/",
      source: "LC 968",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "Three-state tree DP — each node returns one of `{covered_no_cam, covered_has_cam, uncovered}`; parent's state is determined by the combination of children's states. The transition table is the entire problem — a Google/Meta favorite that generalises the tuple-DP idea to a small finite state machine per node",
    },
    {
      num: 6,
      title: "Tree Distances I",
      url: "https://cses.fi/problemset/task/1132",
      source: "CSES",
      difficulty: "hard",
      list: "UG ⭐",
      role: "extension",
      teaches: "**Rerooting introduction** — for each node, find the farthest node in the whole tree. Two DFS passes: (1) post-order computes `down[v]` = deepest descendant distance; (2) pre-order propagates `up[v]` = farthest distance going through the parent, using the top-two `down` values of each node's children to handle the 'exclude the child we are recursing into' case",
    },
    {
      num: 7,
      title: "Sum of Distances in Tree",
      url: "https://leetcode.com/problems/sum-of-distances-in-tree/",
      source: "LC 834",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: recomputing the sum at each root is O(n²). What changes about `ans` when you move the root from `u` to child `v`? Nodes inside `v`'s subtree drop by 1; the rest rise by 1. So `ans[v] = ans[u] + (n − sz[v]) − sz[v]`. First DFS builds `sz` and `ans[root]` bottom-up; second DFS reroots in O(n).",
    },
  ],
};
