import type { Module } from "../types";

export const bitManip: Module = {
  id: "bit-manip",
  num: 30,
  name: "Bit Manipulation",
  section: "2c",
  track: "both",
  order: 30,
  prereqIds: ["foundations"],
  isUtility: true,
  resources: [
    { title: "CPH Book Ch. 10 — Bit Manipulation", url: "https://cses.fi/book/book.pdf" },
    { title: "CP-Algorithms — Submask Enumeration", url: "https://cp-algorithms.com/algebra/all-submasks.html" },
    { title: "USACO Guide — Bitmask DP (Gold)", url: "https://usaco.guide/gold/dp-bitmasks" },
    { title: "LC 191 Editorial — Number of 1 Bits", url: "https://leetcode.com/problems/number-of-1-bits/editorial/" },
  ],
  problems: [
    {
      num: 1,
      title: "Number of 1 Bits",
      url: "https://leetcode.com/problems/number-of-1-bits/",
      source: "LC 191",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "The two core bit tricks of the module — `x & (x - 1)` clears the lowest set bit (Brian Kernighan), and `x & -x` isolates it. Counting set bits via `while (x) { x &= x - 1; count++; }` runs in O(popcount) rather than O(word size)",
    },
    {
      num: 2,
      title: "Counting Bits",
      url: "https://leetcode.com/problems/counting-bits/",
      source: "LC 338",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Bit-by-bit DP — `dp[i] = dp[i >> 1] + (i & 1)` reuses the popcount of `i` with its low bit stripped. First time we treat bit operations as a recurrence rather than a one-shot trick",
    },
    {
      num: 3,
      title: "Missing Number",
      url: "https://leetcode.com/problems/missing-number/",
      source: "LC 268",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "XOR identity — `a ^ a = 0` and `a ^ 0 = a`, so XOR-ing `[0..n]` with the array cancels every present value and leaves the missing one. The canonical \"pair cancellation\" trick that reappears in problems 4 and 7",
    },
    {
      num: 4,
      title: "Single Number",
      url: "https://leetcode.com/problems/single-number/",
      source: "LC 136",
      difficulty: "easy",
      list: "new",
      role: "extension",
      teaches: "Same XOR cancellation as LC 268 but without the index trick — XOR every element and duplicates pair off to 0, leaving the unique value. O(1) space where a hash set would need O(n)",
    },
    {
      num: 5,
      title: "Reverse Bits",
      url: "https://leetcode.com/problems/reverse-bits/",
      source: "LC 190",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Bit-shift arithmetic — extract the low bit with `n & 1`, accumulate into `result = (result << 1) | bit`, then `n >>= 1`. The shift-and-OR build pattern that also powers binary-to-int parsing",
    },
    {
      num: 6,
      title: "Sum of Two Integers",
      url: "https://leetcode.com/problems/sum-of-two-integers/",
      source: "LC 371",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Addition without `+` — `a ^ b` is the sum without carry, `(a & b) << 1` is the carry; loop until the carry is 0. Forces explicit reasoning about how the ALU actually adds, and surfaces signed-overflow masking in Python",
    },
    {
      num: 7,
      title: "Single Number III",
      url: "https://leetcode.com/problems/single-number-iii/",
      source: "LC 260",
      difficulty: "medium",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: XOR-the-array gives `a ^ b`, but you need `a` and `b` separately. What primitive splits one bit-set into a partition of the input? Problem 1's `x & -x` (lowest set bit). XOR all to get `a ^ b`, isolate a 1-bit, partition on that bit, XOR each group. The bit-isolation also seeds submask enumeration in module 31.",
    },
  ],
};
