import type { Module } from "../types";

export const bitManip: Module = {
  id: "bit-manip",
  num: 5,
  name: "Bit Manipulation",
  section: "1a",
  tier: "core",
  order: 5,
  prereqIds: ["foundations"],
  isUtility: true,
  resources: [
    { title: "CPH Book Ch. 10 — Bit Manipulation", url: "https://cses.fi/book/book.pdf" },
    { title: "CP-Algorithms — Submask Enumeration", url: "https://cp-algorithms.com/algebra/all-submasks.html" },
    { title: "USACO Guide — Bitmask DP (Gold)", url: "https://usaco.guide/gold/dp-bitmasks" },
    { title: "LC 191 Editorial — Number of 1 Bits", url: "https://leetcode.com/problems/number-of-1-bits/editorial/" },
  ],
  problems: [
    {
      num: 1,
      title: "Number of 1 Bits",
      url: "https://leetcode.com/problems/number-of-1-bits/",
      source: "LC 191",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "The two core bit tricks of the module — `x & (x - 1)` clears the lowest set bit (Brian Kernighan), and `x & -x` isolates it. Counting set bits via `while (x) { x &= x - 1; count++; }` runs in O(popcount) rather than O(word size)",
    },
    {
      num: 2,
      title: "Counting Bits",
      url: "https://leetcode.com/problems/counting-bits/",
      source: "LC 338",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Bit-by-bit DP — `dp[i] = dp[i >> 1] + (i & 1)` reuses the popcount of `i` with its low bit stripped. First time we treat bit operations as a recurrence rather than a one-shot trick",
    },
    {
      num: 3,
      title: "Single Number",
      url: "https://leetcode.com/problems/single-number/",
      source: "LC 136",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "**XOR pair cancellation** — `a ^ a = 0` and `a ^ 0 = a`, so XOR-ing the whole array leaves only the element appearing once. The canonical \"pair cancellation\" primitive, asked at every FAANG; reappears verbatim in problems 4 and 7",
    },
    {
      num: 4,
      title: "Missing Number",
      url: "https://leetcode.com/problems/missing-number/",
      source: "LC 268",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Same XOR-pair-cancellation as problem 3, but the \"pairs\" are *constructed* — XOR `[0..n]` against the array so every present value cancels with its index-twin, leaving the missing one. First time we synthesise a second sequence to force pair cancellation; the sum-formula alternative `n(n+1)/2 − sum(arr)` is the arithmetic dual",
    },
    {
      num: 5,
      title: "Single Number II",
      url: "https://leetcode.com/problems/single-number-ii/",
      source: "LC 137",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Bit counts mod 3 — every other number appears 3 times; for each bit position, the count of 1-bits across the array is `≡ 1 (mod 3)` iff the unique number has that bit set. Solve via two accumulator variables encoding a 3-state machine (ones, twos) updated with bitwise ops. Distinct from problem 3's XOR-pair-cancellation: pair cancellation can't help when count is 3.",
    },
    {
      num: 6,
      title: "Reverse Bits",
      url: "https://leetcode.com/problems/reverse-bits/",
      source: "LC 190",
      difficulty: "easy",
      list: "NC150",
      role: "extension",
      teaches: "Bit-shift arithmetic — extract the low bit with `n & 1`, accumulate into `result = (result << 1) | bit`, then `n >>= 1`. The shift-and-OR build pattern that also powers binary-to-int parsing",
    },
    {
      num: 7,
      title: "Sum of Two Integers",
      url: "https://leetcode.com/problems/sum-of-two-integers/",
      source: "LC 371",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Addition without `+` — `a ^ b` is the sum without carry, `(a & b) << 1` is the carry; loop until the carry is 0. Forces explicit reasoning about how the ALU actually adds, and surfaces signed-overflow masking in Python",
    },
    {
      num: 8,
      title: "Single Number III",
      url: "https://leetcode.com/problems/single-number-iii/",
      source: "LC 260",
      difficulty: "medium",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: XOR-the-array gives `a ^ b`, but you need `a` and `b` separately. What primitive splits one bit-set into a partition of the input? Problem 1's `x & -x` (lowest set bit). XOR all to get `a ^ b`, isolate a 1-bit, partition on that bit, XOR each group. The bit-isolation also seeds submask enumeration in module 31.",
    },
  ],
};
