import type { Module } from "../types";

// Tier: faang-plus. Bitmask DP is the standard tool whenever the state space
// is "which subset of n <= ~20 items have I committed to so far?" — TSP-style
// tours, assignment/partition, subset cover with constraints, and small-grid
// row-by-row DP. Common Meta/Google hard (LC 847, 943, 1494, 1659).
export const bitmaskDp: Module = {
  id: "bitmask-dp",
  num: 33,
  name: "Bitmask DP",
  section: "2e",
  tier: "faang-plus",
  order: 33,
  prereqIds: ["dp-intro", "bit-manip"],
  isNew: true,
  resources: [
    { title: "CPH Book Ch. 10 — Bit manipulation & Ch. 19 — DP over subsets", url: "https://cses.fi/book/book.pdf" },
    { title: "CP-Algorithms — DP on subsets (SOS DP)", url: "https://cp-algorithms.com/dynamic_programming/profile-dynamics.html" },
    { title: "USACO Guide — Bitmask DP (Gold)", url: "https://usaco.guide/gold/dp-bitmasks" },
  ],
  problems: [
    {
      num: 1,
      title: "Hamiltonian Flights",
      url: "https://cses.fi/problemset/task/1690",
      source: "CSES",
      difficulty: "medium",
      list: "UG ⭐",
      role: "baseline",
      teaches: "**The canonical bitmask DP template.** `dp[mask][v]` = number of paths that visit exactly the set `mask` of cities and end at `v`. Transition: for each edge `u -> v` with `u in mask` and `v not in mask`, add `dp[mask][u]` to `dp[mask | (1<<v)][v]`. Final answer sums `dp[(1<<n)-1][n-1]`. This is the TSP / Held–Karp skeleton — O(2^n · n^2) time, O(2^n · n) state — that every later problem specialises. Your Step 1 problem.",
    },
    {
      num: 2,
      title: "Beautiful Arrangement",
      url: "https://leetcode.com/problems/beautiful-arrangement/",
      source: "LC 526",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Assignment-style bitmask DP** — `dp[mask] = # ways to place the first popcount(mask) positions using exactly the numbers in `mask``. The position is implicit (it equals `popcount(mask)`), so the state collapses from `dp[mask][pos]` to `dp[mask]`. The trick — *position = popcount(mask)* — recurs in problems 6 and 9 and is the single most important state-compression idiom in this module.",
    },
    {
      num: 3,
      title: "Partition to K Equal Sum Subsets",
      url: "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/",
      source: "LC 698",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Bitmask DP as an alternative to backtracking** — module 13 solved this by bucket-filling with pruning. Here: `dp[mask] = current sum mod target` over all subsets reachable by adding one element at a time, valid only when the running sum never exceeds `target`. O(2^n · n) — beats the exponential-worst-case backtracker when `n <= 16`. Forces the *reframe*: a partition problem is a sequence of subset-builds, each crossing a `target` boundary.",
    },
    {
      num: 4,
      title: "Shortest Path Visiting All Nodes",
      url: "https://leetcode.com/problems/shortest-path-visiting-all-nodes/",
      source: "LC 847",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**BFS over (node, mask) states** — the unweighted-TSP variant. State is `(v, mask)`; transition pushes `(u, mask | (1<<u))` for every neighbour `u`. BFS guarantees the first time you pop a state with `mask == (1<<n)-1` is the optimum. Revisiting *nodes* is allowed but revisiting *states* is not — the mask captures everything that matters. FAANG-canonical (Meta on-site staple).",
    },
    {
      num: 5,
      title: "Parallel Courses II",
      url: "https://leetcode.com/problems/parallel-courses-ii/",
      source: "LC 1494",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**Prereq-mask DP with a capacity constraint.** `dp[taken] = min semesters to reach this set`. From `taken`, compute `available = courses whose prereq mask is a subset of taken`, then enumerate every subset of `available` of size `<= k` (the `for s = avail; s; s = (s-1) & avail` subset-iteration trick) and relax `dp[taken | s] = dp[taken] + 1`. Combines SOS-style subset enumeration with a topological feasibility check — harder Meta-flavoured DP.",
    },
    {
      num: 6,
      title: "Maximum Students Taking Exam",
      url: "https://leetcode.com/problems/maximum-students-taking-exam/",
      source: "LC 1349",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**Row-by-row profile DP.** `dp[row][mask]` = max students seated through `row` with `mask` describing which seats in that row are occupied. A mask is valid when no two bits are adjacent and every set bit lands on a non-broken seat. Transition forbids diagonal cheating between `prev_mask` and `mask`. The 2D-grid → 1D-mask compression is the prototype for any narrow-grid problem (width `<= 10`); same shape powers LC 1659 in the checkpoint.",
    },
    {
      num: 7,
      title: "Minimum Number of Work Sessions to Finish the Tasks",
      url: "https://leetcode.com/problems/minimum-number-of-work-sessions-to-finish-the-tasks/",
      source: "LC 1986",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Subset DP with a capacity dimension** — `dp[mask] = (sessions_used, time_in_current_session)` minimised lexicographically. Adding task `i` either fits in the current session (`time + t[i] <= sessionTime`) or opens a new session. The two-component objective is the new wrinkle: the obvious `dp[mask] = min sessions` loses information about the partially-filled session and gives wrong answers. Teaches when a scalar state isn't enough.",
    },
    {
      num: 8,
      title: "Find the Shortest Superstring",
      url: "https://leetcode.com/problems/find-the-shortest-superstring/",
      source: "LC 943",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**TSP on a string-overlap graph.** Precompute `overlap[i][j]` = max suffix-of-`words[i]` that's a prefix-of-`words[j]`; then run Held–Karp with edge weight `len(words[j]) - overlap[i][j]`. Reconstruct the path by storing a `parent[mask][v]` pointer. Two new skills on top of problem 1: (a) building the weight matrix from a string-processing subproblem, (b) path reconstruction from the DP table.",
    },
    {
      num: 9,
      title: "Unique Paths III",
      url: "https://leetcode.com/problems/unique-paths-iii/",
      source: "LC 980",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**Bitmask over grid cells** — when the obstacle-free cell count is `<= 20`, label each walkable cell with a bit and use `visited_mask` as state. DFS from `start` with `(r, c, mask)`; count paths reaching `end` with `mask == full`. Memoisation on `(r, c, mask)` is optional (paths are usually few) but the framing matters: the moment grid + visited-set fits in a 32-bit int, you switch from backtracking-with-set to bitmask DP.",
    },
    {
      num: 10,
      title: "Maximize Grid Happiness",
      url: "https://leetcode.com/problems/maximize-grid-happiness/",
      source: "LC 1659",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: problem 6 carried one row's occupancy in a single mask. Here each cell holds *introvert*, *extrovert*, or *empty* — three states per cell — and the score depends on both vertical (previous row) *and* horizontal (previous cell in same row) neighbours. What does the mask have to remember, and which two earlier ideas combine? Profile DP with a base-3 mask of the last `n` cells (rolling window across rows) plus remaining-introvert / remaining-extrovert counters. Score updates incrementally as each cell is placed. Synthesises problems 6 (profile DP) and 7 (multi-component capacity state) — a true Google-hard.",
    },
  ],
};
