import type { Module } from "../types";

// Tier: faang-plus. Interval DP is the technique whenever the subproblem is
// "best/cost over a contiguous range [l..r], decided by choosing a split point
// or a 'last action' inside the range." Canonical FAANG hards: LC 312 Burst
// Balloons, LC 1000 Merge Stones, LC 664 Strange Printer.
export const intervalDp: Module = {
  id: "interval-dp",
  num: 34,
  name: "Interval DP",
  section: "2e",
  tier: "faang-plus",
  order: 34,
  prereqIds: ["dp-intro"],
  isNew: true,
  resources: [
    { title: "CPH Book Ch. 7.4 — Interval problems", url: "https://cses.fi/book/book.pdf" },
    { title: "USACO Guide — Range DP (Gold)", url: "https://usaco.guide/gold/dp-ranges" },
    { title: "CP-Algorithms — DP on intervals (optimal BST / matrix chain)", url: "https://cp-algorithms.com/dynamic_programming/divide-and-conquer-dp.html" },
  ],
  problems: [
    {
      num: 1,
      title: "Minimum Cost to Cut a Stick",
      url: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
      source: "LC 1547",
      difficulty: "hard",
      list: "new",
      role: "baseline",
      teaches: "**The cleanest interval-DP intro.** Sort cut positions, sentinel with `0` and `n`. `dp[l][r] = min cost to make every cut strictly between positions l and r`, with transition `dp[l][r] = min over k in (l, r) of dp[l][k] + dp[k][r] + (cuts[r] - cuts[l])`. The transition shape — *pick a split point `k` inside the interval, pay a length-dependent cost, recurse on both halves* — is the matrix-chain / optimal-BST skeleton you'll reuse in every problem below. Fill by increasing `r - l`. Your Step 1 problem.",
    },
    {
      num: 2,
      title: "Burst Balloons",
      url: "https://leetcode.com/problems/burst-balloons/",
      source: "LC 312",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**The \"last action\" reframe** — the iconic FAANG interval DP. The obvious *first* balloon to burst couples both subintervals (its neighbours keep changing); instead let `k` be the *last* balloon burst in `(l, r)`. Then at that moment its neighbours are exactly `l` and `r`, so `dp[l][r] = max over k of dp[l][k] + dp[k][r] + nums[l]*nums[k]*nums[r]`. The decoupling — choose the action that leaves a clean recursion — generalises to LC 664 and LC 1000 below.",
    },
    {
      num: 3,
      title: "Strange Printer",
      url: "https://leetcode.com/problems/strange-printer/",
      source: "LC 664",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**Conditional-skip interval DP.** `dp[l][r] = min turns to print s[l..r]`. Base: `dp[l][l] = 1`. Transition: assume `s[l]` is printed in the same stroke as some later matching character — `dp[l][r] = min over k in (l, r] with s[k]==s[l] of dp[l][k-1] + dp[k+1][r]` (the second piece becomes `dp[l][r-1]` if you fold the `k==r` case). The \"piggyback on a matching endpoint\" trick — saving a stroke when characters align — is a recurring interval-DP move; see LC 1547 vs LC 1000 contrast.",
    },
    {
      num: 4,
      title: "Minimum Score Triangulation of Polygon",
      url: "https://leetcode.com/problems/minimum-score-triangulation-of-polygon/",
      source: "LC 1039",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Geometric framing of interval DP.** `dp[l][r] = min triangulation score of the polygon defined by vertices l..r`. Pick the third vertex `k` of the triangle on edge `(l, r)`: `dp[l][r] = min over k in (l, r) of dp[l][k] + dp[k][r] + v[l]*v[k]*v[r]`. Same transition shape as Burst Balloons but motivated by geometry — triangulation = sequence of last-triangle choices. Drives home that interval DP isn't string-specific; any *divide-by-a-pivot-inside-the-range* problem fits.",
    },
    {
      num: 5,
      title: "Minimum Cost Tree From Leaf Values",
      url: "https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/",
      source: "LC 1130",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Interval DP with a precomputed range-max.** `dp[l][r] = min sum of non-leaf node values over all binary trees whose leaves are arr[l..r]`. Pick the split point `k`: `dp[l][r] = min over k of dp[l][k] + dp[k+1][r] + max(arr[l..k]) * max(arr[k+1..r])`. Precompute `maxRange[l][r]` (or build incrementally) to keep the transition O(1). Bonus: the O(n) monotonic-stack solution is the lesson on *when interval DP is the obvious answer but not the tight one* — useful FAANG follow-up.",
    },
    {
      num: 6,
      title: "Scramble String",
      url: "https://leetcode.com/problems/scramble-string/",
      source: "LC 87",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**Interval DP on two strings simultaneously.** State `dp[i][j][len]` = can `s1[i..i+len)` scramble to `s2[j..j+len)`. Transition: for every split point `k in [1, len)`, check either *no-swap* (`dp[i][j][k] && dp[i+k][j+k][len-k]`) or *swap* (`dp[i][j+len-k][k] && dp[i+k][j][len-k]`). 3D state because both starting indices move independently; the split `k` is the pivot. Prune with a character-count check before recursing — the practical interview answer.",
    },
    {
      num: 7,
      title: "Empty String",
      url: "https://cses.fi/problemset/task/1080",
      source: "CSES",
      difficulty: "hard",
      list: "UG",
      role: "extension",
      teaches: "**Counting interval DP** with binomial-coefficient bookkeeping. Let `dp[l][r]` count erasure orders that empty `s[l..r]` (defined for even-length substrings only). Match `s[l]` with some matching `s[k]` (same char, `k - l` odd) inside: erase the inner block first, then interleave its order with the outer halves — multiply by `C(total_pairs - 1, inner_pairs)` to count interleavings. The interleave-multinomial is the new tool; same *match-an-endpoint-with-an-internal-character* pivot as LC 664.",
    },
    {
      num: 8,
      title: "Minimum Cost to Merge Stones",
      url: "https://leetcode.com/problems/minimum-cost-to-merge-stones/",
      source: "LC 1000",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: in Burst Balloons the pivot was the *last* action, in Cut Stick it was an *interior split point*. Here only `k` piles can merge at once — the split has to land on a boundary where the left side reduces to a number of piles `≡ 1 (mod k-1)`. Why does feasibility (`(n-1) % (k-1) == 0`) need to be checked upfront, and what shape does the transition pivot take? `dp[l][r][p] = min cost to merge stones[l..r] into exactly p piles`. Transitions: `dp[l][r][1] = dp[l][r][k] + sum(l, r)`; `dp[l][r][p] = min over mid of dp[l][mid][1] + dp[mid+1][r][p-1]` with `mid` stepping by `k-1`. Synthesises problem 1 (split-point DP), problem 2 (\"last merge\" framing), and a feasibility / modular-arithmetic constraint — the hardest interval DP on LC.",
    },
  ],
};
