import type { Module } from "../types";

// Tier: faang-plus. Fenwick (BIT) is the highest-ROI advanced data structure
// for FAANG interviews — Google in particular loves the "count inversions /
// count smaller after self" family (LC 315, 327, 493). The structure itself
// is ~10 lines; the interview skill is recognising when a problem reduces to
// "point update + prefix query on values" via coord-comp + offline processing.
export const fenwick: Module = {
  id: "fenwick",
  num: 35,
  name: "Fenwick Tree (BIT)",
  section: "2e",
  tier: "faang-plus",
  order: 35,
  prereqIds: ["prefix-sums", "coord-comp"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Point Update Range Sum (Gold)", url: "https://usaco.guide/gold/PURS" },
    { title: "CP-Algorithms — Fenwick Tree", url: "https://cp-algorithms.com/data_structures/fenwick.html" },
    { title: "LC 315 editorial — Count of Smaller Numbers After Self", url: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/editorial/" },
  ],
  problems: [
    {
      num: 1,
      title: "Range Sum Query - Mutable",
      url: "https://leetcode.com/problems/range-sum-query-mutable/",
      source: "LC 307",
      difficulty: "medium",
      list: "new",
      role: "baseline",
      teaches: "**The canonical FAANG entry-point to BIT.** Point update + prefix sum, both in `O(log n)`, on an array that mutates. Internalise the two-line `update(i, delta)` (climb `i += i & -i`) and `query(i)` (descend `i -= i & -i`) — they're the entire data structure. Range sum `[l, r]` = `query(r) - query(l-1)`. Every problem in this module is a reframing of this primitive.",
    },
    {
      num: 2,
      title: "Dynamic Range Sum Queries",
      url: "https://cses.fi/problemset/task/1648",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "The cleanest possible CSES drill — same operations as LC 307 with `n, q <= 2*10^5` so you *must* hit `O((n+q) log n)`. Use this to verify your template against tight constraints; segment tree here is overkill. Pair-trains your fingers for the two-line update/query.",
    },
    {
      num: 3,
      title: "Count of Smaller Numbers After Self",
      url: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
      source: "LC 315",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**The Google canonical hard.** The reframing: walk right-to-left, and for each `a[i]` ask \"how many *values* less than `a[i]` have I already seen?\" That's a prefix query on a BIT indexed by **value** (after coord-comp). Update is `+1` at `rank(a[i])`. This `BIT-over-values` pattern is the most important Fenwick idea — it dispatches LC 493, LC 327, and every inversion-counting variant.",
    },
    {
      num: 4,
      title: "Reverse Pairs",
      url: "https://leetcode.com/problems/reverse-pairs/",
      source: "LC 493",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "Same right-to-left BIT-over-values pattern as LC 315, but the threshold is `2 * a[j]` instead of `a[j]`. The wrinkle: you must coord-compress over the *union* of `{a[i]}` and `{2 * a[i]}` so the lookup index exists. Merge-sort solves this too, but Fenwick is cleaner and generalises to harder thresholds. Classic 2-Sigma / Google onsite.",
    },
    {
      num: 5,
      title: "Count of Range Sum",
      url: "https://leetcode.com/problems/count-of-range-sum/",
      source: "LC 327",
      difficulty: "hard",
      list: "new",
      role: "combination",
      teaches: "**Three-concept composition.** (1) `sum[l..r] in [lo, hi]` ⟺ `P[r+1] - P[l] in [lo, hi]`, so reduce to prefix sums `P`. (2) For each `P[j]`, count earlier `P[i]` with `P[i] in [P[j]-hi, P[j]-lo]` — a *range* query on values seen so far. (3) Coord-compress `{P[i], P[i]-lo, P[i]-hi}` and run a BIT. Three composed tricks → the synthesis problem that distinguishes candidates who *know* Fenwick from those who *recognise reductions to it*.",
    },
    {
      num: 6,
      title: "Count Number of Teams",
      url: "https://leetcode.com/problems/count-number-of-teams/",
      source: "LC 1395",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "Counting triples `(i < j < k)` with `r[i] < r[j] < r[k]` (or `>`). Naive `O(n^3)` is intended-to-fail; the BIT speedup fixes the middle index `j` and asks \"smaller-on-left × greater-on-right\". Two BITs over values, swept left-to-right and right-to-left. The same template counts ascending k-tuples for any small `k` — the LIS-by-counting pattern.",
    },
    {
      num: 7,
      title: "Queries on a Permutation With Key",
      url: "https://leetcode.com/problems/queries-on-a-permutation-with-key/",
      source: "LC 1409",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**BIT over dynamic positions** rather than values. Reserve indices `[1..m]` for the front (initially empty) and `[m+1..m+n]` for the start; track which positions are occupied with a `+1/-1` BIT. \"Index of value `v`\" = `query(pos[v])`. Move-to-front = clear old position, claim a fresh slot on the left. Same BIT, new framing: **occupancy counts**.",
    },
    {
      num: 8,
      title: "Range Sum Query 2D - Mutable",
      url: "https://leetcode.com/problems/range-sum-query-2d-mutable/",
      source: "LC 308",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**2D Fenwick.** `update(r, c, delta)` climbs both indices independently; `query(r, c)` is the inclusion-exclusion `Q(r2,c2) - Q(r1-1,c2) - Q(r2,c1-1) + Q(r1-1,c1-1)`. Cost `O(log R · log C)` per op — the only practical mutable-2D structure in interview range. Generalises directly to 2D inversion counting and k-NN-style grid queries.",
    },
    {
      num: 9,
      title: "Range Update Queries",
      url: "https://cses.fi/problemset/task/1651",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "**Range update + point query** via the difference-array trick on a BIT: to add `v` on `[l, r]`, do `update(l, +v)` and `update(r+1, -v)`; then `point(i) = query(i)` (prefix sum of deltas). This is the dual of the standard BIT (point update + range query). Recognising which dual you need is the Fenwick interview skill — the data structure barely changes.",
    },
    {
      num: 10,
      title: "Count Good Triplets in an Array",
      url: "https://leetcode.com/problems/count-good-triplets-in-an-array/",
      source: "LC 2179",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: two permutations of `[0..n-1]`; count triples `(x, y, z)` that appear in order in *both*. What does fixing `y` give you? **Synthesis.** Reindex `nums2` by `nums1`'s position (so one becomes the identity), then fix the middle element `y` and count `left = #{x < y appearing before in nums2}` and `right = #{z > y appearing after}`. Both are BIT-over-values sweeps — exactly the LC 1395 template, but the reindexing step is the insight. A clean checkpoint: composes coord-comp, the right-to-left BIT sweep, and the \"fix the middle\" counting trick.",
    },
  ],
};
