import type { Module } from "../types";

// Tier: faang-plus. Segment tree is the "strictly more powerful Fenwick" —
// any associative monoid (max, min, gcd, count-of-X, leftmost-index-with-...)
// plus lazy propagation for range updates. FAANG appearances skew toward
// line-sweep geometry (LC 218, 850) and interval-management (LC 715, 732)
// where Fenwick can't express the query. Lazy propagation is the hardest
// generalisation — composed-lazy (LC 1622) is the ceiling.
export const segTree: Module = {
  id: "seg-tree",
  num: 38,
  name: "Segment Tree",
  section: "2e",
  tier: "faang-plus",
  order: 38,
  prereqIds: ["fenwick"],
  isNew: true,
  resources: [
    { title: "USACO Guide — Point Update Range Sum (Gold, segment tree section)", url: "https://usaco.guide/gold/PURS" },
    { title: "CP-Algorithms — Segment Tree (incl. lazy propagation)", url: "https://cp-algorithms.com/data_structures/segment_tree.html" },
    { title: "USACO Guide — Range Queries with Sweep Line (Plat)", url: "https://usaco.guide/plat/sweep-line" },
  ],
  problems: [
    {
      num: 1,
      title: "Hotel Queries",
      url: "https://cses.fi/problemset/task/1143",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "baseline",
      teaches: "**The perfect intro to segment tree's flexibility over Fenwick.** Maintain `max(free_rooms)` per node; for each group, *descend* the tree to find the **leftmost** index with `max >= need`, then point-update that slot. The descent (`if left.max >= need go left else right`) is a single `O(log n)` walk — Fenwick cannot do this because it can't *navigate* by value. This walk-with-predicate pattern recurs in every \"first index satisfying X\" problem.",
    },
    {
      num: 2,
      title: "Dynamic Range Minimum Queries",
      url: "https://cses.fi/problemset/task/1649",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "Same shape as LC 307 / CSES 1648 but with `min` instead of `sum` — and `min` is **not invertible**, so Fenwick is out. This is the canonical justification for segment tree existing. Internalise the recursive `build / update / query(l, r, node, nl, nr)` template here; you'll reuse it verbatim for every monoid (max, gcd, xor-with-no-inverse-context, etc.).",
    },
    {
      num: 3,
      title: "Range Update Queries",
      url: "https://cses.fi/problemset/task/1651",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "**Lazy propagation, the easy intro.** Range *add* + point query. Store a `lazy[node]` add pending; `push_down` before descending. Note this is the *seg-tree* solution to the same problem the Fenwick module solved via difference array — here we use it as the lazy-prop training-wheels case because point query means no `apply-to-aggregate` step. Sets up problem 4.",
    },
    {
      num: 4,
      title: "Range Updates and Sums",
      url: "https://cses.fi/problemset/task/1735",
      source: "CSES",
      difficulty: "hard",
      list: "UG ⭐",
      role: "combination",
      teaches: "**The canonical lazy-propagation problem.** Two update types (add `v` on `[l,r]`, *set* `v` on `[l,r]`) + range sum query. The hard part is **composing two lazy types**: a pending `set` annihilates a pending `add`; a new `add` on top of a `set` accumulates. Get the `apply(node, lazy)` and `compose(parent_lazy, child_lazy)` rules right and the rest is mechanical. Every advanced seg-tree problem (LC 1622, 2569) is a variant of this composition discipline.",
    },
    {
      num: 5,
      title: "My Calendar III",
      url: "https://leetcode.com/problems/my-calendar-iii/",
      source: "LC 732",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "Track the **maximum concurrent bookings** as intervals stream in. Two clean angles: (a) dynamic seg tree on a compressed coord with range `+1` and global `max`; (b) sorted-map difference array with `O(n)` per query. The seg-tree framing generalises (e.g. \"max overlap during `[t1, t2]`\") whereas the diff-array doesn't. Recognising when the seg-tree generalisation is needed is the interview signal.",
    },
    {
      num: 6,
      title: "Range Module",
      url: "https://leetcode.com/problems/range-module/",
      source: "LC 715",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**Interval cover / unset / query** as a maintained set of disjoint intervals. The seg-tree-with-lazy framing: `cover[l, r] = 1` is a range-set-to-1 with lazy push-down on a dynamically allocated tree (coords up to `10^9`); `remove` is range-set-to-0; `query` is range-all-ones-check. The `sortedcontainers` solution wins in Python but the seg-tree framing is the one Google asks about — \"now make `addRange` return the new length\".",
    },
    {
      num: 7,
      title: "The Skyline Problem",
      url: "https://leetcode.com/problems/the-skyline-problem/",
      source: "LC 218",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**Line sweep + range-max seg tree.** Events at building starts/ends; seg tree over compressed x-coords stores max active height per segment. Sweep, output a keypoint whenever the running max changes. The heap solution is more famous, but the seg-tree variant generalises to LC 850 and is the *only* approach for online skylines. Internalise: \"line sweep gives you the events; seg tree maintains the active aggregate.\"",
    },
    {
      num: 8,
      title: "Rectangle Area II",
      url: "https://leetcode.com/problems/rectangle-area-ii/",
      source: "LC 850",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**Klee's algorithm** — sweep a horizontal line bottom-to-top; at each event toggle a rectangle's x-extent in a seg tree that tracks **total covered length** under non-negative range-add `+1/-1`. The seg-tree node stores `(coverCount, totalLen, coveredLen)` with the classic \"if `coverCount > 0` then `coveredLen = totalLen` else pull from children\" rule. This is *the* line-sweep-meets-seg-tree problem; expect it from Google L5+.",
    },
    {
      num: 9,
      title: "Polynomial Queries",
      url: "https://cses.fi/problemset/task/1736",
      source: "CSES",
      difficulty: "hard",
      list: "UG ⭐",
      role: "extension",
      teaches: "**Lazy with arithmetic progressions.** Range update adds `1, 2, 3, ..., (r-l+1)` to `[l, r]`. Store lazy as `(a, b)` meaning \"add `a + b * (i - segStart)`\"; composition adds coefficient-wise with a shift. The aggregate stored is the sum, so `apply` uses the closed-form `sum_{i=0..len-1} (a + b*i) = a*len + b*len*(len-1)/2`. The exercise: derive `compose` and `apply` carefully — once you've done this, composed-lazy seg trees stop being scary.",
    },
    {
      num: 10,
      title: "Fancy Sequence",
      url: "https://leetcode.com/problems/fancy-sequence/",
      source: "LC 1622",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: each value is hit by a sequence of `+a` and `*b` ops; how do you store the *combined* op as a single lazy? **Composed-lazy synthesis.** Every pending op on a value is `x -> b*x + a` — an affine map. Composition of affines is again affine: `(b2, a2) ∘ (b1, a1) = (b2*b1, b2*a1 + a2)`. Store one `(mul, add)` lazy per node, all arithmetic mod `1e9+7` (and the divide-on-append uses modular inverse via Fermat). The cleanest possible test that you can derive `compose` from scratch — the skill that solves every future variant. (The official one-element-array trick exists but learn the seg-tree solution; it's the transferable one.)",
    },
  ],
};
