import type { Module } from "../types";

// Tier: quant. Modular arithmetic, sieves, GCD/LCM, multiplicative-function
// preprocessing, and Fermat/CRT — the toolkit assumed at Citadel / Jane Street /
// HRT math screens and at every Div2 E that touches `MOD = 1e9+7`. SWE-track
// candidates almost never see Pollard rho or Dirichlet sums in interviews;
// quant-track candidates are expected to derive them at the whiteboard.
export const numberTheory: Module = {
  id: "number-theory",
  num: 40,
  name: "Number Theory",
  section: "2f",
  tier: "quant",
  order: 40,
  prereqIds: ["foundations"],
  isNew: true,
  resources: [
    { title: "CP-Algorithms — Algebra section (modular arithmetic, sieves, GCD, Fermat, CRT)", url: "https://cp-algorithms.com/algebra/" },
    { title: "CPH Book Ch. 21 — Number Theory", url: "https://cses.fi/book/book.pdf" },
    { title: "USACO Guide — Number Theory (Gold)", url: "https://usaco.guide/gold/divisibility" },
    { title: "Mark Joshi — Quant Job Interview Questions and Answers (free excerpt PDF)", url: "https://www.markjoshi.com/RecruitmentExtract.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Exponentiation",
      url: "https://cses.fi/problemset/task/1095",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "**Binary exponentiation** under a modulus — `a^b mod m` in O(log b) by squaring `a` and consuming bits of `b`. Foundational: every modular inverse, every matrix power, every NTT layer downstream calls this primitive. Memorise the 6-line loop; whiteboard it from scratch — Jane Street / HRT will ask",
    },
    {
      num: 2,
      title: "Counting Divisors",
      url: "https://cses.fi/problemset/task/1713",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "extension",
      teaches: "**Sieve of Eratosthenes**, generalised — for each `i <= MAX`, add 1 to `d[j]` for every multiple `j = i, 2i, 3i, ...`. The harmonic sum gives O(N log N) total. The pattern \"precompute a multiplicative function over `[1, N]`\" recurs in problems 3, 5 and 9; this is the cleanest first instance",
    },
    {
      num: 3,
      title: "Common Divisors",
      url: "https://cses.fi/problemset/task/1081",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "**Max-GCD via divisor counting** — flip the question: instead of \"largest `g` dividing two array elements\", scan `g` from MAX down to 1 and check whether `>= 2` array elements are multiples of `g`. The harmonic-sieve pattern from problem 2, now answering an existence query. Citadel screen: \"largest number dividing at least 2 of these N values\"",
    },
    {
      num: 4,
      title: "Exponentiation II",
      url: "https://cses.fi/problemset/task/1712",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "**Fermat's little theorem** — when `p` is prime, `a^(p-1) ≡ 1 (mod p)`, so the *exponent* lives mod `p - 1`, not mod `p`. Compute `a^(b^c mod (p-1)) mod p` via two nested `power` calls. The first time a modulus appears in two different moduli simultaneously — the trap quant interviewers set with `a^a^a mod p`",
    },
    {
      num: 5,
      title: "Prime Multiples",
      url: "https://cses.fi/problemset/task/2185",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "**Inclusion-exclusion over a prime set** — count integers in `[1, n]` divisible by at least one of `k <= 20` primes. Iterate over all `2^k` non-empty subsets, sign by parity of `|S|`, term is `n / prod(S)`. The bitmask-IE skeleton you'll reuse for squarefree counts, Möbius sums, and \"at least one of these events\" probability problems",
    },
    {
      num: 6,
      title: "Smallest Integer Divisible by K",
      url: "https://leetcode.com/problems/smallest-integer-divisible-by-k/",
      source: "LC 1015",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Cycle detection in modular arithmetic** — simulate `r = (10*r + 1) mod k`; if you revisit a residue you'll never reach 0, otherwise the step count is the answer. There are only `k` residues so termination is O(k). The pigeonhole+modular-orbit argument is the proof-flavoured warmup Jane Street uses before asking about Fermat's little theorem",
    },
    {
      num: 7,
      title: "Mirror Reflection",
      url: "https://leetcode.com/problems/mirror-reflection/",
      source: "LC 858",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Unfold the room** — instead of reflecting the laser, reflect the room. The beam becomes a straight line and hits a receptor when `k * q = m * p` for integers `k, m`, i.e. at `lcm(p, q)`. Then `k = lcm/q = p / gcd(p, q)` and `m = q / gcd(p, q)` decide which corner. The \"unfold\" trick reappears in billiard-table and torus problems — Jane Street brain-teaser staple",
    },
    {
      num: 8,
      title: "Sum of Divisors",
      url: "https://cses.fi/problemset/task/1082",
      source: "CSES",
      difficulty: "hard",
      list: "UG",
      role: "extension",
      teaches: "**Dirichlet hyperbola / divisor sum identity** — `sum_{i=1..n} sigma(i) = sum_{d=1..n} d * floor(n/d)`. Then bucket the `floor(n/d)` values: only O(sqrt n) distinct values, each a contiguous range of `d`. O(sqrt n) instead of O(n). The \"sum over `floor(n/d)` blocks\" trick is *the* number-theory speedup; reused in Möbius sums and prime-counting",
    },
    {
      num: 9,
      title: "Christmas Party",
      url: "https://cses.fi/problemset/task/1717",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "checkpoint",
      teaches: "Before reading: count permutations with no fixed point under a prime modulus. What recurrence avoids the O(n!) inclusion-exclusion, and which primitive from problem 1 lets you report the answer mod `1e9+7`? **Derangements** via `!n = (n - 1) * (!(n-1) + !(n-2))`, computed in O(n) with modular arithmetic. Synthesis: combinatorial recurrence (module 38 preview) + modular exponentiation primitive from this module.",
    },
  ],
};
