import type { Module } from "../types";

// Tier: quant. Binomial / multinomial coefficients, Catalan numbers, stars and
// bars, inclusion-exclusion, derangements, factorial number system — the
// counting toolkit assumed at Citadel / Jane Street / HRT brain-teaser rounds.
// SWE candidates see the LC 62 / LC 920 instances; quant candidates are
// expected to recognise the underlying identity and re-derive it.
export const combinatorics: Module = {
  id: "combinatorics",
  num: 41,
  name: "Combinatorics",
  section: "2f",
  tier: "quant",
  order: 41,
  prereqIds: ["foundations"],
  isNew: true,
  resources: [
    { title: "CP-Algorithms — Combinatorics section (binomials, Catalan, stars and bars, IE)", url: "https://cp-algorithms.com/combinatorics/binomial-coefficients.html" },
    { title: "CPH Book Ch. 22 — Combinatorics", url: "https://cses.fi/book/book.pdf" },
    { title: "USACO Guide — Combinatorics (Gold)", url: "https://usaco.guide/gold/combo" },
    { title: "Mark Joshi — Quant Job Interview Questions and Answers (free excerpt PDF)", url: "https://www.markjoshi.com/RecruitmentExtract.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Creating Strings II",
      url: "https://cses.fi/problemset/task/1715",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "**Multinomial coefficient** — number of distinct anagrams is `n! / prod(k_c!)` where `k_c` is the count of letter `c`. Requires modular factorials and modular inverse (Fermat from module 37) for the denominator. The canonical \"arrange with repeats\" template; every later problem in this module assumes the `nCr mod p` precompute lives in your hands",
    },
    {
      num: 2,
      title: "Bracket Sequences I",
      url: "https://cses.fi/problemset/task/2064",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "**Catalan numbers** — number of balanced bracket sequences of length `2n` is `C_n = C(2n, n) / (n + 1)`. Closed form means O(1) per query after factorial precompute. Memorise `C_0 = 1, C_1 = 1, C_2 = 2, C_3 = 5, C_4 = 14` — Jane Street will ask \"how many balanced parentheses with 4 pairs?\" and want 14 on the spot",
    },
    {
      num: 3,
      title: "Bracket Sequences II",
      url: "https://cses.fi/problemset/task/2187",
      source: "CSES",
      difficulty: "hard",
      list: "UG",
      role: "extension",
      teaches: "**Reflection principle** — count completions of a partial bracket sequence with prefix-balance `k` and `m` slots left. Answer is `C(m, (m + k)/2) - C(m, (m + k)/2 + 1)`, the celebrated Andre reflection: subtract paths that touch `-1`. The proof (bijection between bad paths and reflected paths) is the standard quant interview \"prove the Catalan formula\" follow-up",
    },
    {
      num: 4,
      title: "Unique Paths",
      url: "https://leetcode.com/problems/unique-paths/",
      source: "LC 62",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "**DP-vs-combinatorics contrast** — the O(mn) grid DP from module 26 is also `C(m + n - 2, m - 1)` in O(m + n) via factorials. Quant interviewers will accept the DP, then ask \"can you do it without the table?\" — they want the binomial. Same problem, two lenses; the combinatorial lens generalises to lattice paths with diagonal steps (Delannoy, Schroder)",
    },
    {
      num: 5,
      title: "Distributing Apples",
      url: "https://cses.fi/problemset/task/1716",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "**Stars and bars** — ways to write `m` as an ordered sum of `n` non-negative integers is `C(n + m - 1, n - 1)`. The \"place `n - 1` dividers among `n + m - 1` slots\" bijection. Reused in every \"split a quantity across buckets\" interview (Citadel options-pricing screens love it: \"distribute K shares across N accounts\")",
    },
    {
      num: 6,
      title: "Number of Music Playlists",
      url: "https://leetcode.com/problems/number-of-music-playlists/",
      source: "LC 920",
      difficulty: "hard",
      list: "new",
      role: "extension",
      teaches: "**Inclusion-exclusion** for surjections — number of length-`goal` playlists using exactly all `N` songs (with the `K`-gap constraint) is `sum_{i=0..N} (-1)^i * C(N, i) * (N - i)! / (N - i - K)! * ...`. Alternatively a 2D DP `dp[i][j] = # playlists of length i using j distinct songs`. The IE derivation is the Citadel/Jane Street favourite; the DP is the LC-accepted fallback",
    },
    {
      num: 7,
      title: "Christmas Party",
      url: "https://cses.fi/problemset/task/1717",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "**Derangements** — permutations with no fixed point, `!n = (n - 1) * (!(n-1) + !(n-2))`, with `!n / n! -> 1/e`. Jane Street brain-teaser: \"N people swap hats at random — probability no-one gets their own?\" Answer `≈ 1/e ≈ 0.3679`. The same problem appears as module 37's checkpoint (modular-arithmetic flavoured); here you focus on the combinatorial derivation",
    },
    {
      num: 8,
      title: "Minimum Operations to Make String Sorted",
      url: "https://leetcode.com/problems/minimum-number-of-operations-to-make-string-sorted/",
      source: "LC 1830",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: the operation is exactly `prev_permutation`, so the answer is the lexicographic rank of `s` among permutations of its multiset. How does the factorial number system encode that rank, and how do duplicate letters change the multinomial denominator at each position? **Multinomial rank** — for each position, count multisets lexicographically smaller and multiply by `(remaining - 1)! / prod(k_c!)` (problem 1's multinomial, now indexed by position). Synthesis: factorials + modular inverse + multinomial.",
    },
  ],
};
