import type { Module } from "../types";

export const probability: Module = {
  id: "probability",
  num: 39,
  name: "Probability & Expected Value",
  label: "Probability &\nExpected Value",
  section: "2e",
  track: "both",
  order: 39,
  prereqIds: ["combinatorics"],
  isNew: true,
  resources: [
    { title: "Xinfeng Zhou — A Practical Guide to Quantitative Finance Interviews (the green book)", url: "https://www.amazon.com/dp/1438236662" },
    { title: "Mark Joshi — Quant Job Interview Questions and Answers (free excerpt PDF)", url: "https://www.markjoshi.com/RecruitmentExtract.pdf" },
    { title: "USACO Guide — Intro to Probability (Plat)", url: "https://usaco.guide/plat/intro-prob" },
    { title: "CPH Book Ch. 25 — Probability", url: "https://cses.fi/book/book.pdf" },
  ],
  problems: [
    {
      num: 1,
      title: "Inversion Probability",
      url: "https://cses.fi/problemset/task/1728",
      source: "CSES",
      difficulty: "easy",
      list: "UG",
      role: "baseline",
      teaches: "**Linearity of expectation** — the master tool. `E[total inversions] = sum over pairs (i, j) of P(a_i > a_j)`, even though the pair indicators are *not* independent. Each pair's probability is a closed-form over two uniform ranges. This is the quant interview opener: \"for each potential event, what's its probability of contributing 1?\"",
    },
    {
      num: 2,
      title: "Candy Lottery",
      url: "https://cses.fi/problemset/task/1727",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "`E[max]` via the **tail-sum identity** `E[X] = sum_{k>=1} P(X >= k)`. Compute `P(max < k) = (k/N)^K`, then sum `1 - P(max < k)`. The same identity rewrites any nonneg integer RV as a sum of indicators `1[X >= k]` — linearity in disguise. Common green-book follow-up: \"expected max of K uniform draws\"",
    },
    {
      num: 3,
      title: "Dice Probability",
      url: "https://cses.fi/problemset/task/1725",
      source: "CSES",
      difficulty: "medium",
      list: "UG",
      role: "extension",
      teaches: "**Probability-DP baseline** — `dp[i][s] = P(after i rolls, sum is s)`, transition `dp[i][s] = (1/6) * sum_{d=1..6} dp[i-1][s-d]`. First time the state *is* a probability (not a count). Answer is a range sum on the final row — sets up the windowed transition in LC 837",
    },
    {
      num: 4,
      title: "New 21 Game",
      url: "https://leetcode.com/problems/new-21-game/",
      source: "LC 837",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Probability DP with a sliding window** — `dp[x] = P(reach x)` and the transition is a uniform mixture over the last `W` states, so a running window sum collapses O(NW) → O(N). The absorbing-state trick: once `x >= K` you stop, so `dp[x]` for `x >= K` are leaves contributing only to the final answer. Classic Two Sigma / Citadel interview problem",
    },
    {
      num: 5,
      title: "Soup Servings",
      url: "https://leetcode.com/problems/soup-servings/",
      source: "LC 808",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Recursive expected value** with four equally-likely transitions — `E[f(a,b)] = (1/4) * sum f(a', b')`, the Bellman-equation skeleton you'll write in every random-walk and MDP problem. Tie-handling at the absorbing state (`a <= 0 and b <= 0` contributes 0.5) is the classic edge-case test. The large-N convergence shortcut is a quant favourite",
    },
    {
      num: 6,
      title: "Knight Probability in Chessboard",
      url: "https://leetcode.com/problems/knight-probability-in-chessboard/",
      source: "LC 688",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Bounded random walk** on a 2D Markov chain — `dp[k][r][c] = P(still on board after k moves starting from (r, c))`. Each step is a uniform 1/8 mixture of neighbours; falling off the board is an absorbing state with probability 0. The gambler's-ruin intuition (probability of survival vs. eventual ruin) lives in this template",
    },
    {
      num: 7,
      title: "Linked List Random Node",
      url: "https://leetcode.com/problems/linked-list-random-node/",
      source: "LC 382",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Reservoir sampling** — keep the i-th element with probability `1/i` as you stream. Inductive proof: after `n` items, every item has probability `1/n` of being held. The canonical \"sample 1 from an unknown-length stream\" problem; generalises to `k`-reservoir for HRT/Jump streaming questions",
    },
    {
      num: 8,
      title: "Moving Robots",
      url: "https://cses.fi/problemset/task/1726",
      source: "CSES",
      difficulty: "hard",
      list: "UG",
      role: "extension",
      teaches: "**Linearity over a grid, conditioned on per-robot DP**. `E[empty squares] = sum over squares s of P(s is empty) = sum_s prod_robots (1 - P(robot ends at s))`. Compute each robot's K-step distribution by independent DP, then combine via the linearity decomposition from problem 1. The two ideas (DP + linearity) compose — the synthesis quant interviewers probe for",
    },
    {
      num: 9,
      title: "Probability of a Two Boxes Having The Same Number of Distinct Balls",
      url: "https://leetcode.com/problems/probability-of-a-two-boxes-having-the-same-number-of-distinct-balls/",
      source: "LC 1467",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: \"P(equal distinct | equal totals)\" looks like Bayes. What dispatches the conditional, and what weighting (module 38) turns each split into a count? Conditional as `favourable / total`: enumerate every per-colour split, weight by its multinomial coefficient, accumulate both buckets in parallel. Expand the joint, then divide.",
    },
  ],
};
