import type { Module } from "../types";

export const strings: Module = {
  id: "strings",
  num: 42,
  name: "Strings & Palindromes",
  label: "Strings &\nPalindromes",
  section: "2f",
  track: "both",
  order: 42,
  prereqIds: ["two-pointers", "sliding-window"],
  isNew: true,
  resources: [
    { title: "USACO Guide — String Searching (Gold)", url: "https://usaco.guide/gold/string-search" },
    { title: "CP-Algorithms — String Hashing", url: "https://cp-algorithms.com/string/string-hashing.html" },
    { title: "CPH Book Ch. 26 — String Algorithms", url: "https://cses.fi/book/book.pdf" },
    { title: "LeetCode editorial for LC 5 — Longest Palindromic Substring", url: "https://leetcode.com/problems/longest-palindromic-substring/editorial/" },
  ],
  problems: [
    {
      num: 1,
      title: "Find the Index of the First Occurrence in a String",
      url: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/",
      source: "LC 28",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Substring matching baseline — brute-force `O(n·m)` scan: for each start index `i` in `haystack`, compare `haystack[i:i+m]` against `needle`. The cleanest introduction before KMP / Z-function (deferred); names the problem the module's checkpoint will reuse",
    },
    {
      num: 2,
      title: "Palindromic Substrings",
      url: "https://leetcode.com/problems/palindromic-substrings/",
      source: "LC 647",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "**Expand-around-center** sub-pattern — for each index `i`, expand `(i, i)` for odd-length and `(i, i+1)` for even-length palindromes while `s[l] == s[r]`. Counts every palindrome in `O(n²)` without DP; extends the converging two-pointer from [module 5 LC 125](05-two-pointers.md) into a *diverging* walk",
    },
    {
      num: 3,
      title: "Longest Palindromic Substring",
      url: "https://leetcode.com/problems/longest-palindromic-substring/",
      source: "LC 5",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same expand-around-center skeleton as problem 2, but track the longest interval seen — return `s[best_l:best_r+1]`. Lives here (not in [module 26 DP](26-dp-2d.md)) because the `O(n²)` time / `O(1)` space center-expansion dominates the `O(n²)` time / `O(n²)` space DP recurrence in practice",
    },
    {
      num: 4,
      title: "Valid Palindrome II",
      url: "https://leetcode.com/problems/valid-palindrome-ii/",
      source: "LC 680",
      difficulty: "easy",
      list: "new",
      role: "extension",
      teaches: "**Skip-budget two-pointer** — converge from both ends; on the first mismatch, branch into *two* sub-checks (skip left, or skip right) and return `True` if either resulting interval is a palindrome. Generalises [module 5 LC 125](05-two-pointers.md) by allowing exactly one deletion; the branch-on-mismatch shape recurs in fuzzy-matching problems",
    },
    {
      num: 5,
      title: "Encode and Decode Strings",
      url: "https://leetcode.com/problems/encode-and-decode-strings/",
      source: "LC 271",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "**Length-prefix serialization** — encode each string as `f\"{len(s)}#{s}\"` so the decoder reads digits until `#`, then slices exactly that many characters. Naive delimiters fail because any chosen separator can appear in the payload; the length prefix is *unambiguous*. The only sensible home for this design problem in the roadmap",
    },
    {
      num: 6,
      title: "Rotate String",
      url: "https://leetcode.com/problems/rotate-string/",
      source: "LC 796",
      difficulty: "easy",
      list: "new",
      role: "extension",
      teaches: "**Doubling trick** — `s` is a rotation of `goal` iff `len(s) == len(goal)` and `goal` appears as a substring of `s + s`. Reduces a rotation check to the substring-search primitive from problem 1; the same `s + s` idea reappears in cyclic-array problems and necklace canonicalisation",
    },
    {
      num: 7,
      title: "Shortest Palindrome",
      url: "https://leetcode.com/problems/shortest-palindrome/",
      source: "LC 214",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Find the longest palindromic *prefix* of `s`, then prepend the reverse of the remaining suffix. The clean trick: build `t = s + \"#\" + reverse(s)` and compute its prefix function — the final value is the length of the longest prefix of `s` that is also a suffix of `reverse(s)`, i.e. the longest palindromic prefix. Recombines the substring-matching primitive (problem 1) with palindrome structure (problems 2-4); a brute `O(n²)` solution using problem 1's scan is also accepted and is the recommended first pass",
    },
  ],
};
