import type { Module } from "../types";

export const strings: Module = {
  id: "strings",
  num: 42,
  name: "Strings & Palindromes",
  label: "Strings &\nPalindromes",
  section: "2g",
  tier: "core",
  order: 42,
  prereqIds: ["two-pointers", "sliding-window"],
  isNew: true,
  resources: [
    { title: "USACO Guide — String Searching (Gold)", url: "https://usaco.guide/gold/string-search" },
    { title: "CP-Algorithms — String Hashing", url: "https://cp-algorithms.com/string/string-hashing.html" },
    { title: "CPH Book Ch. 26 — String Algorithms", url: "https://cses.fi/book/book.pdf" },
    { title: "LeetCode editorial for LC 5 — Longest Palindromic Substring", url: "https://leetcode.com/problems/longest-palindromic-substring/editorial/" },
  ],
  problems: [
    {
      num: 1,
      title: "Find the Index of the First Occurrence in a String",
      url: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/",
      source: "LC 28",
      difficulty: "easy",
      list: "NC150",
      role: "baseline",
      teaches: "Substring matching baseline — brute-force `O(n·m)` scan: for each start index `i` in `haystack`, compare `haystack[i:i+m]` against `needle`. The cleanest introduction before KMP / Z-function (deferred); names the problem the module's checkpoint will reuse",
    },
    {
      num: 2,
      title: "Palindromic Substrings",
      url: "https://leetcode.com/problems/palindromic-substrings/",
      source: "LC 647",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "**Expand-around-center** sub-pattern — for each index `i`, expand `(i, i)` for odd-length and `(i, i+1)` for even-length palindromes while `s[l] == s[r]`. Counts every palindrome in `O(n²)` without DP; extends the converging two-pointer from [module 5 LC 125](05-two-pointers.md) into a *diverging* walk",
    },
    {
      num: 3,
      title: "Longest Palindromic Substring",
      url: "https://leetcode.com/problems/longest-palindromic-substring/",
      source: "LC 5",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "Same expand-around-center skeleton as problem 2, but track the longest interval seen — return `s[best_l:best_r+1]`. Lives here (not in [module 26 DP](26-dp-2d.md)) because the `O(n²)` time / `O(1)` space center-expansion dominates the `O(n²)` time / `O(n²)` space DP recurrence in practice",
    },
    {
      num: 4,
      title: "Valid Palindrome II",
      url: "https://leetcode.com/problems/valid-palindrome-ii/",
      source: "LC 680",
      difficulty: "easy",
      list: "new",
      role: "extension",
      teaches: "**Skip-budget two-pointer** — converge from both ends; on the first mismatch, branch into *two* sub-checks (skip left, or skip right) and return `True` if either resulting interval is a palindrome. Generalises [module 5 LC 125](05-two-pointers.md) by allowing exactly one deletion; the branch-on-mismatch shape recurs in fuzzy-matching problems. A Meta phone-screen staple",
    },
    {
      num: 5,
      title: "Minimum Remove to Make Valid Parentheses",
      url: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/",
      source: "LC 1249",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Two-pass index-marking** — first pass tracks unmatched `)` positions with a counter; second pass right-to-left removes the unmatched `(`. Cleaner than a stack of indices: each pass only needs an integer plus a `set` of indices to drop. Currently the single most-asked Meta problem; the index-marking idiom recurs in string-cleanup interviews",
    },
    {
      num: 6,
      title: "Reverse Words in a String",
      url: "https://leetcode.com/problems/reverse-words-in-a-string/",
      source: "LC 151",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Split-reverse-join with whitespace normalisation** — the one-liner `' '.join(s.split()[::-1])` is the canonical answer, but interviewers ask for the in-place `O(1)`-extra char-array version: reverse the entire array, then reverse each word in place, then compact. Tests careful index bookkeeping under multiple-space and leading/trailing-space edge cases; a Meta and Microsoft favourite",
    },
    {
      num: 7,
      title: "String to Integer (atoi)",
      url: "https://leetcode.com/problems/string-to-integer-atoi/",
      source: "LC 8",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**State-machine parsing** — four states (leading-space, signed, in-number, done) drive a single linear scan; clamp to `INT_MIN` / `INT_MAX` on every digit accumulation, not at the end, to dodge overflow. The canonical \"messy spec\" interview problem — the algorithm is trivial; the grade is on how cleanly you enumerate the edge cases (Google, Meta, Amazon staple)",
    },
    {
      num: 8,
      title: "Rotate String",
      url: "https://leetcode.com/problems/rotate-string/",
      source: "LC 796",
      difficulty: "easy",
      list: "new",
      role: "extension",
      teaches: "**Doubling trick** — `s` is a rotation of `goal` iff `len(s) == len(goal)` and `goal` appears as a substring of `s + s`. Reduces a rotation check to the substring-search primitive from problem 1; the same `s + s` idea reappears in cyclic-array problems and necklace canonicalisation",
    },
    {
      num: 9,
      title: "Shortest Palindrome",
      url: "https://leetcode.com/problems/shortest-palindrome/",
      source: "LC 214",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: the answer prepends `reverse(suffix)` to `s` — the real task is the longest palindromic *prefix* of `s`. What earlier problem reframes that as a prefix-function on what concatenation? Problem 1's KMP. Compute the prefix function of `t = s + \"#\" + reverse(s)`; the final value is the answer. Problem 1's brute scan also passes.",
    },
  ],
};
