import type { Module } from "../types";

export const design: Module = {
  id: "design",
  num: 43,
  name: "Design & OOD",
  section: "2h",
  track: "interview",
  order: 43,
  prereqIds: ["arrays-hashing", "linked-list", "heap"],
  isNew: true,
  resources: [
    { title: "Tech Interview Handbook — Algorithms / Design questions", url: "https://www.techinterviewhandbook.org/algorithms/study-cheatsheet/" },
    { title: "NeetCode — Design playlist (YouTube)", url: "https://www.youtube.com/playlist?list=PLot-Xpze53lcvx_tjrr_m2lgD7CktSe5y" },
    { title: "LeetCode editorial for LC 146 — LRU Cache", url: "https://leetcode.com/problems/lru-cache/editorial/" },
    { title: "LeetCode editorial for LC 460 — LFU Cache", url: "https://leetcode.com/problems/lfu-cache/editorial/" },
  ],
  problems: [
    {
      num: 1,
      title: "Logger Rate Limiter",
      url: "https://leetcode.com/problems/logger-rate-limiter/",
      source: "LC 359",
      difficulty: "easy",
      list: "new",
      role: "baseline",
      teaches: "**Hashmap of message → last-printed timestamp** — on each call, accept iff `timestamp - last[msg] >= 10` (or `msg` unseen), then update. The simplest \"design with state\" — names the API-with-stateful-store shape every later problem in this module elaborates on; a Google phone-screen favourite",
    },
    {
      num: 2,
      title: "Insert Delete GetRandom O(1)",
      url: "https://leetcode.com/problems/insert-delete-getrandom-o1/",
      source: "LC 380",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "**Hashmap + dynamic array with swap-to-end** — `vals` stores items contiguously, `idx[val]` maps value → its index in `vals`. Delete swaps the target with the last element and pops, keeping `vals` dense so `getRandom` is a single `vals[randint(0, n-1)]`. The idiom that turns an unordered set into an O(1)-random-access container",
    },
    {
      num: 3,
      title: "LRU Cache",
      url: "https://leetcode.com/problems/lru-cache/",
      source: "LC 146",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "**Hashmap → DLL-node pointer for O(1) move-to-front** — keys map to nodes in a doubly linked list ordered most-recent-at-head. `get` re-links the node to the head; `put` evicts the tail when over capacity. Sentinel head/tail nodes remove every edge case. The canonical interview design problem and the template the next three problems compose against",
    },
    {
      num: 4,
      title: "Design Twitter",
      url: "https://leetcode.com/problems/design-twitter/",
      source: "LC 355",
      difficulty: "medium",
      list: "NC150",
      role: "combination",
      teaches: "**Per-user tweet list + heap-merge for the feed** — store each user's tweets as a list of `(timestamp, tweetId)` and follows as a set. `getNewsFeed(u)` runs a merge-K-sorted over `u`'s own list plus each followee's list using a max-heap keyed by timestamp — the [module 16 LC 23](16-heap.md) primitive reused in a design wrapper. The hashmap + heap composition is the module's signature combination",
    },
    {
      num: 5,
      title: "Design Underground System",
      url: "https://leetcode.com/problems/design-underground-system/",
      source: "LC 1396",
      difficulty: "medium",
      list: "new",
      role: "extension",
      teaches: "**Two-hashmap aggregation** — `inflight[id] = (startStation, startTime)` tracks check-ins; `totals[(from, to)] = (sumDuration, count)` accumulates completed trips. `getAverageTime` reads from `totals` in O(1). The pattern: split a stream of events into an \"open\" map and a \"finalized\" map keyed by the aggregation tuple",
    },
    {
      num: 6,
      title: "Random Pick with Weight",
      url: "https://leetcode.com/problems/random-pick-with-weight/",
      source: "LC 528",
      difficulty: "medium",
      list: "NC150",
      role: "extension",
      teaches: "**Prefix sums + binary search** — build `pref[i] = w[0] + ... + w[i]` once; on `pickIndex`, draw `r` uniformly from `[1, pref[-1]]` and return `bisect_left(pref, r)`. Reframes [module 4](04-prefix-sums.md) and [module 11](11-binary-search.md) primitives as a constructor-plus-method design; the only problem in the roadmap that asks you to *justify* a sampling distribution",
    },
    {
      num: 7,
      title: "LFU Cache",
      url: "https://leetcode.com/problems/lfu-cache/",
      source: "LC 460",
      difficulty: "hard",
      list: "NC150",
      role: "extension",
      teaches: "**LRU plus a second hashmap mapping frequency → ordered set of keys at that frequency, plus a `min_freq` tracker** — `get`/`put` bump a key's frequency, moving it from `freq[f]` to `freq[f+1]`. Eviction pops the least-recently-used key from `freq[min_freq]`. Maintaining `min_freq` correctly on insert (reset to 1) and on bump (increment only when the old `freq[min_freq]` empties) is the bug surface — this is what makes it Hard relative to problem 3",
    },
    {
      num: 8,
      title: "Design In-Memory File System",
      url: "https://leetcode.com/problems/design-in-memory-file-system/",
      source: "LC 588",
      difficulty: "hard",
      list: "new",
      role: "checkpoint",
      teaches: "Before reading: paths share prefixes; lookups proceed one component at a time. Which [module 15](15-tries.md) structure fits? A trie of path components — each node holds either a dict of children (directory) or a string buffer (file). `ls`, `mkdir`, and `addContentToFile` all walk the trie then act at the leaf.",
    },
  ],
};
