import type { LabProblem } from "./types";

// Prediction-calibration drills (kind === "estimation"). These are NOT
// algorithmic problems — they are 5-minute reasoning exercises that train
// Fermi decomposition, complexity intuition, and probability-under-uncertainty.
// Curated by Agent J. Three sub-families:
//   1) Fermi (order-of-magnitude reasoning)
//   2) Algorithm complexity prediction
//   3) Probability / expected value
// Every problem must have:
//   - kind: "estimation"
//   - requiredModules: []  (no algorithmic prereqs gate these)
//   - answer + answerType populated (the calibration UI auto-checks)
//   - insightTags with >= 1 tag
export const PROBLEMS_ESTIMATION: LabProblem[] = [
  // ════════════════════════════════════════════════════════════════════════
  // 1) Fermi estimation — order-of-magnitude reasoning
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "fermi-piano-tuners-chicago",
    source: "fermi",
    url: "https://en.wikipedia.org/wiki/Fermi_problem#Examples",
    title: "How many piano tuners are there in Chicago?",
    estMinutes: 5,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "For Fermi: decompose into 3-5 independent factors you can each estimate to within 1 order of magnitude (population × pianos-per-household × tunings-per-piano-per-year ÷ tunings-per-tuner-per-year). Multiplying ~unbiased estimates lets errors partially cancel.",
    stuckHints: [
      "What's the population, and what fraction of households own a piano?",
      "How often does a piano need tuning? How long does one tuning take?",
      "What's a tuner's workload in a year (hours × pianos/hour)?",
    ],
    insightTags: ["fermi-decomposition", "order-of-magnitude"],
    answer: "~100 (between 30 and 300)",
    answerType: "numeric",
    acceptableTolerance: 0.5,
  },
  {
    id: "fermi-cells-human-body",
    source: "fermi",
    url: "https://en.wikipedia.org/wiki/Cell_(biology)#Number_of_cells_in_the_human_body",
    title: "How many cells are in a human body?",
    estMinutes: 4,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "Body mass (~70 kg = 7×10^4 g) divided by mass-per-cell. A typical animal cell is ~10 μm wide, so volume ≈ 10^-9 cm^3 and mass ≈ 10^-9 g. Result: ~10^14. The trick is knowing one biological constant (cell size) and converting units cleanly.",
    stuckHints: [
      "What's a cell's diameter in microns? Cube it to get a volume.",
      "Assume cell density ≈ water density (~1 g/cm^3).",
      "Body mass / mass-per-cell. Watch your unit conversions.",
    ],
    insightTags: ["fermi-decomposition", "order-of-magnitude", "unit-conversion"],
    answer: "~10^13 to 10^14",
    answerType: "numeric",
    acceptableTolerance: 0.5,
  },
  {
    id: "fermi-dna-total-length",
    source: "fermi",
    url: "https://hypertextbook.com/facts/1998/StevenChen.shtml",
    title: "Total length of all DNA strands in your body, end-to-end?",
    estMinutes: 5,
    kind: "estimation",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    canonicalInsight:
      "Chain two known order-of-magnitudes: ~10^14 cells × ~2 m of DNA per cell = ~2×10^14 m. Comparing to known reference distances (Earth-Sun = 1.5×10^11 m) makes the answer memorable: the strand could reach the sun and back ~600+ times.",
    stuckHints: [
      "How many cells in a body? (See prior Fermi.) How much DNA per nucleus?",
      "Length of human genome (3×10^9 bp) × spacing (~0.34 nm/bp) ≈ 1 m per haploid set.",
      "Multiply per-cell length by cell count. Then convert to something familiar (Earth-Sun distance).",
    ],
    insightTags: ["fermi-decomposition", "order-of-magnitude", "chained-estimates"],
    answer: "~10^14 m (≈ 100x to 1000x Earth-Sun distance)",
    answerType: "numeric",
    acceptableTolerance: 0.5,
  },
  {
    id: "fermi-music-recorded",
    source: "fermi",
    url: "https://what-if.xkcd.com/166/",
    title: "How many minutes of music has humanity recorded?",
    estMinutes: 6,
    kind: "estimation",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    canonicalInsight:
      "Decompose by population × songs-per-person-uploaded × duration. ~10^9 users on streaming/upload platforms × ~10 uploaded tracks/user × ~4 min/track ≈ 4×10^10 minutes ≈ 80,000 years. Cross-check with industry numbers (Spotify ~100M tracks × 4 min = 4×10^8 min, much less, because user uploads dominate).",
    stuckHints: [
      "Two sources: commercial recordings (catalog) vs user uploads (YouTube, SoundCloud).",
      "Estimate each independently and add. Which dominates by orders of magnitude?",
      "What's the upper bound? (Population × lifetime × 24h/day = strict ceiling.)",
    ],
    insightTags: ["fermi-decomposition", "upper-bound-sanity-check"],
    answer: "~10^10 to 10^11 minutes (tens of thousands of years)",
    answerType: "numeric",
    acceptableTolerance: 0.5,
  },
  {
    id: "fermi-internet-energy-per-day",
    source: "fermi",
    url: "https://www.iea.org/energy-system/buildings/data-centres-and-data-transmission-networks",
    title: "How much energy does the internet consume in a day?",
    estMinutes: 6,
    kind: "estimation",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    canonicalInsight:
      "Three independent components: data centers (~300 TWh/yr) + transmission networks (~300 TWh/yr) + end-user devices share (~200 TWh/yr) ≈ 800 TWh/yr ≈ 2 TWh/day ≈ 7×10^15 J/day. Decomposition: total = sum of subsystems, each one a power × time product. Sanity check vs world power consumption (~25,000 TWh/yr).",
    stuckHints: [
      "Internet = data centers + network transmission + end devices. Estimate each.",
      "Global electricity ~25,000 TWh/yr. What fraction is plausibly 'internet'?",
      "Power (watts) × time (seconds) = energy (joules). Convert at the end, not in the middle.",
    ],
    insightTags: ["fermi-decomposition", "sum-of-subsystems", "order-of-magnitude"],
    answer: "~2 TWh/day (≈ 7×10^15 J/day)",
    answerType: "numeric",
    acceptableTolerance: 0.5,
  },
  {
    id: "fermi-golf-balls-747",
    source: "fermi",
    url: "https://www.glassdoor.com/Interview/Fermi-estimation-questions-i-e-how-many-golf-balls-fit-into-a-Boeing-747-etc-QTN_2433785.htm",
    title: "How many golf balls fit inside a Boeing 747?",
    estMinutes: 5,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "Volume-ratio Fermi: cabin volume ≈ cylinder (radius 3 m, length 60 m) ≈ 1700 m^3 = 1.7×10^9 cm^3. Golf ball ≈ 4 cm diameter → volume ≈ 33 cm^3. Naive ratio ≈ 5×10^7; apply ~0.7 packing efficiency → ~3×10^7. Frame the question: does it include seats? With seats removed, ~3×10^7; with seats, ~10^7.",
    stuckHints: [
      "Approximate the cabin as a cylinder. What are its rough dimensions?",
      "Single golf ball volume (cm^3)? Don't forget packing efficiency (~64-74%).",
      "Clarify the prompt — empty cabin? Cargo hold included? State your assumption.",
    ],
    insightTags: ["fermi-decomposition", "volume-ratio", "packing-density"],
    answer: "~10^7 (between 10 million and 40 million depending on assumptions)",
    answerType: "numeric",
    acceptableTolerance: 0.5,
  },
  {
    id: "fermi-mms-swimming-pool",
    source: "fermi",
    url: "https://www.prweb.com/releases/how_many_m_ms_fill_an_olympic_size_swimming_pool_/prweb12216653.htm",
    title: "How many M&Ms fit in a standard (Olympic) swimming pool?",
    estMinutes: 5,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "Same volume-ratio frame as the 747. Pool volume = 50 × 25 × 2 = 2500 m^3 = 2.5×10^9 cm^3. M&M volume ≈ 0.6 cm^3 (oblate spheroid). Naive ratio ≈ 4×10^9; with packing efficiency ~0.65 → ~2.5×10^9. Reusable pattern: any 'how many X fit in Y' is volume(Y) × packing / volume(X).",
    stuckHints: [
      "Volume of an Olympic pool? (Hint: 50 m × 25 m × 2 m.)",
      "Volume of one M&M (treat as a flat ellipsoid).",
      "Multiply by packing efficiency (~0.6-0.7 for irregular shapes).",
    ],
    insightTags: ["fermi-decomposition", "volume-ratio", "packing-density"],
    answer: "~2.5×10^9 (≈ 2.4 billion)",
    answerType: "numeric",
    acceptableTolerance: 0.5,
  },

  // ════════════════════════════════════════════════════════════════════════
  // 2) Algorithm complexity prediction
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "complexity-rank-sorts-large-n",
    source: "custom",
    url: "https://en.wikipedia.org/wiki/Sorting_algorithm#Comparison_of_algorithms",
    title: "Rank by speed at n = 10^6: quicksort, mergesort, heapsort, bubble sort",
    estMinutes: 4,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "Dominant-term first: bubble = O(n^2) loses by orders of magnitude at 10^6. Quick/merge/heap are all O(n log n) — separate them by constants and cache behavior: quicksort wins on average (best constants + locality), mergesort next (extra space hurts cache), heapsort last among n log n sorts (poor locality, many swaps).",
    stuckHints: [
      "Group by big-O class first. At n=10^6, does any class lose by 10000x?",
      "Within the same big-O class, what determines constants? (Cache, swaps, branches.)",
      "Which sort allocates O(n) extra memory?",
    ],
    insightTags: ["complexity-dominant-term", "big-o-comparison", "constant-factors"],
    answer: "quicksort, mergesort, heapsort, bubble sort",
    answerType: "ordering",
  },
  {
    id: "complexity-2n-vs-nfact-n20",
    source: "custom",
    url: "https://www.bigocheatsheet.com/",
    title: "For n = 20: which is faster, 2^n DP or n! brute force?",
    estMinutes: 3,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "Plug in: 2^20 ≈ 10^6, 20! ≈ 2.4×10^18. Factorial dwarfs exponential for n ≥ ~5. The 'bitmask DP turns n! into 2^n × n' trick (e.g. held-karp TSP) is the standard answer to 'n ≤ 20 means brute force, right?' — no, it means bitmask DP.",
    stuckHints: [
      "Compute 2^20 and 20! roughly — how many digits each?",
      "When does k! overtake 2^k? (Hint: very early.)",
      "Which one fits in under a second at typical 10^8 ops/sec?",
    ],
    insightTags: ["complexity-dominant-term", "big-o-comparison", "n-le-20-bitmask"],
    answer: "2^n DP (≈ 10^6 ops vs 10^18)",
    answerType: "categorical",
  },
  {
    id: "complexity-runtime-at-n",
    source: "custom",
    // CP reference on input-size → algorithm-budget mapping (distinct from the other bigocheatsheet entry above).
    url: "https://codeforces.com/blog/entry/21344",
    title: "Predict wall-clock runtime: n=10^8 simple loop, n=10^6 nested loop, n=10^4 cubic loop",
    estMinutes: 4,
    kind: "estimation",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    canonicalInsight:
      "Calibrate to a personal constant: a tight inner loop on a modern CPU runs at ~10^8-10^9 simple ops/sec. Then: 10^8 ops = ~1s; 10^6 nested = 10^12 ops = ~10000s (too slow!); 10^4 cubic = 10^12 ops = ~10000s (also too slow!). The lesson: 'cubic on 10^4' and 'quadratic on 10^6' both blow up — n bounds dictate which big-O class you can afford.",
    stuckHints: [
      "What's your assumed ops-per-second? (10^8-10^9 is a safe default.)",
      "Compute total ops for each: n for simple, n^2 for nested, n^3 for cubic.",
      "Divide by ops/sec. Which ones exceed a 1-second budget?",
    ],
    insightTags: ["complexity-dominant-term", "ops-per-second", "n-budget-mapping"],
    answer: "~1s, ~10^4s, ~10^4s (only the first finishes; both others time out)",
    answerType: "ordering",
  },
  {
    id: "complexity-crossover-n",
    source: "custom",
    url: "https://en.wikipedia.org/wiki/Asymptotic_analysis",
    title: "A is O(n^2) with constant 1, B is O(n log n) with constant 5. At what n does B beat A?",
    estMinutes: 4,
    kind: "estimation",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    canonicalInsight:
      "Set 1·n^2 = 5·n log_2 n → n = 5 log_2 n. Try n=20: 5·log_2(20) ≈ 21.6 > 20 → A still wins. Try n=30: 5·log_2(30) ≈ 24.5 < 30 → B wins. Crossover near n ≈ 25. Asymptotic dominance is a SMALL effect until n is past the crossover; for n < 25, the worse big-O class is actually faster.",
    stuckHints: [
      "Write the equation c_A · f_A(n) = c_B · f_B(n) and solve.",
      "Try a few values of n and bracket the crossover.",
      "Constants matter at small n. Big-O wins ONLY past the crossover.",
    ],
    insightTags: ["big-o-comparison", "constant-factors", "asymptotic-crossover"],
    answer: "n ≈ 25 (B wins for n >= 25, loses for n < 25)",
    answerType: "numeric",
    acceptableTolerance: 0.3,
  },
  {
    id: "complexity-recursive-fib-space",
    source: "custom",
    url: "https://en.wikipedia.org/wiki/Fibonacci_sequence#Computation",
    title: "Space complexity of naive recursive Fibonacci (no memoization)?",
    estMinutes: 3,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "Don't confuse TIME (O(φ^n), exponential nodes) with SPACE. Space = max call-stack depth, not total nodes. The deepest path from fib(n) → fib(n-1) → ... → fib(1) has depth n, so space = O(n). General rule: recursive space = depth of the deepest single path, not total recursive calls.",
    stuckHints: [
      "Are you counting nodes in the call tree, or stack depth?",
      "How deep is the deepest single chain of recursive calls?",
      "Time can be exponential while space is linear — they're decoupled.",
    ],
    insightTags: ["complexity-dominant-term", "recursive-stack-depth", "time-space-decoupling"],
    answer: "O(n)",
    answerType: "categorical",
  },
  {
    id: "complexity-quicksort-comparisons-n1000",
    source: "custom",
    url: "https://en.wikipedia.org/wiki/Quicksort#Average-case_analysis",
    title: "Expected # of comparisons for randomized quicksort, n = 1000?",
    estMinutes: 4,
    kind: "estimation",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    canonicalInsight:
      "Closed-form: E[comparisons] ≈ 2n ln(n) ≈ 1.39 · n log_2(n). At n=1000: 1.39 × 1000 × 9.97 ≈ 13,800. Memorize the constant 2 ln 2 ≈ 1.39 — it's the gap between randomized quicksort and the information-theoretic lower bound n log_2 n.",
    stuckHints: [
      "Formula: ~2n ln n. (Derive from harmonic sum of pivot-comparison probabilities.)",
      "log_2(1000) ≈ 10. n log_2 n ≈ 10^4. The constant pushes it ~40% higher.",
      "Express in terms of n log_2 n first, then convert ln ↔ log_2.",
    ],
    insightTags: ["complexity-dominant-term", "randomized-quicksort-constant", "ln-vs-log2"],
    answer: "~1.4 × 10^4 (≈ 13,800)",
    answerType: "numeric",
    acceptableTolerance: 0.3,
  },
  {
    id: "complexity-two-sum-vs-three-sum",
    source: "custom",
    // Wikipedia 3SUM article — distinct from the roadmap's leetcode/3sum entry.
    url: "https://en.wikipedia.org/wiki/3SUM",
    title: "Time complexity: two-sum (hash) vs three-sum (sort + two-pointer)?",
    estMinutes: 3,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "k-sum pattern: optimal is O(n^(k-1)) for k >= 2. Two-sum = O(n) via hash. Three-sum = O(n^2) via fix-one + two-pointer. Four-sum = O(n^3). Each extra summand adds one factor of n. The 'hash trick' only buys you the LAST sum for free; the outer loops are unavoidable.",
    stuckHints: [
      "Two-sum with a hash: scan once, look up complement. What's that?",
      "Three-sum: fix one element, do two-sum on the rest. Outer loop × inner.",
      "Pattern: k-sum is O(n^(k-1)) once you can sort.",
    ],
    insightTags: ["complexity-dominant-term", "k-sum-pattern", "big-o-comparison"],
    answer: "O(n) and O(n^2)",
    answerType: "categorical",
  },

  // ════════════════════════════════════════════════════════════════════════
  // 3) Probability / expected value
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "prob-ev-fair-d6",
    source: "custom",
    url: "https://en.wikipedia.org/wiki/Expected_value#Examples",
    title: "Expected value of one roll of a fair d6?",
    estMinutes: 2,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "EV of uniform {1..n} is (n+1)/2 — the average of the endpoints. For n=6: 3.5. General trick: for any symmetric distribution, EV = midpoint of support.",
    stuckHints: [
      "Average of 1, 2, 3, 4, 5, 6.",
      "Formula for uniform {1..n}: (n+1)/2.",
      "Use symmetry — pair 1 with 6, 2 with 5, 3 with 4.",
    ],
    insightTags: ["expected-value", "uniform-distribution", "symmetry"],
    answer: "3.5",
    answerType: "numeric",
    acceptableTolerance: 0.05,
  },
  {
    id: "prob-at-least-one-6-in-4-rolls",
    source: "custom",
    url: "https://en.wikipedia.org/wiki/Probability#Independence",
    title: "P(at least one 6 in 4 rolls of a fair d6)?",
    estMinutes: 3,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "Complement: P(at least one 6) = 1 - P(no 6 in any of 4) = 1 - (5/6)^4 ≈ 1 - 0.482 ≈ 0.518. The 'at least one' phrasing is a tell — compute the complement of 'none', which factors cleanly under independence.",
    stuckHints: [
      "'At least one' = 1 - 'none'.",
      "P(no 6 on one roll) = 5/6. Roles are independent.",
      "(5/6)^4 ≈ 0.48; subtract from 1.",
    ],
    insightTags: ["complement-trick", "independence", "de-mere-paradox"],
    answer: "≈ 0.518",
    answerType: "numeric",
    acceptableTolerance: 0.1,
  },
  {
    id: "prob-expected-distance-unit-interval",
    source: "custom",
    url: "https://www.landonlehman.com/post/mean-distances-in-uniform-distributions/",
    title: "Two uniform random points in [0,1] — expected distance?",
    estMinutes: 4,
    kind: "estimation",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    canonicalInsight:
      "E[|X - Y|] = 1/3 for X, Y ~ Uniform[0,1] i.i.d. Sanity heuristic: order statistics of 2 uniforms on [0,1] are at positions 1/3 and 2/3 in expectation (n+1 equal segments), so spacing = 1/3.",
    stuckHints: [
      "Compute the double integral ∫∫|x-y| dx dy directly.",
      "Or use order statistics: E[X_(k)] = k/(n+1) for uniform.",
      "Sanity: expected gap when you split [0,1] into 3 equal pieces.",
    ],
    insightTags: ["order-statistics", "uniform-distribution", "expected-value"],
    answer: "1/3 (≈ 0.333)",
    answerType: "numeric",
    acceptableTolerance: 0.1,
  },
  {
    id: "prob-draws-until-ace",
    source: "custom",
    url: "https://en.wikipedia.org/wiki/Geometric_distribution",
    title: "Expected # of draws (with replacement) from a 52-card deck until you draw an ace?",
    estMinutes: 3,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "Geometric distribution: E[draws until success] = 1/p. P(ace) = 4/52 = 1/13, so EV = 13. General rule: any 'wait for first success with probability p per trial' has mean 1/p.",
    stuckHints: [
      "What's P(ace on a single draw)?",
      "Geometric distribution mean = 1/p.",
      "Pattern memo: 'expected trials to first success = 1 / per-trial probability.'",
    ],
    insightTags: ["geometric-distribution", "expected-value"],
    answer: "13",
    answerType: "numeric",
    acceptableTolerance: 0.05,
  },
  {
    id: "prob-birthday-paradox-23",
    source: "custom",
    url: "https://en.wikipedia.org/wiki/Birthday_problem",
    title: "P(at least 2 people share a birthday in a room of 23)?",
    estMinutes: 4,
    kind: "estimation",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    canonicalInsight:
      "Birthday paradox: ~50% at n=23 — counterintuitive because pairs scale as C(n,2) = O(n^2). Quick estimate: P(collision) ≈ 1 - exp(-n^2 / (2·365)). At n=23, n^2/(2·365) ≈ 0.725, so P ≈ 1 - e^(-0.725) ≈ 0.51.",
    stuckHints: [
      "Count PAIRS, not people. C(23,2) = 253.",
      "P(no collision) ≈ exp(-pairs / 365) for small per-pair rate.",
      "Most people guess ~5%. Why is the right answer ~50%?",
    ],
    insightTags: ["birthday-paradox", "pairs-not-elements", "complement-trick"],
    answer: "≈ 0.507 (about 50.7%)",
    answerType: "numeric",
    acceptableTolerance: 0.1,
  },
  {
    id: "prob-variance-coin-flip",
    source: "custom",
    url: "https://en.wikipedia.org/wiki/Bernoulli_distribution",
    title: "Variance of a single fair coin flip (X=1 if heads, 0 if tails)?",
    estMinutes: 2,
    kind: "estimation",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 1,
    canonicalInsight:
      "Bernoulli(p) variance = p(1-p). Maximized at p=1/2, giving 1/4 = 0.25. Memo: any Bernoulli variance peaks at the fair-coin case; far from 1/2 the variance shrinks (a biased coin is more predictable).",
    stuckHints: [
      "Var(X) = E[X^2] - E[X]^2. For Bernoulli, X^2 = X.",
      "Formula: p(1-p) for Bernoulli(p).",
      "Maximum variance for a 0/1 distribution occurs at p = 1/2.",
    ],
    insightTags: ["bernoulli-variance", "expected-value"],
    answer: "0.25 (1/4)",
    answerType: "numeric",
    acceptableTolerance: 0.05,
  },
  {
    id: "prob-flips-until-hth",
    source: "custom",
    url: "https://data140.org/sp17/textbook/ch13/Waiting_Till_a_Pattern_Appears.html",
    title: "Expected # of fair coin flips to first see the pattern HTH?",
    estMinutes: 5,
    kind: "estimation",
    requiredModules: [],
    difficulty: "stretch",
    transferDistance: 3,
    canonicalInsight:
      "For HTH: E[T] = 10. Pattern formula via autocorrelation: E[T] = sum over self-overlaps. HTH overlaps with itself at the prefix 'H' (length 1), giving 2^3 + 2^1 = 10. Versus HTT (no self-overlap): 2^3 = 8. Counter-intuitive: patterns with self-overlap take LONGER to appear because false starts reset more often.",
    stuckHints: [
      "Set up states by 'how much of HTH have I matched so far'.",
      "Martingale / Conway leading-number formula: sum 2^k over matching prefix-suffix lengths.",
      "Compare to HTT — which takes longer, and why?",
    ],
    insightTags: ["pattern-waiting-time", "expected-value", "autocorrelation-conway"],
    answer: "10",
    answerType: "numeric",
    acceptableTolerance: 0.1,
  },
];
