import type { LabProblem } from "./types";

// Solving Lab — Jane Street puzzles + probability/combinatorics classics.
//
// Two content buckets in one file:
//   1. Jane Street puzzles (source: "jane-street") — puzzles from the
//      janestreet.com/puzzles archive selected for elegance and transferability.
//   2. Probability/combinatorics classics (source: "puzzle") — canonical
//      problems NOT already in problems-puzzles.ts, chosen for their
//      "aha-moment" insights that generalize far beyond the specific problem.
//
// All entries: kind: "puzzle", requiredModules: [].
export const PROBLEMS_JANE_STREET: LabProblem[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // JANE STREET PUZZLES
  // ══════════════════════════════════════════════════════════════════════════

  // ── Warm-up ───────────────────────────────────────────────────────────────
  {
    id: "js-some-off-square",
    source: "jane-street",
    url: "https://www.janestreet.com/puzzles/some-off-square-index/",
    title: "Some Off Square (Geometric Probability)",
    estMinutes: 30,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 2,
    problemStatement:
      "A circle is randomly generated by sampling two points uniformly and independently from the interior of a unit square, then using those two points as the endpoints of a diameter. What is the probability that the circle extends at least partially outside the square? Express your answer in exact form.",
    canonicalInsight:
      "Break the event into cases by conditioning on where the diameter's midpoint falls and whether the radius reaches a boundary — geometric probability over a square factors naturally into independent x- and y-coordinates, and the complement (entirely inside) is a product of two 1D containment events.",
    stuckHints: [
      "When is the circle entirely inside the square? Express that in terms of the midpoint and the half-diameter.",
      "If two uniform points on [0,1] define a segment, what is the distribution of their midpoint and half-length?",
      "Can you decompose the 2D probability over the x- and y-axes independently?",
    ],
    insightTags: ["conditional-probability", "symmetry"],
  },
  {
    id: "js-figurine-figuring",
    source: "jane-street",
    url: "https://www.janestreet.com/puzzles/figurine-figuring-index/",
    title: "Figurine Figuring (Order Statistics Under Stopping)",
    estMinutes: 35,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 3,
    problemStatement:
      "A bag contains 78 figurines from 'The Twelve Days of Christmas': 12 drummers drumming, 11 pipers piping, 10 lords a-leaping, and so on down to 1 partridge in a pear tree. Jane draws figurines uniformly at random, without replacement, and stops the moment she pulls the partridge. She keeps the partridge and gives Alex everything else she drew. If n is the maximum number of figurines of any single type that Alex receives, what is the expected value of n, expressed to seven significant figures?",
    canonicalInsight:
      "The partridge acts as a random stopping time in a uniform draw — conditioning on its position k (uniform on 1..78) turns each other type's count into a hypergeometric random variable, so E[n] decomposes via linearity-of-expectation over indicator events that 'type i contributes exactly j copies', which sum cleanly over the stopping-time distribution.",
    stuckHints: [
      "Condition on where the partridge appears in the random order — what does that say about how many of each other type appear before it?",
      "Given the partridge is at position k, how many of the 12 drummers would Alex expect to receive?",
      "Can you write E[max over types] in terms of P(at least one type has count ≥ j) using the tail-sum identity?",
    ],
    insightTags: ["tail-sum-identity", "linearity-of-expectation", "conditional-probability"],
  },
  {
    id: "js-candy-collectors",
    source: "jane-street",
    url: "https://www.janestreet.com/puzzles/candy-collectors-index/",
    title: "Candy Collectors (Combinatorial Probability)",
    estMinutes: 40,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 3,
    problemStatement:
      "Five children take turns receiving candy. All 25 pieces — 5 identical copies each of 5 different types — are arranged in a uniformly random order and dealt out: the first 5 to child 1, the next 5 to child 2, and so on. What is the probability that each child has exactly one type of candy that they hold strictly more of than every other child? Express your answer as an exact fraction in lowest terms.",
    canonicalInsight:
      "The event decomposes into a double-counting problem: count the ordered arrangements where each child's private maximum is uniquely attained, using inclusion-exclusion over the symmetric group of candy-type permutations — the symmetry between the five types collapses the giant multinomial sum into a product of smaller ballot-style counts.",
    stuckHints: [
      "What does it take for child 1 to be the unique holder of the most of some type? Try with just 2 children and 2 types first.",
      "How many ways can 5 identical copies of one type be split 5-ways among the children so that one child has strictly more than the others?",
      "Can you use the symmetry between types (the labels don't matter) to simplify the count?",
    ],
    insightTags: ["inclusion-exclusion", "indicator-decomposition", "symmetry"],
  },
  {
    id: "js-robot-baseball",
    source: "jane-street",
    url: "https://www.janestreet.com/puzzles/robot-baseball-index/",
    title: "Robot Baseball (Game Theory + Mixed Strategies)",
    estMinutes: 50,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "stretch",
    transferDistance: 3,
    problemStatement:
      "Two robots play baseball. Each pitch, the pitcher simultaneously chooses to throw a ball or a strike, while the batter chooses to wait or swing. A thrown ball + batter waits: balls counter increases. A thrown strike + batter waits: strikes counter increases. A thrown ball + batter swings: strikes counter increases. A thrown strike + batter swings: the batter hits a home run (scoring 4 points) with probability p, or gets a strike otherwise. An at-bat ends when balls reach 4 (batter scores 1), strikes reach 3 (batter scores 0), or a home run is hit. Assuming both players use optimal mixed strategies and the league has chosen p to maximize the probability q of reaching a full count (3 balls, 2 strikes), find q to ten decimal places.",
    canonicalInsight:
      "At each count, the optimal mixed strategy is a Nash equilibrium of a zero-sum game whose payoff matrix is the batter's expected score from that count — solve backward from terminal counts (minimax), then the externally chosen p optimizes a smooth function of these equilibria, reducing a combinatorial game to a 1D calculus problem.",
    stuckHints: [
      "At any given count, the pitcher and batter are playing a 2×2 zero-sum game — what is the payoff matrix in terms of expected final score?",
      "Solve the terminal counts (3 balls or 2 strikes) first, then work backward using backward induction.",
      "Once you have the Nash equilibrium strategies as functions of p, how does p affect the probability of reaching full count?",
    ],
    insightTags: ["backward-induction", "rational-agent-modeling"],
  },
  {
    id: "js-robot-javelin",
    source: "jane-street",
    url: "https://www.janestreet.com/puzzles/robot-javelin-index/",
    title: "Robot Javelin (Nash Equilibrium + Information Asymmetry)",
    estMinutes: 45,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "stretch",
    transferDistance: 3,
    problemStatement:
      "Two robots compete in javelin. Each robot makes a first throw with distance drawn uniformly from [0, 1], then decides whether to keep that result or discard it and take a second throw (also uniform [0, 1]). The robot with the larger final distance wins. Robot Spears has exploited a protocol flaw: before deciding whether to re-throw, it receives one bit of information revealing whether its opponent Java-lin's first throw was above or below some threshold d (which Spears chose optimally). Java-lin can adjust its strategy knowing about this exploit. What is Java-lin's maximum achievable winning probability?",
    canonicalInsight:
      "The base game has a symmetric Nash equilibrium where each robot re-throws iff its first throw is below 1/2; the one-bit information leak breaks this symmetry by splitting Java-lin's strategy into two cases conditioned on Spears knowing it's above or below d — Java-lin's best response is a threshold strategy that optimally exploits the known structure of Spears's updated mixed strategy.",
    stuckHints: [
      "What is the Nash equilibrium strategy in the base game (without the information leak)?",
      "If Spears knows only whether your throw is above or below d, how does that change Spears's optimal decision?",
      "Java-lin now faces a known but asymmetric opponent — can you write Java-lin's win probability as a function of its own threshold and optimize?",
    ],
    insightTags: ["backward-induction", "rational-agent-modeling", "information-leak"],
  },
  {
    id: "js-single-cross",
    source: "jane-street",
    url: "https://www.janestreet.com/puzzles/single-cross-index/",
    title: "Single Cross (Geometric Probability — Buffon's Needle Variant)",
    estMinutes: 40,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    problemStatement:
      "A random line segment of length D is placed on an infinite plane ruled with a square unit grid (gridlines at every integer coordinate in both axes). The segment's position and orientation are chosen uniformly at random. What length D maximizes the probability that the segment crosses exactly one gridline, and what is that maximal probability?",
    canonicalInsight:
      "The expected number of crossings is linear in D (by linearity of expectation + Buffon's needle), but 'exactly one crossing' is a non-monotone event — for short D the probability is nearly 0 (too short to reach a line), for long D it's also small (almost certainly crosses multiple lines), so the maximum sits at an interior D where you balance the two failure modes by optimizing a trigonometric integral.",
    stuckHints: [
      "Use Buffon's needle: the expected number of gridline crossings for a segment of length D is a known formula — what is it?",
      "P(exactly 1 crossing) ≠ E[crossings]. How do you go from expected crossings to the probability of exactly 1?",
      "For what range of D can a segment cross exactly 1 gridline at all? What constraint does this put on D?",
    ],
    insightTags: ["linearity-of-expectation", "indicator-decomposition", "symmetry"],
  },
  {
    id: "js-beside-the-point",
    source: "jane-street",
    url: "https://www.janestreet.com/puzzles/beside-the-point-index/",
    title: "Beside the Point (Geometric Probability — Voronoi on a Square)",
    estMinutes: 45,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    problemStatement:
      "Two random points — one red, one blue — are chosen uniformly and independently from the interior of a unit square. What is the probability that there exists a point on the side of the square nearest to the blue point that is equidistant to both the blue and the red points? Express your answer to ten decimal places, or exactly.",
    canonicalInsight:
      "The equidistant point on the nearest side exists iff the red point is within the 'Voronoi shadow' cast by the blue point onto that wall — equivalently, iff the perpendicular from the red point meets the nearest side before the red point is closer to an adjacent or opposite side; this reduces to a conjunction of linear inequalities whose probability decomposes into a clean double integral over the relative positions.",
    stuckHints: [
      "Fix the blue point and ask: for which positions of red does an equidistant point on the nearest wall exist? Sketch the region.",
      "The equidistant condition on the wall defines a parabola (the set of points equidistant from red and blue) — when does that parabola hit the wall on the blue-nearest side?",
      "The problem has 4-fold symmetry (nearest side is left/right/top/bottom) — condition on which side is nearest to blue and integrate.",
    ],
    insightTags: ["conditional-probability", "symmetry", "change-of-coordinates"],
  },
  {
    id: "js-hooks-7",
    source: "jane-street",
    url: "https://www.janestreet.com/puzzles/hooks-7-index/",
    title: "Hooks 7 (L-Shaped Partition + Connectivity Counting)",
    estMinutes: 60,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "stretch",
    transferDistance: 2,
    problemStatement:
      "Partition a square grid into 9 L-shaped 'hooks' of decreasing sizes (the largest is a 9×9 L-shape with 17 squares, down to a 1×1 single square). Fill each hook with its matching digit: nine 9s in the 9-hook, eight 8s in the 8-hook, and so on. The filled squares must form one connected region (orthogonal adjacency), every 2×2 sub-square must contain at least one empty square, and the sum of values in each of the 19 connected shaded regions must be the same. Once solved, compute the product of the areas of the connected groups of empty squares.",
    canonicalInsight:
      "The equal-sum constraint on 19 regions converts a free placement puzzle into a highly over-determined system — the key insight is that the target sum is forced (total filled value divided by 19), and then the hook placement is constrained by both connectivity and the shared-sum condition, making constraint propagation and symmetry-breaking the right attack rather than brute-force search.",
    stuckHints: [
      "What must the sum of each shaded region equal? (Compute total sum of all filled digits first.)",
      "Try placing the 9-hook and 8-hook first — the connectivity constraint limits their relative positions strongly.",
      "What does the '2×2 must contain an empty square' rule say about where dense hooks can be placed?",
    ],
    insightTags: ["invariant-search", "small-example-discovery"],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PROBABILITY / COMBINATORICS CLASSICS
  // (not already in problems-puzzles.ts)
  // ══════════════════════════════════════════════════════════════════════════

  // ── Warm-up ───────────────────────────────────────────────────────────────
  {
    id: "puzzle-gamblers-ruin",
    source: "puzzle",
    url: "https://en.wikipedia.org/wiki/Gambler%27s_ruin",
    title: "Gambler's Ruin",
    estMinutes: 30,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 2,
    problemStatement:
      "A gambler starts with $k and plays a fair coin-flip game: win $1 with probability 1/2, lose $1 with probability 1/2. The game ends when the gambler either reaches $N (winning) or $0 (ruined). What is the probability of reaching $N before being ruined? Generalize to biased coin (p ≠ 1/2).",
    canonicalInsight:
      "For a fair game the ruin probability is exactly k/N — the gambler's fortune is a martingale, so its expected value is conserved, and the two boundary outcomes (0 or N) must average to the starting value k; for a biased game the martingale is (q/p)^{fortune}, giving ruin probability (1-(q/p)^k)/(1-(q/p)^N), which reveals that even a tiny house edge compounds to near-certain ruin at large N.",
    stuckHints: [
      "Let p_k = P(reach N | start at k). Write the recurrence p_k = (1/2)p_{k+1} + (1/2)p_{k-1} and guess a linear solution.",
      "What does the martingale property (the process has constant expected value) imply about p_k?",
      "For the biased case, guess an exponential solution to the recurrence — what base makes it work?",
    ],
    insightTags: ["markov-chain-states", "backward-induction"],
  },
  {
    id: "puzzle-ballot-problem",
    source: "puzzle",
    url: "https://en.wikipedia.org/wiki/Bertrand_ballot_problem",
    title: "Ballot Problem (Reflection Principle)",
    estMinutes: 35,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 3,
    problemStatement:
      "In an election, candidate A receives a votes and candidate B receives b votes, with a > b. The ballots are counted one by one in a uniformly random order. What is the probability that A is strictly ahead of B throughout the entire counting process — that is, A's running total exceeds B's after every single ballot is revealed?",
    canonicalInsight:
      "The ballot problem's answer is (a−b)/(a+b), proved by a reflection argument: map each counting sequence where B ties or leads at some point to a unique sequence starting with B's ballot, establishing a bijection between 'bad' paths and all paths starting with B — this reflection principle over lattice paths is the same tool that prices barrier options in finance.",
    stuckHints: [
      "Try small cases: a=2, b=1 (3 ballots). Enumerate and count.",
      "Draw the counting as a lattice path from (0,0) to (a,b). When does the path touch or cross the diagonal?",
      "Can you find a 1-to-1 map between 'bad' paths and some easily-counted set of paths?",
    ],
    insightTags: ["symmetry-cancellation", "indicator-decomposition"],
  },
  {
    id: "puzzle-coupon-collector",
    source: "puzzle",
    url: "https://en.wikipedia.org/wiki/Coupon_collector%27s_problem",
    title: "Coupon Collector's Problem",
    estMinutes: 25,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 2,
    problemStatement:
      "There are n different types of coupons, and each purchase gives you one coupon selected uniformly at random (with replacement). How many purchases do you need, on average, to collect at least one of every type? This is the coupon collector's problem — find the exact expected value.",
    canonicalInsight:
      "Decompose the process into n phases: phase k runs from having k−1 distinct coupons until you get the k-th new one, and in phase k the probability of success per draw is (n−k+1)/n, giving a geometric wait with mean n/(n−k+1); summing over phases gives E[T] = n·H_n = n·(1 + 1/2 + 1/3 + ... + 1/n) ≈ n ln n — the harmonic series appears because each new type is progressively harder to find.",
    stuckHints: [
      "How long until you get the SECOND distinct coupon, given you already have one? The third, given you have two?",
      "Each 'new coupon' phase is a geometric trial — what is the success probability in phase k?",
      "Sum up the expected waiting times across all n phases.",
    ],
    insightTags: ["linearity-of-expectation", "geometric-distribution", "harmonic-series-divergence"],
  },
  {
    id: "puzzle-two-envelope",
    source: "puzzle",
    url: "https://en.wikipedia.org/wiki/Two_envelopes_problem",
    title: "Two-Envelope Paradox",
    estMinutes: 30,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "standard",
    transferDistance: 3,
    problemStatement:
      "Two envelopes each contain money. One has twice as much as the other, but you don't know which. You pick one and see it contains $X. You are offered a chance to switch. A seemingly valid argument says: the other envelope contains either $2X (with probability 1/2) or $X/2 (with probability 1/2), giving expected value 5X/4 > X, so you should always switch — yet by symmetry you should be indifferent. What's wrong with the argument?",
    canonicalInsight:
      "The paradox conflates two different probability models: in any fixed prior over envelope amounts, the conditional expected value of the other envelope given yours is X cannot simultaneously be 5X/4 for ALL values of X — the 1/2 probability in the argument is not the true conditional probability, which depends on the prior and takes different values for different X; resolving the paradox requires specifying the prior, and for any proper prior the switching argument breaks down.",
    stuckHints: [
      "Try a concrete example: the envelopes contain ($1, $2) or ($2, $4) each with probability 1/2. What is the correct conditional probability that the other envelope has twice as much, given you see $2?",
      "The argument treats P(other = 2X | mine = X) = 1/2 for all X. Is this consistent with any prior distribution on envelope amounts?",
      "What would it mean for E[other | mine = X] to equal 5X/4 for every X? What would that imply about E[other]?",
    ],
    insightTags: ["conditional-probability", "sample-space-care"],
  },
  {
    id: "puzzle-st-petersburg",
    source: "puzzle",
    url: "https://en.wikipedia.org/wiki/St._Petersburg_paradox",
    title: "St. Petersburg Paradox",
    estMinutes: 20,
    kind: "puzzle",
    requiredModules: [],
    difficulty: "warm-up",
    transferDistance: 2,
    problemStatement:
      "A casino offers the following game: a fair coin is flipped repeatedly until it lands tails. If tails first appears on flip k, you win $2^k. What is the expected value of this game? How much would you pay to play it, and why does your answer differ from the expected value?",
    canonicalInsight:
      "The expected value is infinite (each flip k contributes 2^k · (1/2)^k = 1, and there are infinitely many flip outcomes), yet no rational person would pay more than ~$20 to play — the resolution is that expected-value maximization fails when outcomes have diminishing marginal utility; logarithmic utility U($x) = log x gives a finite price (around $2 for natural log), introducing the concept that decision-making under uncertainty must account for risk preferences, not just raw expectations.",
    stuckHints: [
      "Compute the contribution of flip k to expected value: 2^k × P(win on flip k). Sum over all k.",
      "Why do large-but-rare wins (e.g., $2^{40} with probability 2^{-40}) count so heavily in expected value but matter so little in practice?",
      "What if you replaced the payoff with log(payoff)? Does the expected utility converge?",
    ],
    insightTags: ["expected-value", "geometric-distribution"],
  },
];
