// Step 5 problem counts per module. Foundations is omitted — it is a
// skill checklist, not a problem set, so no progress badge is shown.
// Update when a module's problem list changes.
export const PROBLEM_COUNTS: Record<string, number> = {
  "foundations":     7,
  "arrays-hashing":  9,
  "sorting":         7,
  "prefix-sums":     9,
  "two-pointers":    7,
  "sliding-window":  7,
  "stack":           7,
  "monotonic-stack": 7,
  "monotonic-deque": 6,
  "linked-list":     10,
  "binary-search":   8,
  "bs-answer":       8,
  "backtracking":    10,
  "trees":           10,
  "tries":           5,
  "heap":            8,
  "greedy":          8,
  "intervals":       6,
  "graph-traversal": 8,
  "topo-sort":       6,
  "union-find":      6,
  "shortest-paths":  6,
  "mst":             6,
  "adv-graphs":      6,
  "dp-intro":        8,
  "dp-2d":           8,
};
