export const PATTERNS = [
  "Two pointers / sliding window",
  "Binary search",
  "Hash map / set",
  "Stack (monotonic / parsing)",
  "Linked list",
  "Tree traversal",
  "BFS / DFS on grids",
  "Backtracking",
  "Heap / top-K",
  "Greedy + sorting",
  "Intervals",
  "Prefix sum / difference array",
  "1D DP",
  "2D DP",
  "DP on subsequences",
  "Knapsack",
  "Shortest path",
  "Topological sort",
  "Union-find",
  "Trie",
  "Segment tree / BIT",
  "Bit manipulation",
  "Math / number theory",
  "DP on trees",
  "State-compression DP",
] as const;

export type Pattern = (typeof PATTERNS)[number];
